//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Clientes.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClienteContado_CLI))]
    public partial class DestinatarioFrecuente_CLI: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long DEF_IdClienteContado
        {
            get { return _dEF_IdClienteContado; }
            set
            {
                if (_dEF_IdClienteContado != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'DEF_IdClienteContado' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (ClienteContado_CLI != null && ClienteContado_CLI.CLC_IdClienteContado != value)
                        {
                            ClienteContado_CLI = null;
                        }
                    }
                    _dEF_IdClienteContado = value;
                    OnPropertyChanged("DEF_IdClienteContado");
                }
            }
        }
        private long _dEF_IdClienteContado;
    
        [DataMember]
        public long DEF_IdDestinatarioFrecuente
        {
            get { return _dEF_IdDestinatarioFrecuente; }
            set
            {
                if (_dEF_IdDestinatarioFrecuente != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'DEF_IdDestinatarioFrecuente' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (ClienteContado_CLI1 != null && ClienteContado_CLI1.CLC_IdClienteContado != value)
                        {
                            ClienteContado_CLI1 = null;
                        }
                    }
                    _dEF_IdDestinatarioFrecuente = value;
                    OnPropertyChanged("DEF_IdDestinatarioFrecuente");
                }
            }
        }
        private long _dEF_IdDestinatarioFrecuente;
    
        [DataMember]
        public long DEF_IdUltimoCentroServDestino
        {
            get { return _dEF_IdUltimoCentroServDestino; }
            set
            {
                if (_dEF_IdUltimoCentroServDestino != value)
                {
                    _dEF_IdUltimoCentroServDestino = value;
                    OnPropertyChanged("DEF_IdUltimoCentroServDestino");
                }
            }
        }
        private long _dEF_IdUltimoCentroServDestino;
    
        [DataMember]
        public string DEF_DescUltimoCentroServDestino
        {
            get { return _dEF_DescUltimoCentroServDestino; }
            set
            {
                if (_dEF_DescUltimoCentroServDestino != value)
                {
                    _dEF_DescUltimoCentroServDestino = value;
                    OnPropertyChanged("DEF_DescUltimoCentroServDestino");
                }
            }
        }
        private string _dEF_DescUltimoCentroServDestino;
    
        [DataMember]
        public System.DateTime DEF_FechaGrabacion
        {
            get { return _dEF_FechaGrabacion; }
            set
            {
                if (_dEF_FechaGrabacion != value)
                {
                    _dEF_FechaGrabacion = value;
                    OnPropertyChanged("DEF_FechaGrabacion");
                }
            }
        }
        private System.DateTime _dEF_FechaGrabacion;
    
        [DataMember]
        public string DEF_CreadoPor
        {
            get { return _dEF_CreadoPor; }
            set
            {
                if (_dEF_CreadoPor != value)
                {
                    _dEF_CreadoPor = value;
                    OnPropertyChanged("DEF_CreadoPor");
                }
            }
        }
        private string _dEF_CreadoPor;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public ClienteContado_CLI ClienteContado_CLI
        {
            get { return _clienteContado_CLI; }
            set
            {
                if (!ReferenceEquals(_clienteContado_CLI, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (DEF_IdClienteContado != value.CLC_IdClienteContado)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _clienteContado_CLI;
                    _clienteContado_CLI = value;
                    FixupClienteContado_CLI(previousValue);
                    OnNavigationPropertyChanged("ClienteContado_CLI");
                }
            }
        }
        private ClienteContado_CLI _clienteContado_CLI;
    
        [DataMember]
        public ClienteContado_CLI ClienteContado_CLI1
        {
            get { return _clienteContado_CLI1; }
            set
            {
                if (!ReferenceEquals(_clienteContado_CLI1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (DEF_IdDestinatarioFrecuente != value.CLC_IdClienteContado)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _clienteContado_CLI1;
                    _clienteContado_CLI1 = value;
                    FixupClienteContado_CLI1(previousValue);
                    OnNavigationPropertyChanged("ClienteContado_CLI1");
                }
            }
        }
        private ClienteContado_CLI _clienteContado_CLI1;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ClienteContado_CLI = null;
            ClienteContado_CLI1 = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupClienteContado_CLI(ClienteContado_CLI previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.DestinatarioFrecuente_CLI.Contains(this))
            {
                previousValue.DestinatarioFrecuente_CLI.Remove(this);
            }
    
            if (ClienteContado_CLI != null)
            {
                if (!ClienteContado_CLI.DestinatarioFrecuente_CLI.Contains(this))
                {
                    ClienteContado_CLI.DestinatarioFrecuente_CLI.Add(this);
                }
    
                DEF_IdClienteContado = ClienteContado_CLI.CLC_IdClienteContado;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ClienteContado_CLI")
                    && (ChangeTracker.OriginalValues["ClienteContado_CLI"] == ClienteContado_CLI))
                {
                    ChangeTracker.OriginalValues.Remove("ClienteContado_CLI");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ClienteContado_CLI", previousValue);
                }
                if (ClienteContado_CLI != null && !ClienteContado_CLI.ChangeTracker.ChangeTrackingEnabled)
                {
                    ClienteContado_CLI.StartTracking();
                }
            }
        }
    
        private void FixupClienteContado_CLI1(ClienteContado_CLI previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.DestinatarioFrecuente_CLI1.Contains(this))
            {
                previousValue.DestinatarioFrecuente_CLI1.Remove(this);
            }
    
            if (ClienteContado_CLI1 != null)
            {
                if (!ClienteContado_CLI1.DestinatarioFrecuente_CLI1.Contains(this))
                {
                    ClienteContado_CLI1.DestinatarioFrecuente_CLI1.Add(this);
                }
    
                DEF_IdDestinatarioFrecuente = ClienteContado_CLI1.CLC_IdClienteContado;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ClienteContado_CLI1")
                    && (ChangeTracker.OriginalValues["ClienteContado_CLI1"] == ClienteContado_CLI1))
                {
                    ChangeTracker.OriginalValues.Remove("ClienteContado_CLI1");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ClienteContado_CLI1", previousValue);
                }
                if (ClienteContado_CLI1 != null && !ClienteContado_CLI1.ChangeTracker.ChangeTrackingEnabled)
                {
                    ClienteContado_CLI1.StartTracking();
                }
            }
        }

        #endregion

    }
}
