//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Clientes.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Cargo_SEG))]
    [KnownType(typeof(PersonalContrato_CLI))]
    [KnownType(typeof(Contrato_CLI))]
    [KnownType(typeof(Localidad_PAR))]
    [KnownType(typeof(TipoIdentificacion_PAR))]
    public partial class PersonaInterna_PAR: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long PEI_IdPersonaInterna
        {
            get { return _pEI_IdPersonaInterna; }
            set
            {
                if (_pEI_IdPersonaInterna != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PEI_IdPersonaInterna' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pEI_IdPersonaInterna = value;
                    OnPropertyChanged("PEI_IdPersonaInterna");
                }
            }
        }
        private long _pEI_IdPersonaInterna;
    
        [DataMember]
        public string PEI_IdTipoIdentificacion
        {
            get { return _pEI_IdTipoIdentificacion; }
            set
            {
                if (_pEI_IdTipoIdentificacion != value)
                {
                    ChangeTracker.RecordOriginalValue("PEI_IdTipoIdentificacion", _pEI_IdTipoIdentificacion);
                    if (!IsDeserializing)
                    {
                        if (TipoIdentificacion_PAR != null && TipoIdentificacion_PAR.TII_IdTipoIdentificacion != value)
                        {
                            TipoIdentificacion_PAR = null;
                        }
                    }
                    _pEI_IdTipoIdentificacion = value;
                    OnPropertyChanged("PEI_IdTipoIdentificacion");
                }
            }
        }
        private string _pEI_IdTipoIdentificacion;
    
        [DataMember]
        public string PEI_Identificacion
        {
            get { return _pEI_Identificacion; }
            set
            {
                if (_pEI_Identificacion != value)
                {
                    _pEI_Identificacion = value;
                    OnPropertyChanged("PEI_Identificacion");
                }
            }
        }
        private string _pEI_Identificacion;
    
        [DataMember]
        public int PEI_IdCargo
        {
            get { return _pEI_IdCargo; }
            set
            {
                if (_pEI_IdCargo != value)
                {
                    ChangeTracker.RecordOriginalValue("PEI_IdCargo", _pEI_IdCargo);
                    if (!IsDeserializing)
                    {
                        if (Cargo_SEG != null && Cargo_SEG.CAR_IdCargo != value)
                        {
                            Cargo_SEG = null;
                        }
                    }
                    _pEI_IdCargo = value;
                    OnPropertyChanged("PEI_IdCargo");
                }
            }
        }
        private int _pEI_IdCargo;
    
        [DataMember]
        public string PEI_Nombre
        {
            get { return _pEI_Nombre; }
            set
            {
                if (_pEI_Nombre != value)
                {
                    _pEI_Nombre = value;
                    OnPropertyChanged("PEI_Nombre");
                }
            }
        }
        private string _pEI_Nombre;
    
        [DataMember]
        public string PEI_PrimerApellido
        {
            get { return _pEI_PrimerApellido; }
            set
            {
                if (_pEI_PrimerApellido != value)
                {
                    _pEI_PrimerApellido = value;
                    OnPropertyChanged("PEI_PrimerApellido");
                }
            }
        }
        private string _pEI_PrimerApellido;
    
        [DataMember]
        public string PEI_SegundoApellido
        {
            get { return _pEI_SegundoApellido; }
            set
            {
                if (_pEI_SegundoApellido != value)
                {
                    _pEI_SegundoApellido = value;
                    OnPropertyChanged("PEI_SegundoApellido");
                }
            }
        }
        private string _pEI_SegundoApellido;
    
        [DataMember]
        public string PEI_Direccion
        {
            get { return _pEI_Direccion; }
            set
            {
                if (_pEI_Direccion != value)
                {
                    _pEI_Direccion = value;
                    OnPropertyChanged("PEI_Direccion");
                }
            }
        }
        private string _pEI_Direccion;
    
        [DataMember]
        public string PEI_Municipio
        {
            get { return _pEI_Municipio; }
            set
            {
                if (_pEI_Municipio != value)
                {
                    ChangeTracker.RecordOriginalValue("PEI_Municipio", _pEI_Municipio);
                    if (!IsDeserializing)
                    {
                        if (Localidad_PAR != null && Localidad_PAR.LOC_IdLocalidad != value)
                        {
                            Localidad_PAR = null;
                        }
                    }
                    _pEI_Municipio = value;
                    OnPropertyChanged("PEI_Municipio");
                }
            }
        }
        private string _pEI_Municipio;
    
        [DataMember]
        public string PEI_Telefono
        {
            get { return _pEI_Telefono; }
            set
            {
                if (_pEI_Telefono != value)
                {
                    _pEI_Telefono = value;
                    OnPropertyChanged("PEI_Telefono");
                }
            }
        }
        private string _pEI_Telefono;
    
        [DataMember]
        public string PEI_Email
        {
            get { return _pEI_Email; }
            set
            {
                if (_pEI_Email != value)
                {
                    _pEI_Email = value;
                    OnPropertyChanged("PEI_Email");
                }
            }
        }
        private string _pEI_Email;
    
        [DataMember]
        public Nullable<long> PEI_IdRegionalAdm
        {
            get { return _pEI_IdRegionalAdm; }
            set
            {
                if (_pEI_IdRegionalAdm != value)
                {
                    _pEI_IdRegionalAdm = value;
                    OnPropertyChanged("PEI_IdRegionalAdm");
                }
            }
        }
        private Nullable<long> _pEI_IdRegionalAdm;
    
        [DataMember]
        public string PEI_Comentarios
        {
            get { return _pEI_Comentarios; }
            set
            {
                if (_pEI_Comentarios != value)
                {
                    _pEI_Comentarios = value;
                    OnPropertyChanged("PEI_Comentarios");
                }
            }
        }
        private string _pEI_Comentarios;
    
        [DataMember]
        public System.DateTime PEI_FechaGrabacion
        {
            get { return _pEI_FechaGrabacion; }
            set
            {
                if (_pEI_FechaGrabacion != value)
                {
                    _pEI_FechaGrabacion = value;
                    OnPropertyChanged("PEI_FechaGrabacion");
                }
            }
        }
        private System.DateTime _pEI_FechaGrabacion;
    
        [DataMember]
        public string PEI_CreadoPor
        {
            get { return _pEI_CreadoPor; }
            set
            {
                if (_pEI_CreadoPor != value)
                {
                    _pEI_CreadoPor = value;
                    OnPropertyChanged("PEI_CreadoPor");
                }
            }
        }
        private string _pEI_CreadoPor;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Cargo_SEG Cargo_SEG
        {
            get { return _cargo_SEG; }
            set
            {
                if (!ReferenceEquals(_cargo_SEG, value))
                {
                    var previousValue = _cargo_SEG;
                    _cargo_SEG = value;
                    FixupCargo_SEG(previousValue);
                    OnNavigationPropertyChanged("Cargo_SEG");
                }
            }
        }
        private Cargo_SEG _cargo_SEG;
    
        [DataMember]
        public PersonalContrato_CLI PersonalContrato_CLI
        {
            get { return _personalContrato_CLI; }
            set
            {
                if (!ReferenceEquals(_personalContrato_CLI, value))
                {
                    var previousValue = _personalContrato_CLI;
                    _personalContrato_CLI = value;
                    FixupPersonalContrato_CLI(previousValue);
                    OnNavigationPropertyChanged("PersonalContrato_CLI");
                }
            }
        }
        private PersonalContrato_CLI _personalContrato_CLI;
    
        [DataMember]
        public TrackableCollection<Contrato_CLI> Contrato_CLI
        {
            get
            {
                if (_contrato_CLI == null)
                {
                    _contrato_CLI = new TrackableCollection<Contrato_CLI>();
                    _contrato_CLI.CollectionChanged += FixupContrato_CLI;
                }
                return _contrato_CLI;
            }
            set
            {
                if (!ReferenceEquals(_contrato_CLI, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_contrato_CLI != null)
                    {
                        _contrato_CLI.CollectionChanged -= FixupContrato_CLI;
                    }
                    _contrato_CLI = value;
                    if (_contrato_CLI != null)
                    {
                        _contrato_CLI.CollectionChanged += FixupContrato_CLI;
                    }
                    OnNavigationPropertyChanged("Contrato_CLI");
                }
            }
        }
        private TrackableCollection<Contrato_CLI> _contrato_CLI;
    
        [DataMember]
        public TrackableCollection<Contrato_CLI> Contrato_CLI1
        {
            get
            {
                if (_contrato_CLI1 == null)
                {
                    _contrato_CLI1 = new TrackableCollection<Contrato_CLI>();
                    _contrato_CLI1.CollectionChanged += FixupContrato_CLI1;
                }
                return _contrato_CLI1;
            }
            set
            {
                if (!ReferenceEquals(_contrato_CLI1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_contrato_CLI1 != null)
                    {
                        _contrato_CLI1.CollectionChanged -= FixupContrato_CLI1;
                    }
                    _contrato_CLI1 = value;
                    if (_contrato_CLI1 != null)
                    {
                        _contrato_CLI1.CollectionChanged += FixupContrato_CLI1;
                    }
                    OnNavigationPropertyChanged("Contrato_CLI1");
                }
            }
        }
        private TrackableCollection<Contrato_CLI> _contrato_CLI1;
    
        [DataMember]
        public Localidad_PAR Localidad_PAR
        {
            get { return _localidad_PAR; }
            set
            {
                if (!ReferenceEquals(_localidad_PAR, value))
                {
                    var previousValue = _localidad_PAR;
                    _localidad_PAR = value;
                    FixupLocalidad_PAR(previousValue);
                    OnNavigationPropertyChanged("Localidad_PAR");
                }
            }
        }
        private Localidad_PAR _localidad_PAR;
    
        [DataMember]
        public TipoIdentificacion_PAR TipoIdentificacion_PAR
        {
            get { return _tipoIdentificacion_PAR; }
            set
            {
                if (!ReferenceEquals(_tipoIdentificacion_PAR, value))
                {
                    var previousValue = _tipoIdentificacion_PAR;
                    _tipoIdentificacion_PAR = value;
                    FixupTipoIdentificacion_PAR(previousValue);
                    OnNavigationPropertyChanged("TipoIdentificacion_PAR");
                }
            }
        }
        private TipoIdentificacion_PAR _tipoIdentificacion_PAR;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Cargo_SEG = null;
            PersonalContrato_CLI = null;
            Contrato_CLI.Clear();
            Contrato_CLI1.Clear();
            Localidad_PAR = null;
            TipoIdentificacion_PAR = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupCargo_SEG(Cargo_SEG previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PersonaInterna_PAR.Contains(this))
            {
                previousValue.PersonaInterna_PAR.Remove(this);
            }
    
            if (Cargo_SEG != null)
            {
                if (!Cargo_SEG.PersonaInterna_PAR.Contains(this))
                {
                    Cargo_SEG.PersonaInterna_PAR.Add(this);
                }
    
                PEI_IdCargo = Cargo_SEG.CAR_IdCargo;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Cargo_SEG")
                    && (ChangeTracker.OriginalValues["Cargo_SEG"] == Cargo_SEG))
                {
                    ChangeTracker.OriginalValues.Remove("Cargo_SEG");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Cargo_SEG", previousValue);
                }
                if (Cargo_SEG != null && !Cargo_SEG.ChangeTracker.ChangeTrackingEnabled)
                {
                    Cargo_SEG.StartTracking();
                }
            }
        }
    
        private void FixupPersonalContrato_CLI(PersonalContrato_CLI previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (PersonalContrato_CLI != null)
            {
                ChangeTracker.ObjectStateChanging += PersonalContrato_CLI.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.PersonaInterna_PAR, this))
            {
                previousValue.PersonaInterna_PAR = null;
            }
    
            if (PersonalContrato_CLI != null)
            {
                PersonalContrato_CLI.PersonaInterna_PAR = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PersonalContrato_CLI")
                    && (ChangeTracker.OriginalValues["PersonalContrato_CLI"] == PersonalContrato_CLI))
                {
                    ChangeTracker.OriginalValues.Remove("PersonalContrato_CLI");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PersonalContrato_CLI", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (PersonalContrato_CLI != null && !PersonalContrato_CLI.ChangeTracker.ChangeTrackingEnabled)
                {
                    PersonalContrato_CLI.StartTracking();
                }
            }
        }
    
        private void FixupLocalidad_PAR(Localidad_PAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PersonaInterna_PAR.Contains(this))
            {
                previousValue.PersonaInterna_PAR.Remove(this);
            }
    
            if (Localidad_PAR != null)
            {
                if (!Localidad_PAR.PersonaInterna_PAR.Contains(this))
                {
                    Localidad_PAR.PersonaInterna_PAR.Add(this);
                }
    
                PEI_Municipio = Localidad_PAR.LOC_IdLocalidad;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Localidad_PAR")
                    && (ChangeTracker.OriginalValues["Localidad_PAR"] == Localidad_PAR))
                {
                    ChangeTracker.OriginalValues.Remove("Localidad_PAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Localidad_PAR", previousValue);
                }
                if (Localidad_PAR != null && !Localidad_PAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    Localidad_PAR.StartTracking();
                }
            }
        }
    
        private void FixupTipoIdentificacion_PAR(TipoIdentificacion_PAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PersonaInterna_PAR.Contains(this))
            {
                previousValue.PersonaInterna_PAR.Remove(this);
            }
    
            if (TipoIdentificacion_PAR != null)
            {
                if (!TipoIdentificacion_PAR.PersonaInterna_PAR.Contains(this))
                {
                    TipoIdentificacion_PAR.PersonaInterna_PAR.Add(this);
                }
    
                PEI_IdTipoIdentificacion = TipoIdentificacion_PAR.TII_IdTipoIdentificacion;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TipoIdentificacion_PAR")
                    && (ChangeTracker.OriginalValues["TipoIdentificacion_PAR"] == TipoIdentificacion_PAR))
                {
                    ChangeTracker.OriginalValues.Remove("TipoIdentificacion_PAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TipoIdentificacion_PAR", previousValue);
                }
                if (TipoIdentificacion_PAR != null && !TipoIdentificacion_PAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    TipoIdentificacion_PAR.StartTracking();
                }
            }
        }
    
        private void FixupContrato_CLI(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Contrato_CLI item in e.NewItems)
                {
                    item.PersonaInterna_PAR = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Contrato_CLI", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Contrato_CLI item in e.OldItems)
                {
                    if (ReferenceEquals(item.PersonaInterna_PAR, this))
                    {
                        item.PersonaInterna_PAR = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Contrato_CLI", item);
                    }
                }
            }
        }
    
        private void FixupContrato_CLI1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Contrato_CLI item in e.NewItems)
                {
                    item.PersonaInterna_PAR1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Contrato_CLI1", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Contrato_CLI item in e.OldItems)
                {
                    if (ReferenceEquals(item.PersonaInterna_PAR1, this))
                    {
                        item.PersonaInterna_PAR1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Contrato_CLI1", item);
                    }
                }
            }
        }

        #endregion

    }
}
