//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Clientes.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class SucursalesContrato_VCLI: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string SUC_Municipio
        {
            get { return _sUC_Municipio; }
            set
            {
                if (_sUC_Municipio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Municipio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Municipio = value;
                    OnPropertyChanged("SUC_Municipio");
                }
            }
        }
        private string _sUC_Municipio;
    
        [DataMember]
        public int SUC_IdSucursal
        {
            get { return _sUC_IdSucursal; }
            set
            {
                if (_sUC_IdSucursal != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_IdSucursal' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_IdSucursal = value;
                    OnPropertyChanged("SUC_IdSucursal");
                }
            }
        }
        private int _sUC_IdSucursal;
    
        [DataMember]
        public string SUC_Nombre
        {
            get { return _sUC_Nombre; }
            set
            {
                if (_sUC_Nombre != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Nombre' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Nombre = value;
                    OnPropertyChanged("SUC_Nombre");
                }
            }
        }
        private string _sUC_Nombre;
    
        [DataMember]
        public int SUC_ClienteCredito
        {
            get { return _sUC_ClienteCredito; }
            set
            {
                if (_sUC_ClienteCredito != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_ClienteCredito' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_ClienteCredito = value;
                    OnPropertyChanged("SUC_ClienteCredito");
                }
            }
        }
        private int _sUC_ClienteCredito;
    
        [DataMember]
        public string SUC_Zona
        {
            get { return _sUC_Zona; }
            set
            {
                if (_sUC_Zona != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Zona' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Zona = value;
                    OnPropertyChanged("SUC_Zona");
                }
            }
        }
        private string _sUC_Zona;
    
        [DataMember]
        public string SUC_Direccion
        {
            get { return _sUC_Direccion; }
            set
            {
                if (_sUC_Direccion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Direccion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Direccion = value;
                    OnPropertyChanged("SUC_Direccion");
                }
            }
        }
        private string _sUC_Direccion;
    
        [DataMember]
        public string SUC_Telefono
        {
            get { return _sUC_Telefono; }
            set
            {
                if (_sUC_Telefono != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Telefono' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Telefono = value;
                    OnPropertyChanged("SUC_Telefono");
                }
            }
        }
        private string _sUC_Telefono;
    
        [DataMember]
        public string SUC_Fax
        {
            get { return _sUC_Fax; }
            set
            {
                if (_sUC_Fax != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Fax' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Fax = value;
                    OnPropertyChanged("SUC_Fax");
                }
            }
        }
        private string _sUC_Fax;
    
        [DataMember]
        public string SUC_Email
        {
            get { return _sUC_Email; }
            set
            {
                if (_sUC_Email != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Email' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Email = value;
                    OnPropertyChanged("SUC_Email");
                }
            }
        }
        private string _sUC_Email;
    
        [DataMember]
        public string SUC_NombreContacto
        {
            get { return _sUC_NombreContacto; }
            set
            {
                if (_sUC_NombreContacto != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_NombreContacto' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_NombreContacto = value;
                    OnPropertyChanged("SUC_NombreContacto");
                }
            }
        }
        private string _sUC_NombreContacto;
    
        [DataMember]
        public long SUC_AgenciaEncargada
        {
            get { return _sUC_AgenciaEncargada; }
            set
            {
                if (_sUC_AgenciaEncargada != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_AgenciaEncargada' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_AgenciaEncargada = value;
                    OnPropertyChanged("SUC_AgenciaEncargada");
                }
            }
        }
        private long _sUC_AgenciaEncargada;
    
        [DataMember]
        public int SUC_IdSucursalContrato
        {
            get { return _sUC_IdSucursalContrato; }
            set
            {
                if (_sUC_IdSucursalContrato != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_IdSucursalContrato' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_IdSucursalContrato = value;
                    OnPropertyChanged("SUC_IdSucursalContrato");
                }
            }
        }
        private int _sUC_IdSucursalContrato;
    
        [DataMember]
        public int SUC_Contrato
        {
            get { return _sUC_Contrato; }
            set
            {
                if (_sUC_Contrato != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Contrato' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Contrato = value;
                    OnPropertyChanged("SUC_Contrato");
                }
            }
        }
        private int _sUC_Contrato;
    
        [DataMember]
        public string SUC_QueDebeRecoger
        {
            get { return _sUC_QueDebeRecoger; }
            set
            {
                if (_sUC_QueDebeRecoger != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_QueDebeRecoger' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_QueDebeRecoger = value;
                    OnPropertyChanged("SUC_QueDebeRecoger");
                }
            }
        }
        private string _sUC_QueDebeRecoger;
    
        [DataMember]
        public string SUC_Estado
        {
            get { return _sUC_Estado; }
            set
            {
                if (_sUC_Estado != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_Estado' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_Estado = value;
                    OnPropertyChanged("SUC_Estado");
                }
            }
        }
        private string _sUC_Estado;
    
        [DataMember]
        public string LOC_Nombre
        {
            get { return _lOC_Nombre; }
            set
            {
                if (_lOC_Nombre != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LOC_Nombre' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lOC_Nombre = value;
                    OnPropertyChanged("LOC_Nombre");
                }
            }
        }
        private string _lOC_Nombre;
    
        [DataMember]
        public string CES_Nombre
        {
            get { return _cES_Nombre; }
            set
            {
                if (_cES_Nombre != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_Nombre' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_Nombre = value;
                    OnPropertyChanged("CES_Nombre");
                }
            }
        }
        private string _cES_Nombre;
    
        [DataMember]
        public string CES_Telefono1
        {
            get { return _cES_Telefono1; }
            set
            {
                if (_cES_Telefono1 != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_Telefono1' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_Telefono1 = value;
                    OnPropertyChanged("CES_Telefono1");
                }
            }
        }
        private string _cES_Telefono1;
    
        [DataMember]
        public string CES_Direccion
        {
            get { return _cES_Direccion; }
            set
            {
                if (_cES_Direccion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_Direccion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_Direccion = value;
                    OnPropertyChanged("CES_Direccion");
                }
            }
        }
        private string _cES_Direccion;
    
        [DataMember]
        public string CES_IdCentroCostos
        {
            get { return _cES_IdCentroCostos; }
            set
            {
                if (_cES_IdCentroCostos != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_IdCentroCostos' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_IdCentroCostos = value;
                    OnPropertyChanged("CES_IdCentroCostos");
                }
            }
        }
        private string _cES_IdCentroCostos;
    
        [DataMember]
        public string CES_CodigoBodega
        {
            get { return _cES_CodigoBodega; }
            set
            {
                if (_cES_CodigoBodega != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_CodigoBodega' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_CodigoBodega = value;
                    OnPropertyChanged("CES_CodigoBodega");
                }
            }
        }
        private string _cES_CodigoBodega;
    
        [DataMember]
        public short CES_IdClasificadorCanalVenta
        {
            get { return _cES_IdClasificadorCanalVenta; }
            set
            {
                if (_cES_IdClasificadorCanalVenta != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CES_IdClasificadorCanalVenta' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cES_IdClasificadorCanalVenta = value;
                    OnPropertyChanged("CES_IdClasificadorCanalVenta");
                }
            }
        }
        private short _cES_IdClasificadorCanalVenta;
    
        [DataMember]
        public string SUC_IdBodega
        {
            get { return _sUC_IdBodega; }
            set
            {
                if (_sUC_IdBodega != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_IdBodega' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_IdBodega = value;
                    OnPropertyChanged("SUC_IdBodega");
                }
            }
        }
        private string _sUC_IdBodega;
    
        [DataMember]
        public System.DateTime SUC_FechaGrabacion
        {
            get { return _sUC_FechaGrabacion; }
            set
            {
                if (_sUC_FechaGrabacion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SUC_FechaGrabacion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sUC_FechaGrabacion = value;
                    OnPropertyChanged("SUC_FechaGrabacion");
                }
            }
        }
        private System.DateTime _sUC_FechaGrabacion;
    
        [DataMember]
        public string LOC_IdLocalidad
        {
            get { return _lOC_IdLocalidad; }
            set
            {
                if (_lOC_IdLocalidad != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LOC_IdLocalidad' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lOC_IdLocalidad = value;
                    OnPropertyChanged("LOC_IdLocalidad");
                }
            }
        }
        private string _lOC_IdLocalidad;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
