//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.Facturacion.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoProgramado_FAC
    {
        public ConceptoProgramado_FAC()
        {
            this.ImpConceptoProgramado_FAC = new HashSet<ImpConceptoProgramado_FAC>();
        }
    
        public int COP_IdConceptoProg { get; set; }
        public long COP_IdProgramacion { get; set; }
        public int COP_IdServicio { get; set; }
        public int COP_IdSucursal { get; set; }
        public string COP_DescripcionSucursal { get; set; }
        public int COP_Cantidad { get; set; }
        public string COP_DescripcionConcepto { get; set; }
        public decimal COP_ValorUnitario { get; set; }
        public decimal COP_TotalNeto { get; set; }
        public decimal COP_TotalImpuestos { get; set; }
        public decimal COP_Total { get; set; }
        public System.DateTime COP_FechaGrabacion { get; set; }
        public string COP_CreadoPor { get; set; }
    
        public virtual ICollection<ImpConceptoProgramado_FAC> ImpConceptoProgramado_FAC { get; set; }
        public virtual ProgramacionFactura_FAC ProgramacionFactura_FAC { get; set; }
    }
}
