//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.OperacionNacional.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(IngresoOperativoAgenciGuia_OPN))]
    [KnownType(typeof(NovedadesEnviosSueltos_OPU))]
    public partial class IngresoOpeAgeGuiaNovedades_OPN: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public long IOG_IdIngresoOperaAgenciaGuia
        {
            get { return _iOG_IdIngresoOperaAgenciaGuia; }
            set
            {
                if (_iOG_IdIngresoOperaAgenciaGuia != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'IOG_IdIngresoOperaAgenciaGuia' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (IngresoOperativoAgenciGuia_OPN != null && IngresoOperativoAgenciGuia_OPN.IOG_IdIngresoOperaAgenciaGuia != value)
                        {
                            IngresoOperativoAgenciGuia_OPN = null;
                        }
                    }
                    _iOG_IdIngresoOperaAgenciaGuia = value;
                    OnPropertyChanged("IOG_IdIngresoOperaAgenciaGuia");
                }
            }
        }
        private long _iOG_IdIngresoOperaAgenciaGuia;
    
        [DataMember]
        public short IOG_IdNovedad
        {
            get { return _iOG_IdNovedad; }
            set
            {
                if (_iOG_IdNovedad != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'IOG_IdNovedad' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (NovedadesEnviosSueltos_OPU != null && NovedadesEnviosSueltos_OPU.NES_IdNovedad != value)
                        {
                            NovedadesEnviosSueltos_OPU = null;
                        }
                    }
                    _iOG_IdNovedad = value;
                    OnPropertyChanged("IOG_IdNovedad");
                }
            }
        }
        private short _iOG_IdNovedad;
    
        [DataMember]
        public System.DateTime IOG_FechaGrabacion
        {
            get { return _iOG_FechaGrabacion; }
            set
            {
                if (_iOG_FechaGrabacion != value)
                {
                    _iOG_FechaGrabacion = value;
                    OnPropertyChanged("IOG_FechaGrabacion");
                }
            }
        }
        private System.DateTime _iOG_FechaGrabacion;
    
        [DataMember]
        public string IOG_CreadoPor
        {
            get { return _iOG_CreadoPor; }
            set
            {
                if (_iOG_CreadoPor != value)
                {
                    _iOG_CreadoPor = value;
                    OnPropertyChanged("IOG_CreadoPor");
                }
            }
        }
        private string _iOG_CreadoPor;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public IngresoOperativoAgenciGuia_OPN IngresoOperativoAgenciGuia_OPN
        {
            get { return _ingresoOperativoAgenciGuia_OPN; }
            set
            {
                if (!ReferenceEquals(_ingresoOperativoAgenciGuia_OPN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (IOG_IdIngresoOperaAgenciaGuia != value.IOG_IdIngresoOperaAgenciaGuia)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _ingresoOperativoAgenciGuia_OPN;
                    _ingresoOperativoAgenciGuia_OPN = value;
                    FixupIngresoOperativoAgenciGuia_OPN(previousValue);
                    OnNavigationPropertyChanged("IngresoOperativoAgenciGuia_OPN");
                }
            }
        }
        private IngresoOperativoAgenciGuia_OPN _ingresoOperativoAgenciGuia_OPN;
    
        [DataMember]
        public NovedadesEnviosSueltos_OPU NovedadesEnviosSueltos_OPU
        {
            get { return _novedadesEnviosSueltos_OPU; }
            set
            {
                if (!ReferenceEquals(_novedadesEnviosSueltos_OPU, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (IOG_IdNovedad != value.NES_IdNovedad)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _novedadesEnviosSueltos_OPU;
                    _novedadesEnviosSueltos_OPU = value;
                    FixupNovedadesEnviosSueltos_OPU(previousValue);
                    OnNavigationPropertyChanged("NovedadesEnviosSueltos_OPU");
                }
            }
        }
        private NovedadesEnviosSueltos_OPU _novedadesEnviosSueltos_OPU;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // Este tipo de entidad es el extremo dependiente en al menos una asociación que realiza eliminaciones en cascada.
        // Este controlador de eventos procesará notificaciones que tienen lugar cuando se elimina el extremo principal.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            IngresoOperativoAgenciGuia_OPN = null;
            NovedadesEnviosSueltos_OPU = null;
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupIngresoOperativoAgenciGuia_OPN(IngresoOperativoAgenciGuia_OPN previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.IngresoOpeAgeGuiaNovedades_OPN.Contains(this))
            {
                previousValue.IngresoOpeAgeGuiaNovedades_OPN.Remove(this);
            }
    
            if (IngresoOperativoAgenciGuia_OPN != null)
            {
                if (!IngresoOperativoAgenciGuia_OPN.IngresoOpeAgeGuiaNovedades_OPN.Contains(this))
                {
                    IngresoOperativoAgenciGuia_OPN.IngresoOpeAgeGuiaNovedades_OPN.Add(this);
                }
    
                IOG_IdIngresoOperaAgenciaGuia = IngresoOperativoAgenciGuia_OPN.IOG_IdIngresoOperaAgenciaGuia;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("IngresoOperativoAgenciGuia_OPN")
                    && (ChangeTracker.OriginalValues["IngresoOperativoAgenciGuia_OPN"] == IngresoOperativoAgenciGuia_OPN))
                {
                    ChangeTracker.OriginalValues.Remove("IngresoOperativoAgenciGuia_OPN");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("IngresoOperativoAgenciGuia_OPN", previousValue);
                }
                if (IngresoOperativoAgenciGuia_OPN != null && !IngresoOperativoAgenciGuia_OPN.ChangeTracker.ChangeTrackingEnabled)
                {
                    IngresoOperativoAgenciGuia_OPN.StartTracking();
                }
            }
        }
    
        private void FixupNovedadesEnviosSueltos_OPU(NovedadesEnviosSueltos_OPU previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.IngresoOpeAgeGuiaNovedades_OPN.Contains(this))
            {
                previousValue.IngresoOpeAgeGuiaNovedades_OPN.Remove(this);
            }
    
            if (NovedadesEnviosSueltos_OPU != null)
            {
                if (!NovedadesEnviosSueltos_OPU.IngresoOpeAgeGuiaNovedades_OPN.Contains(this))
                {
                    NovedadesEnviosSueltos_OPU.IngresoOpeAgeGuiaNovedades_OPN.Add(this);
                }
    
                IOG_IdNovedad = NovedadesEnviosSueltos_OPU.NES_IdNovedad;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("NovedadesEnviosSueltos_OPU")
                    && (ChangeTracker.OriginalValues["NovedadesEnviosSueltos_OPU"] == NovedadesEnviosSueltos_OPU))
                {
                    ChangeTracker.OriginalValues.Remove("NovedadesEnviosSueltos_OPU");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("NovedadesEnviosSueltos_OPU", previousValue);
                }
                if (NovedadesEnviosSueltos_OPU != null && !NovedadesEnviosSueltos_OPU.ChangeTracker.ChangeTrackingEnabled)
                {
                    NovedadesEnviosSueltos_OPU.StartTracking();
                }
            }
        }

        #endregion

    }
}
