using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CO.Servidor.Raps.Comun
{
    public enum EnumMotivoGuiaRaps
    {
        FALSO_MOTIVO_DEVOLUCION = 27,
        A_PETICION_DEL_REMITENTE = 142,
        ACCIDENTE = 117,
        AVERIADO = 131,
        BLOQUEO_DE_CALLES_CRUDO_INVIERNO_MANIFESTACION_ORDEN_PUBLICO = 118,
        CAMBIAR_NUEVA_DIRECCION_DE_ENTREGA = 136,
        CAMBIO_DE_DOMICILIO = 124,
        CONTENIDO_INCOMPLETO_HURTO = 132,
        DESTINATARIO_DESCONOCIDO = 129,
        DIRECCION_INCOMPLETA = 126,
        DIRECCION_NO_EXISTE = 127,
        ENVIO_CRUZADO_TROCADO = 140,
        FALLECIDO = 125,
        FUERA_DE_ZONA = 116,
        HUELGA = 119,
        HURTO = 139,
        INCAUTADO = 138,
        INMUEBLE_DESHABITADO = 123,
        NO_CORRESPONDE_LA_CIUDAD_DESTINO = 128,
        NO_PAGARON_EL_ALCOBRO = 133,
        NO_PAGARON_PRODUCTO_CONTRAPAGO = 134,
        RESIDENTE_AUSENTE = 121,
        RESIDENTE_AUSENTE_NO_ALCANZO_EL_MENSAJERO = 122,
        SE_NEGO_A_RECIBIR = 130,
        VACACIONES = 120,

        /// MOTIVOS DE AGENCIA
        /// 

        ACCIDENTE_AGE = 33,
        AVERIADO_AGE = 34,
        CAMBIO_DE_DOMICILIO_AGE = 35,
        DESTINATARIO_DESCONOCIDO_AGE = 36,
        DIRECCION_INCOMPLETA_AGE = 37,
        DIRECCION_NO_EXISTE_AGE = 38,
        DEV_EN_VACACIONES_AGE = 39,
        INMUEBLE_DESHABITADO_AGE = 40,
        SE_NEGO_A_RECIBIR_AGE = 41,
        PAGARON_EL_ALCOBRO_AGE = 42,
        FALLECIDO_AGE = 43,
        HUELGA_AGE = 44,
        TROCADO_AGE = 45,
        PETICION_DEL_REMITENTE_AGE = 46,
        HURTO_AGE = 47,
        INCAUTADO_AGE = 48,
        NO_RECLAMO_EN_OFICINA_AGE = 49,
        RESIDENTE_AUSENTE_2_AVISO_AGE = 50,
        CONTENIDO_INCOMPLETO_AGE = 51,
        AD_DE_PAGO_AL_COBRO_AGE = 56,
        RESIDENTE_AUSENTE_1_AVISO_AGE = 58,


    }
}
