//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Solicitudes.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(EstadosGiro_GIR))]
    [KnownType(typeof(GirosPeatonPeaton_GIR))]
    [KnownType(typeof(SolicitudGiro_GIR))]
    public partial class AdmisionGiros_GIR: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long ADG_IdAdmisionGiro
        {
            get { return _aDG_IdAdmisionGiro; }
            set
            {
                if (_aDG_IdAdmisionGiro != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ADG_IdAdmisionGiro' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _aDG_IdAdmisionGiro = value;
                    OnPropertyChanged("ADG_IdAdmisionGiro");
                }
            }
        }
        private long _aDG_IdAdmisionGiro;
    
        [DataMember]
        public string ADG_PrefijoIdGiro
        {
            get { return _aDG_PrefijoIdGiro; }
            set
            {
                if (_aDG_PrefijoIdGiro != value)
                {
                    _aDG_PrefijoIdGiro = value;
                    OnPropertyChanged("ADG_PrefijoIdGiro");
                }
            }
        }
        private string _aDG_PrefijoIdGiro;
    
        [DataMember]
        public long ADG_IdGiro
        {
            get { return _aDG_IdGiro; }
            set
            {
                if (_aDG_IdGiro != value)
                {
                    _aDG_IdGiro = value;
                    OnPropertyChanged("ADG_IdGiro");
                }
            }
        }
        private long _aDG_IdGiro;
    
        [DataMember]
        public string ADG_DigitoVerificacion
        {
            get { return _aDG_DigitoVerificacion; }
            set
            {
                if (_aDG_DigitoVerificacion != value)
                {
                    _aDG_DigitoVerificacion = value;
                    OnPropertyChanged("ADG_DigitoVerificacion");
                }
            }
        }
        private string _aDG_DigitoVerificacion;
    
        [DataMember]
        public string ADG_GuidDeChequeo
        {
            get { return _aDG_GuidDeChequeo; }
            set
            {
                if (_aDG_GuidDeChequeo != value)
                {
                    _aDG_GuidDeChequeo = value;
                    OnPropertyChanged("ADG_GuidDeChequeo");
                }
            }
        }
        private string _aDG_GuidDeChequeo;
    
        [DataMember]
        public bool ADG_AdmisionAutomatica
        {
            get { return _aDG_AdmisionAutomatica; }
            set
            {
                if (_aDG_AdmisionAutomatica != value)
                {
                    _aDG_AdmisionAutomatica = value;
                    OnPropertyChanged("ADG_AdmisionAutomatica");
                }
            }
        }
        private bool _aDG_AdmisionAutomatica;
    
        [DataMember]
        public string ADG_IdTipoGiro
        {
            get { return _aDG_IdTipoGiro; }
            set
            {
                if (_aDG_IdTipoGiro != value)
                {
                    _aDG_IdTipoGiro = value;
                    OnPropertyChanged("ADG_IdTipoGiro");
                }
            }
        }
        private string _aDG_IdTipoGiro;
    
        [DataMember]
        public long ADG_IdCentroServicioOrigen
        {
            get { return _aDG_IdCentroServicioOrigen; }
            set
            {
                if (_aDG_IdCentroServicioOrigen != value)
                {
                    _aDG_IdCentroServicioOrigen = value;
                    OnPropertyChanged("ADG_IdCentroServicioOrigen");
                }
            }
        }
        private long _aDG_IdCentroServicioOrigen;
    
        [DataMember]
        public string ADG_NombreCentroServicioOrigen
        {
            get { return _aDG_NombreCentroServicioOrigen; }
            set
            {
                if (_aDG_NombreCentroServicioOrigen != value)
                {
                    _aDG_NombreCentroServicioOrigen = value;
                    OnPropertyChanged("ADG_NombreCentroServicioOrigen");
                }
            }
        }
        private string _aDG_NombreCentroServicioOrigen;
    
        [DataMember]
        public string ADG_IdPaisOrigen
        {
            get { return _aDG_IdPaisOrigen; }
            set
            {
                if (_aDG_IdPaisOrigen != value)
                {
                    _aDG_IdPaisOrigen = value;
                    OnPropertyChanged("ADG_IdPaisOrigen");
                }
            }
        }
        private string _aDG_IdPaisOrigen;
    
        [DataMember]
        public string ADG_DescPaisOrigen
        {
            get { return _aDG_DescPaisOrigen; }
            set
            {
                if (_aDG_DescPaisOrigen != value)
                {
                    _aDG_DescPaisOrigen = value;
                    OnPropertyChanged("ADG_DescPaisOrigen");
                }
            }
        }
        private string _aDG_DescPaisOrigen;
    
        [DataMember]
        public string ADG_IdCiudadOrigen
        {
            get { return _aDG_IdCiudadOrigen; }
            set
            {
                if (_aDG_IdCiudadOrigen != value)
                {
                    _aDG_IdCiudadOrigen = value;
                    OnPropertyChanged("ADG_IdCiudadOrigen");
                }
            }
        }
        private string _aDG_IdCiudadOrigen;
    
        [DataMember]
        public string ADG_DescCiudadOrigen
        {
            get { return _aDG_DescCiudadOrigen; }
            set
            {
                if (_aDG_DescCiudadOrigen != value)
                {
                    _aDG_DescCiudadOrigen = value;
                    OnPropertyChanged("ADG_DescCiudadOrigen");
                }
            }
        }
        private string _aDG_DescCiudadOrigen;
    
        [DataMember]
        public string ADG_CodigoPostalOrigen
        {
            get { return _aDG_CodigoPostalOrigen; }
            set
            {
                if (_aDG_CodigoPostalOrigen != value)
                {
                    _aDG_CodigoPostalOrigen = value;
                    OnPropertyChanged("ADG_CodigoPostalOrigen");
                }
            }
        }
        private string _aDG_CodigoPostalOrigen;
    
        [DataMember]
        public long ADG_IdCentroServicioDestino
        {
            get { return _aDG_IdCentroServicioDestino; }
            set
            {
                if (_aDG_IdCentroServicioDestino != value)
                {
                    _aDG_IdCentroServicioDestino = value;
                    OnPropertyChanged("ADG_IdCentroServicioDestino");
                }
            }
        }
        private long _aDG_IdCentroServicioDestino;
    
        [DataMember]
        public string ADG_NombreCentroServicioDestino
        {
            get { return _aDG_NombreCentroServicioDestino; }
            set
            {
                if (_aDG_NombreCentroServicioDestino != value)
                {
                    _aDG_NombreCentroServicioDestino = value;
                    OnPropertyChanged("ADG_NombreCentroServicioDestino");
                }
            }
        }
        private string _aDG_NombreCentroServicioDestino;
    
        [DataMember]
        public string ADG_IdPaisDestino
        {
            get { return _aDG_IdPaisDestino; }
            set
            {
                if (_aDG_IdPaisDestino != value)
                {
                    _aDG_IdPaisDestino = value;
                    OnPropertyChanged("ADG_IdPaisDestino");
                }
            }
        }
        private string _aDG_IdPaisDestino;
    
        [DataMember]
        public string ADG_DescPaisDestino
        {
            get { return _aDG_DescPaisDestino; }
            set
            {
                if (_aDG_DescPaisDestino != value)
                {
                    _aDG_DescPaisDestino = value;
                    OnPropertyChanged("ADG_DescPaisDestino");
                }
            }
        }
        private string _aDG_DescPaisDestino;
    
        [DataMember]
        public string ADG_IdCiudadDestino
        {
            get { return _aDG_IdCiudadDestino; }
            set
            {
                if (_aDG_IdCiudadDestino != value)
                {
                    _aDG_IdCiudadDestino = value;
                    OnPropertyChanged("ADG_IdCiudadDestino");
                }
            }
        }
        private string _aDG_IdCiudadDestino;
    
        [DataMember]
        public string ADG_DescCiudadDestino
        {
            get { return _aDG_DescCiudadDestino; }
            set
            {
                if (_aDG_DescCiudadDestino != value)
                {
                    _aDG_DescCiudadDestino = value;
                    OnPropertyChanged("ADG_DescCiudadDestino");
                }
            }
        }
        private string _aDG_DescCiudadDestino;
    
        [DataMember]
        public string ADG_CodigoPostalDestino
        {
            get { return _aDG_CodigoPostalDestino; }
            set
            {
                if (_aDG_CodigoPostalDestino != value)
                {
                    _aDG_CodigoPostalDestino = value;
                    OnPropertyChanged("ADG_CodigoPostalDestino");
                }
            }
        }
        private string _aDG_CodigoPostalDestino;
    
        [DataMember]
        public decimal ADG_ValorGiro
        {
            get { return _aDG_ValorGiro; }
            set
            {
                if (_aDG_ValorGiro != value)
                {
                    _aDG_ValorGiro = value;
                    OnPropertyChanged("ADG_ValorGiro");
                }
            }
        }
        private decimal _aDG_ValorGiro;
    
        [DataMember]
        public decimal ADG_TarifaPorcPorte
        {
            get { return _aDG_TarifaPorcPorte; }
            set
            {
                if (_aDG_TarifaPorcPorte != value)
                {
                    _aDG_TarifaPorcPorte = value;
                    OnPropertyChanged("ADG_TarifaPorcPorte");
                }
            }
        }
        private decimal _aDG_TarifaPorcPorte;
    
        [DataMember]
        public decimal ADG_TarifaFijaPorte
        {
            get { return _aDG_TarifaFijaPorte; }
            set
            {
                if (_aDG_TarifaFijaPorte != value)
                {
                    _aDG_TarifaFijaPorte = value;
                    OnPropertyChanged("ADG_TarifaFijaPorte");
                }
            }
        }
        private decimal _aDG_TarifaFijaPorte;
    
        [DataMember]
        public decimal ADG_ValorPorte
        {
            get { return _aDG_ValorPorte; }
            set
            {
                if (_aDG_ValorPorte != value)
                {
                    _aDG_ValorPorte = value;
                    OnPropertyChanged("ADG_ValorPorte");
                }
            }
        }
        private decimal _aDG_ValorPorte;
    
        [DataMember]
        public decimal ADG_ValorAdicionales
        {
            get { return _aDG_ValorAdicionales; }
            set
            {
                if (_aDG_ValorAdicionales != value)
                {
                    _aDG_ValorAdicionales = value;
                    OnPropertyChanged("ADG_ValorAdicionales");
                }
            }
        }
        private decimal _aDG_ValorAdicionales;
    
        [DataMember]
        public decimal ADG_ValorImpuestos
        {
            get { return _aDG_ValorImpuestos; }
            set
            {
                if (_aDG_ValorImpuestos != value)
                {
                    _aDG_ValorImpuestos = value;
                    OnPropertyChanged("ADG_ValorImpuestos");
                }
            }
        }
        private decimal _aDG_ValorImpuestos;
    
        [DataMember]
        public decimal ADG_ValorTotal
        {
            get { return _aDG_ValorTotal; }
            set
            {
                if (_aDG_ValorTotal != value)
                {
                    _aDG_ValorTotal = value;
                    OnPropertyChanged("ADG_ValorTotal");
                }
            }
        }
        private decimal _aDG_ValorTotal;
    
        [DataMember]
        public Nullable<long> ADG_DeclaracionVoluntariaOrigenes
        {
            get { return _aDG_DeclaracionVoluntariaOrigenes; }
            set
            {
                if (_aDG_DeclaracionVoluntariaOrigenes != value)
                {
                    _aDG_DeclaracionVoluntariaOrigenes = value;
                    OnPropertyChanged("ADG_DeclaracionVoluntariaOrigenes");
                }
            }
        }
        private Nullable<long> _aDG_DeclaracionVoluntariaOrigenes;
    
        [DataMember]
        public string ADG_Observaciones
        {
            get { return _aDG_Observaciones; }
            set
            {
                if (_aDG_Observaciones != value)
                {
                    _aDG_Observaciones = value;
                    OnPropertyChanged("ADG_Observaciones");
                }
            }
        }
        private string _aDG_Observaciones;
    
        [DataMember]
        public string ADG_IdTipoIdentificacionRemitente
        {
            get { return _aDG_IdTipoIdentificacionRemitente; }
            set
            {
                if (_aDG_IdTipoIdentificacionRemitente != value)
                {
                    _aDG_IdTipoIdentificacionRemitente = value;
                    OnPropertyChanged("ADG_IdTipoIdentificacionRemitente");
                }
            }
        }
        private string _aDG_IdTipoIdentificacionRemitente;
    
        [DataMember]
        public string ADG_IdRemitente
        {
            get { return _aDG_IdRemitente; }
            set
            {
                if (_aDG_IdRemitente != value)
                {
                    _aDG_IdRemitente = value;
                    OnPropertyChanged("ADG_IdRemitente");
                }
            }
        }
        private string _aDG_IdRemitente;
    
        [DataMember]
        public string ADG_NombreRemitente
        {
            get { return _aDG_NombreRemitente; }
            set
            {
                if (_aDG_NombreRemitente != value)
                {
                    _aDG_NombreRemitente = value;
                    OnPropertyChanged("ADG_NombreRemitente");
                }
            }
        }
        private string _aDG_NombreRemitente;
    
        [DataMember]
        public string ADG_IdTipoIdentificacionDestinatario
        {
            get { return _aDG_IdTipoIdentificacionDestinatario; }
            set
            {
                if (_aDG_IdTipoIdentificacionDestinatario != value)
                {
                    _aDG_IdTipoIdentificacionDestinatario = value;
                    OnPropertyChanged("ADG_IdTipoIdentificacionDestinatario");
                }
            }
        }
        private string _aDG_IdTipoIdentificacionDestinatario;
    
        [DataMember]
        public string ADG_IdDestinatario
        {
            get { return _aDG_IdDestinatario; }
            set
            {
                if (_aDG_IdDestinatario != value)
                {
                    _aDG_IdDestinatario = value;
                    OnPropertyChanged("ADG_IdDestinatario");
                }
            }
        }
        private string _aDG_IdDestinatario;
    
        [DataMember]
        public string ADG_NombreDestinatario
        {
            get { return _aDG_NombreDestinatario; }
            set
            {
                if (_aDG_NombreDestinatario != value)
                {
                    _aDG_NombreDestinatario = value;
                    OnPropertyChanged("ADG_NombreDestinatario");
                }
            }
        }
        private string _aDG_NombreDestinatario;
    
        [DataMember]
        public bool ADG_Transmitido
        {
            get { return _aDG_Transmitido; }
            set
            {
                if (_aDG_Transmitido != value)
                {
                    _aDG_Transmitido = value;
                    OnPropertyChanged("ADG_Transmitido");
                }
            }
        }
        private bool _aDG_Transmitido;
    
        [DataMember]
        public System.DateTime ADG_FechaGrabacion
        {
            get { return _aDG_FechaGrabacion; }
            set
            {
                if (_aDG_FechaGrabacion != value)
                {
                    _aDG_FechaGrabacion = value;
                    OnPropertyChanged("ADG_FechaGrabacion");
                }
            }
        }
        private System.DateTime _aDG_FechaGrabacion;
    
        [DataMember]
        public string ADG_CreadoPor
        {
            get { return _aDG_CreadoPor; }
            set
            {
                if (_aDG_CreadoPor != value)
                {
                    _aDG_CreadoPor = value;
                    OnPropertyChanged("ADG_CreadoPor");
                }
            }
        }
        private string _aDG_CreadoPor;
    
        [DataMember]
        public Nullable<bool> ADG_NotificarPagoPorEmail
        {
            get { return _aDG_NotificarPagoPorEmail; }
            set
            {
                if (_aDG_NotificarPagoPorEmail != value)
                {
                    _aDG_NotificarPagoPorEmail = value;
                    OnPropertyChanged("ADG_NotificarPagoPorEmail");
                }
            }
        }
        private Nullable<bool> _aDG_NotificarPagoPorEmail;
    
        [DataMember]
        public bool ADG_EstaPagado
        {
            get { return _aDG_EstaPagado; }
            set
            {
                if (_aDG_EstaPagado != value)
                {
                    _aDG_EstaPagado = value;
                    OnPropertyChanged("ADG_EstaPagado");
                }
            }
        }
        private bool _aDG_EstaPagado;
    
        [DataMember]
        public string ADG_TelefonoRemitente
        {
            get { return _aDG_TelefonoRemitente; }
            set
            {
                if (_aDG_TelefonoRemitente != value)
                {
                    _aDG_TelefonoRemitente = value;
                    OnPropertyChanged("ADG_TelefonoRemitente");
                }
            }
        }
        private string _aDG_TelefonoRemitente;
    
        [DataMember]
        public string ADG_TelefonoDestinatario
        {
            get { return _aDG_TelefonoDestinatario; }
            set
            {
                if (_aDG_TelefonoDestinatario != value)
                {
                    _aDG_TelefonoDestinatario = value;
                    OnPropertyChanged("ADG_TelefonoDestinatario");
                }
            }
        }
        private string _aDG_TelefonoDestinatario;
    
        [DataMember]
        public string ADG_DireccionRemitente
        {
            get { return _aDG_DireccionRemitente; }
            set
            {
                if (_aDG_DireccionRemitente != value)
                {
                    _aDG_DireccionRemitente = value;
                    OnPropertyChanged("ADG_DireccionRemitente");
                }
            }
        }
        private string _aDG_DireccionRemitente;
    
        [DataMember]
        public string ADG_DireccionDestinatario
        {
            get { return _aDG_DireccionDestinatario; }
            set
            {
                if (_aDG_DireccionDestinatario != value)
                {
                    _aDG_DireccionDestinatario = value;
                    OnPropertyChanged("ADG_DireccionDestinatario");
                }
            }
        }
        private string _aDG_DireccionDestinatario;
    
        [DataMember]
        public string ADG_EmailRemitente
        {
            get { return _aDG_EmailRemitente; }
            set
            {
                if (_aDG_EmailRemitente != value)
                {
                    _aDG_EmailRemitente = value;
                    OnPropertyChanged("ADG_EmailRemitente");
                }
            }
        }
        private string _aDG_EmailRemitente;
    
        [DataMember]
        public string ADG_EmailDestinatario
        {
            get { return _aDG_EmailDestinatario; }
            set
            {
                if (_aDG_EmailDestinatario != value)
                {
                    _aDG_EmailDestinatario = value;
                    OnPropertyChanged("ADG_EmailDestinatario");
                }
            }
        }
        private string _aDG_EmailDestinatario;
    
        [DataMember]
        public bool ADG_TieneTelemercadeo
        {
            get { return _aDG_TieneTelemercadeo; }
            set
            {
                if (_aDG_TieneTelemercadeo != value)
                {
                    _aDG_TieneTelemercadeo = value;
                    OnPropertyChanged("ADG_TieneTelemercadeo");
                }
            }
        }
        private bool _aDG_TieneTelemercadeo;
    
        [DataMember]
        public long ADG_IdEstadosGiro
        {
            get { return _aDG_IdEstadosGiro; }
            set
            {
                if (_aDG_IdEstadosGiro != value)
                {
                    _aDG_IdEstadosGiro = value;
                    OnPropertyChanged("ADG_IdEstadosGiro");
                }
            }
        }
        private long _aDG_IdEstadosGiro;
    
        [DataMember]
        public bool ADG_EsProduccion
        {
            get { return _aDG_EsProduccion; }
            set
            {
                if (_aDG_EsProduccion != value)
                {
                    _aDG_EsProduccion = value;
                    OnPropertyChanged("ADG_EsProduccion");
                }
            }
        }
        private bool _aDG_EsProduccion;
    
        [DataMember]
        public string ADG_ObservacionesSolicitudes
        {
            get { return _aDG_ObservacionesSolicitudes; }
            set
            {
                if (_aDG_ObservacionesSolicitudes != value)
                {
                    _aDG_ObservacionesSolicitudes = value;
                    OnPropertyChanged("ADG_ObservacionesSolicitudes");
                }
            }
        }
        private string _aDG_ObservacionesSolicitudes;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<EstadosGiro_GIR> EstadosGiro_GIR
        {
            get
            {
                if (_estadosGiro_GIR == null)
                {
                    _estadosGiro_GIR = new TrackableCollection<EstadosGiro_GIR>();
                    _estadosGiro_GIR.CollectionChanged += FixupEstadosGiro_GIR;
                }
                return _estadosGiro_GIR;
            }
            set
            {
                if (!ReferenceEquals(_estadosGiro_GIR, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_estadosGiro_GIR != null)
                    {
                        _estadosGiro_GIR.CollectionChanged -= FixupEstadosGiro_GIR;
                    }
                    _estadosGiro_GIR = value;
                    if (_estadosGiro_GIR != null)
                    {
                        _estadosGiro_GIR.CollectionChanged += FixupEstadosGiro_GIR;
                    }
                    OnNavigationPropertyChanged("EstadosGiro_GIR");
                }
            }
        }
        private TrackableCollection<EstadosGiro_GIR> _estadosGiro_GIR;
    
        [DataMember]
        public GirosPeatonPeaton_GIR GirosPeatonPeaton_GIR
        {
            get { return _girosPeatonPeaton_GIR; }
            set
            {
                if (!ReferenceEquals(_girosPeatonPeaton_GIR, value))
                {
                    var previousValue = _girosPeatonPeaton_GIR;
                    _girosPeatonPeaton_GIR = value;
                    FixupGirosPeatonPeaton_GIR(previousValue);
                    OnNavigationPropertyChanged("GirosPeatonPeaton_GIR");
                }
            }
        }
        private GirosPeatonPeaton_GIR _girosPeatonPeaton_GIR;
    
        [DataMember]
        public TrackableCollection<SolicitudGiro_GIR> SolicitudGiro_GIR
        {
            get
            {
                if (_solicitudGiro_GIR == null)
                {
                    _solicitudGiro_GIR = new TrackableCollection<SolicitudGiro_GIR>();
                    _solicitudGiro_GIR.CollectionChanged += FixupSolicitudGiro_GIR;
                }
                return _solicitudGiro_GIR;
            }
            set
            {
                if (!ReferenceEquals(_solicitudGiro_GIR, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_solicitudGiro_GIR != null)
                    {
                        _solicitudGiro_GIR.CollectionChanged -= FixupSolicitudGiro_GIR;
                    }
                    _solicitudGiro_GIR = value;
                    if (_solicitudGiro_GIR != null)
                    {
                        _solicitudGiro_GIR.CollectionChanged += FixupSolicitudGiro_GIR;
                    }
                    OnNavigationPropertyChanged("SolicitudGiro_GIR");
                }
            }
        }
        private TrackableCollection<SolicitudGiro_GIR> _solicitudGiro_GIR;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            EstadosGiro_GIR.Clear();
            GirosPeatonPeaton_GIR = null;
            SolicitudGiro_GIR.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupGirosPeatonPeaton_GIR(GirosPeatonPeaton_GIR previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (GirosPeatonPeaton_GIR != null)
            {
                ChangeTracker.ObjectStateChanging += GirosPeatonPeaton_GIR.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.AdmisionGiros_GIR, this))
            {
                previousValue.AdmisionGiros_GIR = null;
            }
    
            if (GirosPeatonPeaton_GIR != null)
            {
                GirosPeatonPeaton_GIR.AdmisionGiros_GIR = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("GirosPeatonPeaton_GIR")
                    && (ChangeTracker.OriginalValues["GirosPeatonPeaton_GIR"] == GirosPeatonPeaton_GIR))
                {
                    ChangeTracker.OriginalValues.Remove("GirosPeatonPeaton_GIR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("GirosPeatonPeaton_GIR", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (GirosPeatonPeaton_GIR != null && !GirosPeatonPeaton_GIR.ChangeTracker.ChangeTrackingEnabled)
                {
                    GirosPeatonPeaton_GIR.StartTracking();
                }
            }
        }
    
        private void FixupEstadosGiro_GIR(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (EstadosGiro_GIR item in e.NewItems)
                {
                    item.AdmisionGiros_GIR = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("EstadosGiro_GIR", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EstadosGiro_GIR item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionGiros_GIR, this))
                    {
                        item.AdmisionGiros_GIR = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("EstadosGiro_GIR", item);
                    }
                }
            }
        }
    
        private void FixupSolicitudGiro_GIR(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SolicitudGiro_GIR item in e.NewItems)
                {
                    item.AdmisionGiros_GIR = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SolicitudGiro_GIR", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SolicitudGiro_GIR item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionGiros_GIR, this))
                    {
                        item.AdmisionGiros_GIR = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SolicitudGiro_GIR", item);
                    }
                }
            }
        }

        #endregion
    }
}
