using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CO.Servidor.Raps.Comun.Integraciones
{
    public enum EnumMotivoGuiaRaps : int
    {
        /// MOTIVOS DE PTO
        FALSO_MOTIVO_DEVOLUCION = 27,
        A_PETICION_DEL_REMITENTE = 142,
        ACCIDENTE = 117,
        AVERIADO = 131,
        BLOQUEO_DE_CALLES_CRUDO_INVIERNO_MANIFESTACION_ORDEN_PUBLICO = 118,
        CAMBIAR_NUEVA_DIRECCION_DE_ENTREGA = 136,
        CAMBIO_DE_DOMICILIO = 124,
        CONTENIDO_INCOMPLETO_HURTO = 132,
        DESTINATARIO_DESCONOCIDO = 129,
        DIRECCION_INCOMPLETA = 126,
        DIRECCION_NO_EXISTE = 127,
        ENVIO_CRUZADO_TROCADO = 140,
        FALLECIDO = 125,
        FUERA_DE_ZONA = 116,
        HUELGA = 119,
        HURTO = 139,
        INCAUTADO = 138,
        INMUEBLE_DESHABITADO = 123,
        NO_CORRESPONDE_LA_CIUDAD_DESTINO = 128,
        NO_PAGARON_EL_ALCOBRO = 133,
        NO_PAGARON_PRODUCTO_CONTRAPAGO = 134,
        RESIDENTE_AUSENTE = 121,
        RESIDENTE_AUSENTE_NO_ALCANZO_EL_MENSAJERO = 122,
        SE_NEGO_A_RECIBIR = 130,
        VACACIONES = 120,

        //MOTIVOS DE AGENCIA

        ACCIDENTE_AGE = 33,
        AVERIADO_AGE = 34,
        CAMBIO_DE_DOMICILIO_AGE = 35,
        DESTINATARIO_DESCONOCIDO_AGE = 36,
        DIRECCION_INCOMPLETA_AGE = 37,
        DIRECCION_NO_EXISTE_AGE = 38,
        DEV_EN_VACACIONES_AGE = 39,
        INMUEBLE_DESHABITADO_AGE = 40,
        SE_NEGO_A_RECIBIR_AGE = 41,
        PAGARON_EL_ALCOBRO_AGE = 42,
        FALLECIDO_AGE = 43,
        HUELGA_AGE = 44,
        TROCADO_AGE = 45,
        PETICION_DEL_REMITENTE_AGE = 46,
        HURTO_AGE = 47,
        INCAUTADO_AGE = 48,
        NO_RECLAMO_EN_OFICINA_AGE = 49,
        RESIDENTE_AUSENTE_2_AVISO_AGE = 50,
        CONTENIDO_INCOMPLETO_AGE = 51,
        AD_DE_PAGO_AL_COBRO_AGE = 56,
        RESIDENTE_AUSENTE_1_AVISO_AGE = 58,


        //MOTIVOS QUE NO EPENDE DE UNA GUIA INICIAN DESDE EL 1000, ESTOS NO SE ENCUENTRAN EN LA TABLA MOTIVOGUIA_MEN

        NO_REALIZO_RECOGIDA_FIJA = 1001,
        NO_TIENE_QR_PUNTO = 1002,
        NO_TIENE_QR_CLIENTE_CRE = 1003,
        NO_REALIZO_RECOGIDA_ESPORADICA_MENSAJERO = 1004,
        NO_REALIZO_RECOGIDA_ESPORADICA_PUNTO = 1005,


        //MOTIVOS QUE DEPENDEN DE UNA GUIA PERO NO ESTAN REGISTRADOS EN LA TABLA DE MOTIVOGUIA_MEN INICIAN DESDE EL 2000

        GUIA_MAL_DILIGENCIADA_DATOS_PERSONALES_AGE = 2001,
        GUIA_MAL_DILIGENCIADA_DATOS_PERSONALES_PTO = 2002,
        GUIA_MAL_DILIGENCIADA_PESO_AGE = 2003,
        GUIA_MAL_DILIGENCIADA_PESO_PTO = 2004,
        GUIA_MAL_DILIGENCIADA_TIPO_SERVICIO_AGE = 2005,
        GUIA_MAL_DILIGENCIADA_TIPO_SERVICIO_PTO = 2006,
        GUIA_ASOCIADA_NN_AGE = 2007,
        GUIA_ASOCIADA_NN_PTO = 2008
    }
}
