//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Framework.Servidor.Seguridad.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MenuRolAccion_SEG))]
    public partial class Accion_SEG: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public string ACC_IdAccion
        {
            get { return _aCC_IdAccion; }
            set
            {
                if (_aCC_IdAccion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ACC_IdAccion' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _aCC_IdAccion = value;
                    OnPropertyChanged("ACC_IdAccion");
                }
            }
        }
        private string _aCC_IdAccion;
    
        [DataMember]
        public string ACC_Descripcion
        {
            get { return _aCC_Descripcion; }
            set
            {
                if (_aCC_Descripcion != value)
                {
                    _aCC_Descripcion = value;
                    OnPropertyChanged("ACC_Descripcion");
                }
            }
        }
        private string _aCC_Descripcion;
    
        [DataMember]
        public System.DateTime ACC_FechaGrabacion
        {
            get { return _aCC_FechaGrabacion; }
            set
            {
                if (_aCC_FechaGrabacion != value)
                {
                    _aCC_FechaGrabacion = value;
                    OnPropertyChanged("ACC_FechaGrabacion");
                }
            }
        }
        private System.DateTime _aCC_FechaGrabacion;
    
        [DataMember]
        public string ACC_CreadoPor
        {
            get { return _aCC_CreadoPor; }
            set
            {
                if (_aCC_CreadoPor != value)
                {
                    _aCC_CreadoPor = value;
                    OnPropertyChanged("ACC_CreadoPor");
                }
            }
        }
        private string _aCC_CreadoPor;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public TrackableCollection<MenuRolAccion_SEG> MenuRolAccion_SEG
        {
            get
            {
                if (_menuRolAccion_SEG == null)
                {
                    _menuRolAccion_SEG = new TrackableCollection<MenuRolAccion_SEG>();
                    _menuRolAccion_SEG.CollectionChanged += FixupMenuRolAccion_SEG;
                }
                return _menuRolAccion_SEG;
            }
            set
            {
                if (!ReferenceEquals(_menuRolAccion_SEG, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_menuRolAccion_SEG != null)
                    {
                        _menuRolAccion_SEG.CollectionChanged -= FixupMenuRolAccion_SEG;
                    }
                    _menuRolAccion_SEG = value;
                    if (_menuRolAccion_SEG != null)
                    {
                        _menuRolAccion_SEG.CollectionChanged += FixupMenuRolAccion_SEG;
                    }
                    OnNavigationPropertyChanged("MenuRolAccion_SEG");
                }
            }
        }
        private TrackableCollection<MenuRolAccion_SEG> _menuRolAccion_SEG;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            MenuRolAccion_SEG.Clear();
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupMenuRolAccion_SEG(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (MenuRolAccion_SEG item in e.NewItems)
                {
                    item.Accion_SEG = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("MenuRolAccion_SEG", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MenuRolAccion_SEG item in e.OldItems)
                {
                    if (ReferenceEquals(item.Accion_SEG, this))
                    {
                        item.Accion_SEG = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("MenuRolAccion_SEG", item);
                    }
                }
            }
        }

        #endregion

    }
}
