//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Framework.Servidor.Seguridad.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PersonaInterna_PAR))]
    [KnownType(typeof(Usuario_SEG))]
    public partial class UsuarioPersonaInterna_SEG: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public long USP_IdCodigoUsuario
        {
            get { return _uSP_IdCodigoUsuario; }
            set
            {
                if (_uSP_IdCodigoUsuario != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'USP_IdCodigoUsuario' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Usuario_SEG != null && Usuario_SEG.USU_IdCodigoUsuario != value)
                        {
                            Usuario_SEG = null;
                        }
                    }
                    _uSP_IdCodigoUsuario = value;
                    OnPropertyChanged("USP_IdCodigoUsuario");
                }
            }
        }
        private long _uSP_IdCodigoUsuario;
    
        [DataMember]
        public long USP_IdPersonaInterna
        {
            get { return _uSP_IdPersonaInterna; }
            set
            {
                if (_uSP_IdPersonaInterna != value)
                {
                    ChangeTracker.RecordOriginalValue("USP_IdPersonaInterna", _uSP_IdPersonaInterna);
                    if (!IsDeserializing)
                    {
                        if (PersonaInterna_PAR != null && PersonaInterna_PAR.PEI_IdPersonaInterna != value)
                        {
                            PersonaInterna_PAR = null;
                        }
                    }
                    _uSP_IdPersonaInterna = value;
                    OnPropertyChanged("USP_IdPersonaInterna");
                }
            }
        }
        private long _uSP_IdPersonaInterna;
    
        [DataMember]
        public System.DateTime USP_FechaGrabacion
        {
            get { return _uSP_FechaGrabacion; }
            set
            {
                if (_uSP_FechaGrabacion != value)
                {
                    _uSP_FechaGrabacion = value;
                    OnPropertyChanged("USP_FechaGrabacion");
                }
            }
        }
        private System.DateTime _uSP_FechaGrabacion;
    
        [DataMember]
        public string USP_CreadoPor
        {
            get { return _uSP_CreadoPor; }
            set
            {
                if (_uSP_CreadoPor != value)
                {
                    _uSP_CreadoPor = value;
                    OnPropertyChanged("USP_CreadoPor");
                }
            }
        }
        private string _uSP_CreadoPor;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public PersonaInterna_PAR PersonaInterna_PAR
        {
            get { return _personaInterna_PAR; }
            set
            {
                if (!ReferenceEquals(_personaInterna_PAR, value))
                {
                    var previousValue = _personaInterna_PAR;
                    _personaInterna_PAR = value;
                    FixupPersonaInterna_PAR(previousValue);
                    OnNavigationPropertyChanged("PersonaInterna_PAR");
                }
            }
        }
        private PersonaInterna_PAR _personaInterna_PAR;
    
        [DataMember]
        public Usuario_SEG Usuario_SEG
        {
            get { return _usuario_SEG; }
            set
            {
                if (!ReferenceEquals(_usuario_SEG, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // Este es el extremo dependiente de una relación de identificación por lo que el extremo principal no se puede cambiar si ya está establecido;
                        // de lo contrario, solo se puede establecer en una entidad con la clave primaria que tenga el mismo valor que la clave externa del extremo dependiente.
                        if (USP_IdCodigoUsuario != value.USU_IdCodigoUsuario)
                        {
                            throw new InvalidOperationException("El extremo principal de una relación de identificación solo se puede modificar cuando el extremo dependiente se encuentra en el estado de agregado.");
                        }
                    }
                    var previousValue = _usuario_SEG;
                    _usuario_SEG = value;
                    FixupUsuario_SEG(previousValue);
                    OnNavigationPropertyChanged("Usuario_SEG");
                }
            }
        }
        private Usuario_SEG _usuario_SEG;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // Este tipo de entidad es el extremo dependiente en al menos una asociación que realiza eliminaciones en cascada.
        // Este controlador de eventos procesará notificaciones que tienen lugar cuando se elimina el extremo principal.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PersonaInterna_PAR = null;
            Usuario_SEG = null;
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupPersonaInterna_PAR(PersonaInterna_PAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.UsuarioPersonaInterna_SEG.Contains(this))
            {
                previousValue.UsuarioPersonaInterna_SEG.Remove(this);
            }
    
            if (PersonaInterna_PAR != null)
            {
                if (!PersonaInterna_PAR.UsuarioPersonaInterna_SEG.Contains(this))
                {
                    PersonaInterna_PAR.UsuarioPersonaInterna_SEG.Add(this);
                }
    
                USP_IdPersonaInterna = PersonaInterna_PAR.PEI_IdPersonaInterna;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PersonaInterna_PAR")
                    && (ChangeTracker.OriginalValues["PersonaInterna_PAR"] == PersonaInterna_PAR))
                {
                    ChangeTracker.OriginalValues.Remove("PersonaInterna_PAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PersonaInterna_PAR", previousValue);
                }
                if (PersonaInterna_PAR != null && !PersonaInterna_PAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    PersonaInterna_PAR.StartTracking();
                }
            }
        }
    
        private void FixupUsuario_SEG(Usuario_SEG previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.UsuarioPersonaInterna_SEG, this))
            {
                previousValue.UsuarioPersonaInterna_SEG = null;
            }
    
            if (Usuario_SEG != null)
            {
                Usuario_SEG.UsuarioPersonaInterna_SEG = this;
                USP_IdCodigoUsuario = Usuario_SEG.USU_IdCodigoUsuario;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Usuario_SEG")
                    && (ChangeTracker.OriginalValues["Usuario_SEG"] == Usuario_SEG))
                {
                    ChangeTracker.OriginalValues.Remove("Usuario_SEG");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Usuario_SEG", previousValue);
                }
                if (Usuario_SEG != null && !Usuario_SEG.ChangeTracker.ChangeTrackingEnabled)
                {
                    Usuario_SEG.StartTracking();
                }
            }
        }

        #endregion

    }
}
