//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Cajas.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class BaseGestionCajas_CAJ: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public short BGC_IdCasaMatriz
        {
            get { return _bGC_IdCasaMatriz; }
            set
            {
                if (_bGC_IdCasaMatriz != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'BGC_IdCasaMatriz' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _bGC_IdCasaMatriz = value;
                    OnPropertyChanged("BGC_IdCasaMatriz");
                }
            }
        }
        private short _bGC_IdCasaMatriz;
    
        [DataMember]
        public decimal BGC_BaseOperacionNacional
        {
            get { return _bGC_BaseOperacionNacional; }
            set
            {
                if (_bGC_BaseOperacionNacional != value)
                {
                    _bGC_BaseOperacionNacional = value;
                    OnPropertyChanged("BGC_BaseOperacionNacional");
                }
            }
        }
        private decimal _bGC_BaseOperacionNacional;
    
        [DataMember]
        public decimal BGC_BaseCasaMatriz
        {
            get { return _bGC_BaseCasaMatriz; }
            set
            {
                if (_bGC_BaseCasaMatriz != value)
                {
                    _bGC_BaseCasaMatriz = value;
                    OnPropertyChanged("BGC_BaseCasaMatriz");
                }
            }
        }
        private decimal _bGC_BaseCasaMatriz;
    
        [DataMember]
        public System.DateTime BGC_FechaGrabacion
        {
            get { return _bGC_FechaGrabacion; }
            set
            {
                if (_bGC_FechaGrabacion != value)
                {
                    _bGC_FechaGrabacion = value;
                    OnPropertyChanged("BGC_FechaGrabacion");
                }
            }
        }
        private System.DateTime _bGC_FechaGrabacion;
    
        [DataMember]
        public string BGC_CreadoPor
        {
            get { return _bGC_CreadoPor; }
            set
            {
                if (_bGC_CreadoPor != value)
                {
                    _bGC_CreadoPor = value;
                    OnPropertyChanged("BGC_CreadoPor");
                }
            }
        }
        private string _bGC_CreadoPor;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
