//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Cajas.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RegistroTransaccionesCaja_CAJ))]
    public partial class RegistroVentaFormaPago_CAJ: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long RVF_IdRegistroVentaFormaPago
        {
            get { return _rVF_IdRegistroVentaFormaPago; }
            set
            {
                if (_rVF_IdRegistroVentaFormaPago != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RVF_IdRegistroVentaFormaPago' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _rVF_IdRegistroVentaFormaPago = value;
                    OnPropertyChanged("RVF_IdRegistroVentaFormaPago");
                }
            }
        }
        private long _rVF_IdRegistroVentaFormaPago;
    
        [DataMember]
        public long RVF_IdRegistroVenta
        {
            get { return _rVF_IdRegistroVenta; }
            set
            {
                if (_rVF_IdRegistroVenta != value)
                {
                    ChangeTracker.RecordOriginalValue("RVF_IdRegistroVenta", _rVF_IdRegistroVenta);
                    if (!IsDeserializing)
                    {
                        if (RegistroTransaccionesCaja_CAJ != null && RegistroTransaccionesCaja_CAJ.RTC_IdRegistroTranscaccion != value)
                        {
                            RegistroTransaccionesCaja_CAJ = null;
                        }
                    }
                    _rVF_IdRegistroVenta = value;
                    OnPropertyChanged("RVF_IdRegistroVenta");
                }
            }
        }
        private long _rVF_IdRegistroVenta;
    
        [DataMember]
        public short RVF_IdFormaPago
        {
            get { return _rVF_IdFormaPago; }
            set
            {
                if (_rVF_IdFormaPago != value)
                {
                    _rVF_IdFormaPago = value;
                    OnPropertyChanged("RVF_IdFormaPago");
                }
            }
        }
        private short _rVF_IdFormaPago;
    
        [DataMember]
        public string RVF_DescripcionFormaPago
        {
            get { return _rVF_DescripcionFormaPago; }
            set
            {
                if (_rVF_DescripcionFormaPago != value)
                {
                    _rVF_DescripcionFormaPago = value;
                    OnPropertyChanged("RVF_DescripcionFormaPago");
                }
            }
        }
        private string _rVF_DescripcionFormaPago;
    
        [DataMember]
        public decimal RVF_Valor
        {
            get { return _rVF_Valor; }
            set
            {
                if (_rVF_Valor != value)
                {
                    _rVF_Valor = value;
                    OnPropertyChanged("RVF_Valor");
                }
            }
        }
        private decimal _rVF_Valor;
    
        [DataMember]
        public string RVF_NumeroAsociado
        {
            get { return _rVF_NumeroAsociado; }
            set
            {
                if (_rVF_NumeroAsociado != value)
                {
                    _rVF_NumeroAsociado = value;
                    OnPropertyChanged("RVF_NumeroAsociado");
                }
            }
        }
        private string _rVF_NumeroAsociado;
    
        [DataMember]
        public string RVF_Campo1
        {
            get { return _rVF_Campo1; }
            set
            {
                if (_rVF_Campo1 != value)
                {
                    _rVF_Campo1 = value;
                    OnPropertyChanged("RVF_Campo1");
                }
            }
        }
        private string _rVF_Campo1;
    
        [DataMember]
        public string RVF_Campo2
        {
            get { return _rVF_Campo2; }
            set
            {
                if (_rVF_Campo2 != value)
                {
                    _rVF_Campo2 = value;
                    OnPropertyChanged("RVF_Campo2");
                }
            }
        }
        private string _rVF_Campo2;
    
        [DataMember]
        public System.DateTime RVF_FechaGrabacion
        {
            get { return _rVF_FechaGrabacion; }
            set
            {
                if (_rVF_FechaGrabacion != value)
                {
                    _rVF_FechaGrabacion = value;
                    OnPropertyChanged("RVF_FechaGrabacion");
                }
            }
        }
        private System.DateTime _rVF_FechaGrabacion;
    
        [DataMember]
        public string RVF_CreadoPor
        {
            get { return _rVF_CreadoPor; }
            set
            {
                if (_rVF_CreadoPor != value)
                {
                    _rVF_CreadoPor = value;
                    OnPropertyChanged("RVF_CreadoPor");
                }
            }
        }
        private string _rVF_CreadoPor;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public RegistroTransaccionesCaja_CAJ RegistroTransaccionesCaja_CAJ
        {
            get { return _registroTransaccionesCaja_CAJ; }
            set
            {
                if (!ReferenceEquals(_registroTransaccionesCaja_CAJ, value))
                {
                    var previousValue = _registroTransaccionesCaja_CAJ;
                    _registroTransaccionesCaja_CAJ = value;
                    FixupRegistroTransaccionesCaja_CAJ(previousValue);
                    OnNavigationPropertyChanged("RegistroTransaccionesCaja_CAJ");
                }
            }
        }
        private RegistroTransaccionesCaja_CAJ _registroTransaccionesCaja_CAJ;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            RegistroTransaccionesCaja_CAJ = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupRegistroTransaccionesCaja_CAJ(RegistroTransaccionesCaja_CAJ previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RegistroVentaFormaPago_CAJ.Contains(this))
            {
                previousValue.RegistroVentaFormaPago_CAJ.Remove(this);
            }
    
            if (RegistroTransaccionesCaja_CAJ != null)
            {
                if (!RegistroTransaccionesCaja_CAJ.RegistroVentaFormaPago_CAJ.Contains(this))
                {
                    RegistroTransaccionesCaja_CAJ.RegistroVentaFormaPago_CAJ.Add(this);
                }
    
                RVF_IdRegistroVenta = RegistroTransaccionesCaja_CAJ.RTC_IdRegistroTranscaccion;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RegistroTransaccionesCaja_CAJ")
                    && (ChangeTracker.OriginalValues["RegistroTransaccionesCaja_CAJ"] == RegistroTransaccionesCaja_CAJ))
                {
                    ChangeTracker.OriginalValues.Remove("RegistroTransaccionesCaja_CAJ");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RegistroTransaccionesCaja_CAJ", previousValue);
                }
                if (RegistroTransaccionesCaja_CAJ != null && !RegistroTransaccionesCaja_CAJ.ChangeTracker.ChangeTrackingEnabled)
                {
                    RegistroTransaccionesCaja_CAJ.StartTracking();
                }
            }
        }

        #endregion
    }
}
