//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.CentroServicios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia_VPUA
    {
        public string LOC_IdLocalidad { get; set; }
        public string LOC_Nombre { get; set; }
        public string LOC_IdAncestroPrimerGrado { get; set; }
        public string CES_IdZona { get; set; }
        public string CES_Nombre { get; set; }
        public long CES_IdCentroServicios { get; set; }
        public string CES_Tipo { get; set; }
        public string CES_DigitoVerificacion { get; set; }
        public int CES_IdPropietario { get; set; }
        public string CES_Telefono1 { get; set; }
        public string CES_Direccion { get; set; }
        public string CES_Estado { get; set; }
        public long AGE_IdAgencia { get; set; }
        public string LOC_IdAncestroSegundoGrado { get; set; }
        public string LOC_IdAncestroTercerGrado { get; set; }
        public string LOC_CodigoPostal { get; set; }
        public string LOC_NombreCorto { get; set; }
        public string AGE_NombreCentroLogistico { get; set; }
        public long AGE_IdCentroLogistico { get; set; }
        public decimal CES_PesoMaximo { get; set; }
        public bool CES_AdmiteFormaPagoAlCobro { get; set; }
        public decimal CES_VolumenMaximo { get; set; }
        public string AGE_IdTipoAgencia { get; set; }
        public bool CES_Sistematizada { get; set; }
    }
}
