//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.CentroServicios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificadorCanalVenta_PUA
    {
        public ClasificadorCanalVenta_PUA()
        {
            this.CentroServicios_PUA = new HashSet<CentroServicios_PUA>();
        }
    
        public short CCV_IdClasificadorCanalVenta { get; set; }
        public string CCV_ClasificadorCanalVenta { get; set; }
        public short CCV_IdTipoPropiedad { get; set; }
        public string CCV_Nombre { get; set; }
        public string CCV_IdTipoCentroServicos { get; set; }
        public System.DateTime CCV_FechaGrabacion { get; set; }
        public string CCV_CreadoPor { get; set; }
    
        public virtual TipoCentroServicios_PUA TipoCentroServicios_PUA { get; set; }
        public virtual TipoPropiedad_PUA TipoPropiedad_PUA { get; set; }
        public virtual ICollection<CentroServicios_PUA> CentroServicios_PUA { get; set; }
    }
}
