//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.CentroServicios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipioCentroLogistico_PUA
    {
        public string MCL_IdLocalidad { get; set; }
        public long MCL_IdCentroLogistico { get; set; }
        public System.DateTime MCL_FechaGrabacion { get; set; }
        public string MCL_CreadoPor { get; set; }
        public byte[] anchor { get; set; }
    
        public virtual CentroLogistico_PUA CentroLogistico_PUA { get; set; }
        public virtual Localidad_PAR Localidad_PAR { get; set; }
    }
}
