//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.CentroServicios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservacionCentroServicio_PUA
    {
        public long OCS_IdObservacionCentroServicio { get; set; }
        public long OCS_IdCentroServicios { get; set; }
        public string OCS_Motivo { get; set; }
        public string OCS_Obsevacion { get; set; }
        public System.DateTime OCS_FechaGrabacion { get; set; }
        public string OCS_CreadoPor { get; set; }
    
        public virtual CentroServicios_PUA CentroServicios_PUA { get; set; }
    }
}
