//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO.Servidor.CentroServicios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalAdministrativa_PUA
    {
        public RegionalAdministrativa_PUA()
        {
            this.CentroLogistico_PUA = new HashSet<CentroLogistico_PUA>();
            this.MunicipioRegionalAdm_PUA = new HashSet<MunicipioRegionalAdm_PUA>();
        }
    
        public long REA_IdRegionalAdm { get; set; }
        public string REA_Descripcion { get; set; }
        public System.DateTime REA_FechaGrabacion { get; set; }
        public string REA_CreadoPor { get; set; }
        public string REA_CodigoExternoSucursal { get; set; }
        public short REA_IdCasaMatriz { get; set; }
    
        public virtual ICollection<CentroLogistico_PUA> CentroLogistico_PUA { get; set; }
        public virtual ICollection<MunicipioRegionalAdm_PUA> MunicipioRegionalAdm_PUA { get; set; }
        public virtual CentroServicios_PUA CentroServicios_PUA { get; set; }
    }
}
