//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Tarifas.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class ListaPrecioSrvPrecioRango_VCLI: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int LPS_IdListaPrecioServicio
        {
            get { return _lPS_IdListaPrecioServicio; }
            set
            {
                if (_lPS_IdListaPrecioServicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LPS_IdListaPrecioServicio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lPS_IdListaPrecioServicio = value;
                    OnPropertyChanged("LPS_IdListaPrecioServicio");
                }
            }
        }
        private int _lPS_IdListaPrecioServicio;
    
        [DataMember]
        public int LPS_IdServicio
        {
            get { return _lPS_IdServicio; }
            set
            {
                if (_lPS_IdServicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LPS_IdServicio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lPS_IdServicio = value;
                    OnPropertyChanged("LPS_IdServicio");
                }
            }
        }
        private int _lPS_IdServicio;
    
        [DataMember]
        public int LPS_IdListaPrecios
        {
            get { return _lPS_IdListaPrecios; }
            set
            {
                if (_lPS_IdListaPrecios != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LPS_IdListaPrecios' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lPS_IdListaPrecios = value;
                    OnPropertyChanged("LPS_IdListaPrecios");
                }
            }
        }
        private int _lPS_IdListaPrecios;
    
        [DataMember]
        public decimal LPS_PrimaSeguros
        {
            get { return _lPS_PrimaSeguros; }
            set
            {
                if (_lPS_PrimaSeguros != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LPS_PrimaSeguros' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _lPS_PrimaSeguros = value;
                    OnPropertyChanged("LPS_PrimaSeguros");
                }
            }
        }
        private decimal _lPS_PrimaSeguros;
    
        [DataMember]
        public int PRA_IdListaPrecioServicio
        {
            get { return _pRA_IdListaPrecioServicio; }
            set
            {
                if (_pRA_IdListaPrecioServicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_IdListaPrecioServicio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_IdListaPrecioServicio = value;
                    OnPropertyChanged("PRA_IdListaPrecioServicio");
                }
            }
        }
        private int _pRA_IdListaPrecioServicio;
    
        [DataMember]
        public decimal PRA_Inicial
        {
            get { return _pRA_Inicial; }
            set
            {
                if (_pRA_Inicial != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_Inicial' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_Inicial = value;
                    OnPropertyChanged("PRA_Inicial");
                }
            }
        }
        private decimal _pRA_Inicial;
    
        [DataMember]
        public decimal PRA_Final
        {
            get { return _pRA_Final; }
            set
            {
                if (_pRA_Final != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_Final' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_Final = value;
                    OnPropertyChanged("PRA_Final");
                }
            }
        }
        private decimal _pRA_Final;
    
        [DataMember]
        public decimal PRA_Valor
        {
            get { return _pRA_Valor; }
            set
            {
                if (_pRA_Valor != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_Valor' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_Valor = value;
                    OnPropertyChanged("PRA_Valor");
                }
            }
        }
        private decimal _pRA_Valor;
    
        [DataMember]
        public decimal PRA_Porcentaje
        {
            get { return _pRA_Porcentaje; }
            set
            {
                if (_pRA_Porcentaje != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_Porcentaje' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_Porcentaje = value;
                    OnPropertyChanged("PRA_Porcentaje");
                }
            }
        }
        private decimal _pRA_Porcentaje;
    
        [DataMember]
        public long PRA_IdPrecioRango
        {
            get { return _pRA_IdPrecioRango; }
            set
            {
                if (_pRA_IdPrecioRango != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PRA_IdPrecioRango' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _pRA_IdPrecioRango = value;
                    OnPropertyChanged("PRA_IdPrecioRango");
                }
            }
        }
        private long _pRA_IdPrecioRango;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
