//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Tarifas.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Impuesto_TAR))]
    [KnownType(typeof(Servicio_TAR))]
    public partial class ServicioImpuesto_TAR: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int SEI_IdServicio
        {
            get { return _sEI_IdServicio; }
            set
            {
                if (_sEI_IdServicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SEI_IdServicio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Servicio_TAR != null && Servicio_TAR.SER_IdServicio != value)
                        {
                            Servicio_TAR = null;
                        }
                    }
                    _sEI_IdServicio = value;
                    OnPropertyChanged("SEI_IdServicio");
                }
            }
        }
        private int _sEI_IdServicio;
    
        [DataMember]
        public short SEI_IdImpuesto
        {
            get { return _sEI_IdImpuesto; }
            set
            {
                if (_sEI_IdImpuesto != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SEI_IdImpuesto' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Impuesto_TAR != null && Impuesto_TAR.IMP_IdImpuesto != value)
                        {
                            Impuesto_TAR = null;
                        }
                    }
                    _sEI_IdImpuesto = value;
                    OnPropertyChanged("SEI_IdImpuesto");
                }
            }
        }
        private short _sEI_IdImpuesto;
    
        [DataMember]
        public System.DateTime SEI_FechaGrabacion
        {
            get { return _sEI_FechaGrabacion; }
            set
            {
                if (_sEI_FechaGrabacion != value)
                {
                    _sEI_FechaGrabacion = value;
                    OnPropertyChanged("SEI_FechaGrabacion");
                }
            }
        }
        private System.DateTime _sEI_FechaGrabacion;
    
        [DataMember]
        public string SEI_CreadoPor
        {
            get { return _sEI_CreadoPor; }
            set
            {
                if (_sEI_CreadoPor != value)
                {
                    _sEI_CreadoPor = value;
                    OnPropertyChanged("SEI_CreadoPor");
                }
            }
        }
        private string _sEI_CreadoPor;
    
        [DataMember]
        public byte[] anchor
        {
            get { return _anchor; }
            set
            {
                if (_anchor != value)
                {
                    _anchor = value;
                    OnPropertyChanged("anchor");
                }
            }
        }
        private byte[] _anchor;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Impuesto_TAR Impuesto_TAR
        {
            get { return _impuesto_TAR; }
            set
            {
                if (!ReferenceEquals(_impuesto_TAR, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (SEI_IdImpuesto != value.IMP_IdImpuesto)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _impuesto_TAR;
                    _impuesto_TAR = value;
                    FixupImpuesto_TAR(previousValue);
                    OnNavigationPropertyChanged("Impuesto_TAR");
                }
            }
        }
        private Impuesto_TAR _impuesto_TAR;
    
        [DataMember]
        public Servicio_TAR Servicio_TAR
        {
            get { return _servicio_TAR; }
            set
            {
                if (!ReferenceEquals(_servicio_TAR, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (SEI_IdServicio != value.SER_IdServicio)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _servicio_TAR;
                    _servicio_TAR = value;
                    FixupServicio_TAR(previousValue);
                    OnNavigationPropertyChanged("Servicio_TAR");
                }
            }
        }
        private Servicio_TAR _servicio_TAR;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Impuesto_TAR = null;
            Servicio_TAR = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupImpuesto_TAR(Impuesto_TAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ServicioImpuesto_TAR.Contains(this))
            {
                previousValue.ServicioImpuesto_TAR.Remove(this);
            }
    
            if (Impuesto_TAR != null)
            {
                if (!Impuesto_TAR.ServicioImpuesto_TAR.Contains(this))
                {
                    Impuesto_TAR.ServicioImpuesto_TAR.Add(this);
                }
    
                SEI_IdImpuesto = Impuesto_TAR.IMP_IdImpuesto;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Impuesto_TAR")
                    && (ChangeTracker.OriginalValues["Impuesto_TAR"] == Impuesto_TAR))
                {
                    ChangeTracker.OriginalValues.Remove("Impuesto_TAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Impuesto_TAR", previousValue);
                }
                if (Impuesto_TAR != null && !Impuesto_TAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    Impuesto_TAR.StartTracking();
                }
            }
        }
    
        private void FixupServicio_TAR(Servicio_TAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ServicioImpuesto_TAR.Contains(this))
            {
                previousValue.ServicioImpuesto_TAR.Remove(this);
            }
    
            if (Servicio_TAR != null)
            {
                if (!Servicio_TAR.ServicioImpuesto_TAR.Contains(this))
                {
                    Servicio_TAR.ServicioImpuesto_TAR.Add(this);
                }
    
                SEI_IdServicio = Servicio_TAR.SER_IdServicio;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Servicio_TAR")
                    && (ChangeTracker.OriginalValues["Servicio_TAR"] == Servicio_TAR))
                {
                    ChangeTracker.OriginalValues.Remove("Servicio_TAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Servicio_TAR", previousValue);
                }
                if (Servicio_TAR != null && !Servicio_TAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    Servicio_TAR.StartTracking();
                }
            }
        }

        #endregion

    }
}
