//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Tarifas.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class ServicioImpuestos_VTAR: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int SEI_IdServicio
        {
            get { return _sEI_IdServicio; }
            set
            {
                if (_sEI_IdServicio != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SEI_IdServicio' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sEI_IdServicio = value;
                    OnPropertyChanged("SEI_IdServicio");
                }
            }
        }
        private int _sEI_IdServicio;
    
        [DataMember]
        public short SEI_IdImpuesto
        {
            get { return _sEI_IdImpuesto; }
            set
            {
                if (_sEI_IdImpuesto != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SEI_IdImpuesto' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sEI_IdImpuesto = value;
                    OnPropertyChanged("SEI_IdImpuesto");
                }
            }
        }
        private short _sEI_IdImpuesto;
    
        [DataMember]
        public string SER_Nombre
        {
            get { return _sER_Nombre; }
            set
            {
                if (_sER_Nombre != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_Nombre' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_Nombre = value;
                    OnPropertyChanged("SER_Nombre");
                }
            }
        }
        private string _sER_Nombre;
    
        [DataMember]
        public string SER_Descripcion
        {
            get { return _sER_Descripcion; }
            set
            {
                if (_sER_Descripcion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_Descripcion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_Descripcion = value;
                    OnPropertyChanged("SER_Descripcion");
                }
            }
        }
        private string _sER_Descripcion;
    
        [DataMember]
        public Nullable<short> SER_IdCuentaExterna
        {
            get { return _sER_IdCuentaExterna; }
            set
            {
                if (_sER_IdCuentaExterna != value)
                {
                    _sER_IdCuentaExterna = value;
                    OnPropertyChanged("SER_IdCuentaExterna");
                }
            }
        }
        private Nullable<short> _sER_IdCuentaExterna;
    
        [DataMember]
        public System.DateTime SER_HoraInicioVenta
        {
            get { return _sER_HoraInicioVenta; }
            set
            {
                if (_sER_HoraInicioVenta != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_HoraInicioVenta' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_HoraInicioVenta = value;
                    OnPropertyChanged("SER_HoraInicioVenta");
                }
            }
        }
        private System.DateTime _sER_HoraInicioVenta;
    
        [DataMember]
        public System.DateTime SER_HoraFinVenta
        {
            get { return _sER_HoraFinVenta; }
            set
            {
                if (_sER_HoraFinVenta != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_HoraFinVenta' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_HoraFinVenta = value;
                    OnPropertyChanged("SER_HoraFinVenta");
                }
            }
        }
        private System.DateTime _sER_HoraFinVenta;
    
        [DataMember]
        public string SER_IdentificadorInterno
        {
            get { return _sER_IdentificadorInterno; }
            set
            {
                if (_sER_IdentificadorInterno != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_IdentificadorInterno' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_IdentificadorInterno = value;
                    OnPropertyChanged("SER_IdentificadorInterno");
                }
            }
        }
        private string _sER_IdentificadorInterno;
    
        [DataMember]
        public bool SER_AplicaRetenciones
        {
            get { return _sER_AplicaRetenciones; }
            set
            {
                if (_sER_AplicaRetenciones != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SER_AplicaRetenciones' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _sER_AplicaRetenciones = value;
                    OnPropertyChanged("SER_AplicaRetenciones");
                }
            }
        }
        private bool _sER_AplicaRetenciones;
    
        [DataMember]
        public string IMP_Descripcion
        {
            get { return _iMP_Descripcion; }
            set
            {
                if (_iMP_Descripcion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IMP_Descripcion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iMP_Descripcion = value;
                    OnPropertyChanged("IMP_Descripcion");
                }
            }
        }
        private string _iMP_Descripcion;
    
        [DataMember]
        public decimal IMP_Valor
        {
            get { return _iMP_Valor; }
            set
            {
                if (_iMP_Valor != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IMP_Valor' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iMP_Valor = value;
                    OnPropertyChanged("IMP_Valor");
                }
            }
        }
        private decimal _iMP_Valor;
    
        [DataMember]
        public Nullable<short> IMP_IdCuentaExterna
        {
            get { return _iMP_IdCuentaExterna; }
            set
            {
                if (_iMP_IdCuentaExterna != value)
                {
                    _iMP_IdCuentaExterna = value;
                    OnPropertyChanged("IMP_IdCuentaExterna");
                }
            }
        }
        private Nullable<short> _iMP_IdCuentaExterna;
    
        [DataMember]
        public string UNE_IdUnidad
        {
            get { return _uNE_IdUnidad; }
            set
            {
                if (_uNE_IdUnidad != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UNE_IdUnidad' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _uNE_IdUnidad = value;
                    OnPropertyChanged("UNE_IdUnidad");
                }
            }
        }
        private string _uNE_IdUnidad;
    
        [DataMember]
        public string UNE_Nombre
        {
            get { return _uNE_Nombre; }
            set
            {
                if (_uNE_Nombre != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UNE_Nombre' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _uNE_Nombre = value;
                    OnPropertyChanged("UNE_Nombre");
                }
            }
        }
        private string _uNE_Nombre;
    
        [DataMember]
        public string UNE_Descripcion
        {
            get { return _uNE_Descripcion; }
            set
            {
                if (_uNE_Descripcion != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UNE_Descripcion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _uNE_Descripcion = value;
                    OnPropertyChanged("UNE_Descripcion");
                }
            }
        }
        private string _uNE_Descripcion;
    
        [DataMember]
        public Nullable<short> UNE_IdCuentaExterna
        {
            get { return _uNE_IdCuentaExterna; }
            set
            {
                if (_uNE_IdCuentaExterna != value)
                {
                    _uNE_IdCuentaExterna = value;
                    OnPropertyChanged("UNE_IdCuentaExterna");
                }
            }
        }
        private Nullable<short> _uNE_IdCuentaExterna;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
