//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Suministros.Datos.Modelo
{
    
    public partial class paObtenerSumProvisionadoMenFecha : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int MSS_IdProvisionSumMensajeroSerial
        {
            get { return _mSS_IdProvisionSumMensajeroSerial; }
            set
            {
                if (_mSS_IdProvisionSumMensajeroSerial != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_IdProvisionSumMensajeroSerial = value;
                    OnPropertyChanged("MSS_IdProvisionSumMensajeroSerial");
                }
            }
        }
        private int _mSS_IdProvisionSumMensajeroSerial;
    
        [DataMember]
        public long MSS_IdProvisionSumMensajero
        {
            get { return _mSS_IdProvisionSumMensajero; }
            set
            {
                if (_mSS_IdProvisionSumMensajero != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_IdProvisionSumMensajero = value;
                    OnPropertyChanged("MSS_IdProvisionSumMensajero");
                }
            }
        }
        private long _mSS_IdProvisionSumMensajero;
    
        [DataMember]
        public string MSS_Prefijo
        {
            get { return _mSS_Prefijo; }
            set
            {
                if (_mSS_Prefijo != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_Prefijo = value;
                    OnPropertyChanged("MSS_Prefijo");
                }
            }
        }
        private string _mSS_Prefijo;
    
        [DataMember]
        public long MSS_Inicio
        {
            get { return _mSS_Inicio; }
            set
            {
                if (_mSS_Inicio != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_Inicio = value;
                    OnPropertyChanged("MSS_Inicio");
                }
            }
        }
        private long _mSS_Inicio;
    
        [DataMember]
        public long MSS_Fin
        {
            get { return _mSS_Fin; }
            set
            {
                if (_mSS_Fin != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_Fin = value;
                    OnPropertyChanged("MSS_Fin");
                }
            }
        }
        private long _mSS_Fin;
    
        [DataMember]
        public System.DateTime MSS_FechaInicial
        {
            get { return _mSS_FechaInicial; }
            set
            {
                if (_mSS_FechaInicial != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_FechaInicial = value;
                    OnPropertyChanged("MSS_FechaInicial");
                }
            }
        }
        private System.DateTime _mSS_FechaInicial;
    
        [DataMember]
        public System.DateTime MSS_FechaFinal
        {
            get { return _mSS_FechaFinal; }
            set
            {
                if (_mSS_FechaFinal != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_FechaFinal = value;
                    OnPropertyChanged("MSS_FechaFinal");
                }
            }
        }
        private System.DateTime _mSS_FechaFinal;
    
        [DataMember]
        public System.DateTime MSS_FechaGrabacion
        {
            get { return _mSS_FechaGrabacion; }
            set
            {
                if (_mSS_FechaGrabacion != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_FechaGrabacion = value;
                    OnPropertyChanged("MSS_FechaGrabacion");
                }
            }
        }
        private System.DateTime _mSS_FechaGrabacion;
    
        [DataMember]
        public string MSS_CreadoPor
        {
            get { return _mSS_CreadoPor; }
            set
            {
                if (_mSS_CreadoPor != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_CreadoPor = value;
                    OnPropertyChanged("MSS_CreadoPor");
                }
            }
        }
        private string _mSS_CreadoPor;
    
        [DataMember]
        public int PSM_IdSuministroMensajero
        {
            get { return _pSM_IdSuministroMensajero; }
            set
            {
                if (_pSM_IdSuministroMensajero != value)
                {
                    OnComplexPropertyChanging();
                    _pSM_IdSuministroMensajero = value;
                    OnPropertyChanged("PSM_IdSuministroMensajero");
                }
            }
        }
        private int _pSM_IdSuministroMensajero;
    
        [DataMember]
        public string SUM_Descripcion
        {
            get { return _sUM_Descripcion; }
            set
            {
                if (_sUM_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_Descripcion = value;
                    OnPropertyChanged("SUM_Descripcion");
                }
            }
        }
        private string _sUM_Descripcion;
    
        [DataMember]
        public string RES_IdLocalidadDestino
        {
            get { return _rES_IdLocalidadDestino; }
            set
            {
                if (_rES_IdLocalidadDestino != value)
                {
                    OnComplexPropertyChanging();
                    _rES_IdLocalidadDestino = value;
                    OnPropertyChanged("RES_IdLocalidadDestino");
                }
            }
        }
        private string _rES_IdLocalidadDestino;
    
        [DataMember]
        public string PEI_Identificacion
        {
            get { return _pEI_Identificacion; }
            set
            {
                if (_pEI_Identificacion != value)
                {
                    OnComplexPropertyChanging();
                    _pEI_Identificacion = value;
                    OnPropertyChanged("PEI_Identificacion");
                }
            }
        }
        private string _pEI_Identificacion;
    
        [DataMember]
        public string PEI_PrimerApellido
        {
            get { return _pEI_PrimerApellido; }
            set
            {
                if (_pEI_PrimerApellido != value)
                {
                    OnComplexPropertyChanging();
                    _pEI_PrimerApellido = value;
                    OnPropertyChanged("PEI_PrimerApellido");
                }
            }
        }
        private string _pEI_PrimerApellido;
    
        [DataMember]
        public string PEI_SegundoApellido
        {
            get { return _pEI_SegundoApellido; }
            set
            {
                if (_pEI_SegundoApellido != value)
                {
                    OnComplexPropertyChanging();
                    _pEI_SegundoApellido = value;
                    OnPropertyChanged("PEI_SegundoApellido");
                }
            }
        }
        private string _pEI_SegundoApellido;
    
        [DataMember]
        public string PEI_Nombre
        {
            get { return _pEI_Nombre; }
            set
            {
                if (_pEI_Nombre != value)
                {
                    OnComplexPropertyChanging();
                    _pEI_Nombre = value;
                    OnPropertyChanged("PEI_Nombre");
                }
            }
        }
        private string _pEI_Nombre;
    
        [DataMember]
        public decimal SME_CantidadInicialAutorizada
        {
            get { return _sME_CantidadInicialAutorizada; }
            set
            {
                if (_sME_CantidadInicialAutorizada != value)
                {
                    OnComplexPropertyChanging();
                    _sME_CantidadInicialAutorizada = value;
                    OnPropertyChanged("SME_CantidadInicialAutorizada");
                }
            }
        }
        private decimal _sME_CantidadInicialAutorizada;
    
        [DataMember]
        public int SME_IdSuministro
        {
            get { return _sME_IdSuministro; }
            set
            {
                if (_sME_IdSuministro != value)
                {
                    OnComplexPropertyChanging();
                    _sME_IdSuministro = value;
                    OnPropertyChanged("SME_IdSuministro");
                }
            }
        }
        private int _sME_IdSuministro;
    
        [DataMember]
        public long PSM_IdRemisionSuministros
        {
            get { return _pSM_IdRemisionSuministros; }
            set
            {
                if (_pSM_IdRemisionSuministros != value)
                {
                    OnComplexPropertyChanging();
                    _pSM_IdRemisionSuministros = value;
                    OnPropertyChanged("PSM_IdRemisionSuministros");
                }
            }
        }
        private long _pSM_IdRemisionSuministros;
    
        [DataMember]
        public System.DateTime RES_FechaGrabacion
        {
            get { return _rES_FechaGrabacion; }
            set
            {
                if (_rES_FechaGrabacion != value)
                {
                    OnComplexPropertyChanging();
                    _rES_FechaGrabacion = value;
                    OnPropertyChanged("RES_FechaGrabacion");
                }
            }
        }
        private System.DateTime _rES_FechaGrabacion;
    
        [DataMember]
        public int SUM_IdSuministro
        {
            get { return _sUM_IdSuministro; }
            set
            {
                if (_sUM_IdSuministro != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_IdSuministro = value;
                    OnPropertyChanged("SUM_IdSuministro");
                }
            }
        }
        private int _sUM_IdSuministro;
    
        [DataMember]
        public decimal PSM_CantidadAsginada
        {
            get { return _pSM_CantidadAsginada; }
            set
            {
                if (_pSM_CantidadAsginada != value)
                {
                    OnComplexPropertyChanging();
                    _pSM_CantidadAsginada = value;
                    OnPropertyChanged("PSM_CantidadAsginada");
                }
            }
        }
        private decimal _pSM_CantidadAsginada;
    
        [DataMember]
        public long SME_IdMensajero
        {
            get { return _sME_IdMensajero; }
            set
            {
                if (_sME_IdMensajero != value)
                {
                    OnComplexPropertyChanging();
                    _sME_IdMensajero = value;
                    OnPropertyChanged("SME_IdMensajero");
                }
            }
        }
        private long _sME_IdMensajero;
    
        [DataMember]
        public string MSS_IdNumerador
        {
            get { return _mSS_IdNumerador; }
            set
            {
                if (_mSS_IdNumerador != value)
                {
                    OnComplexPropertyChanging();
                    _mSS_IdNumerador = value;
                    OnPropertyChanged("MSS_IdNumerador");
                }
            }
        }
        private string _mSS_IdNumerador;
    
        [DataMember]
        public int SME_IdSuministroMensajero
        {
            get { return _sME_IdSuministroMensajero; }
            set
            {
                if (_sME_IdSuministroMensajero != value)
                {
                    OnComplexPropertyChanging();
                    _sME_IdSuministroMensajero = value;
                    OnPropertyChanged("SME_IdSuministroMensajero");
                }
            }
        }
        private int _sME_IdSuministroMensajero;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, paObtenerSumProvisionadoMenFecha complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_IdProvisionSumMensajeroSerial", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_IdProvisionSumMensajeroSerial);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_IdProvisionSumMensajero", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_IdProvisionSumMensajero);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_Prefijo", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_Prefijo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_Inicio", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_Inicio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_Fin", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_Fin);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_FechaInicial", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_FechaInicial);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_FechaFinal", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_FechaFinal);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_FechaGrabacion", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_FechaGrabacion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_CreadoPor", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_CreadoPor);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PSM_IdSuministroMensajero", parentPropertyName), complexObject == null ? null : (object)complexObject.PSM_IdSuministroMensajero);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.RES_IdLocalidadDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.RES_IdLocalidadDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PEI_Identificacion", parentPropertyName), complexObject == null ? null : (object)complexObject.PEI_Identificacion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PEI_PrimerApellido", parentPropertyName), complexObject == null ? null : (object)complexObject.PEI_PrimerApellido);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PEI_SegundoApellido", parentPropertyName), complexObject == null ? null : (object)complexObject.PEI_SegundoApellido);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PEI_Nombre", parentPropertyName), complexObject == null ? null : (object)complexObject.PEI_Nombre);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_CantidadInicialAutorizada", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_CantidadInicialAutorizada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_IdSuministro", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_IdSuministro);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PSM_IdRemisionSuministros", parentPropertyName), complexObject == null ? null : (object)complexObject.PSM_IdRemisionSuministros);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.RES_FechaGrabacion", parentPropertyName), complexObject == null ? null : (object)complexObject.RES_FechaGrabacion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_IdSuministro", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_IdSuministro);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PSM_CantidadAsginada", parentPropertyName), complexObject == null ? null : (object)complexObject.PSM_CantidadAsginada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_IdMensajero", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_IdMensajero);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.MSS_IdNumerador", parentPropertyName), complexObject == null ? null : (object)complexObject.MSS_IdNumerador);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_IdSuministroMensajero", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_IdSuministroMensajero);
        }

        #endregion

    }
}
