//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Suministros.Datos.Modelo
{
    
    public partial class SUpaObtenerCentroSrvPropietarioSuministro : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public decimal SCS_StockMinimo
        {
            get { return _sCS_StockMinimo; }
            set
            {
                if (_sCS_StockMinimo != value)
                {
                    OnComplexPropertyChanging();
                    _sCS_StockMinimo = value;
                    OnPropertyChanged("SCS_StockMinimo");
                }
            }
        }
        private decimal _sCS_StockMinimo;
    
        [DataMember]
        public string PCS_Prefijo
        {
            get { return _pCS_Prefijo; }
            set
            {
                if (_pCS_Prefijo != value)
                {
                    OnComplexPropertyChanging();
                    _pCS_Prefijo = value;
                    OnPropertyChanged("PCS_Prefijo");
                }
            }
        }
        private string _pCS_Prefijo;
    
        [DataMember]
        public long PCS_Inicio
        {
            get { return _pCS_Inicio; }
            set
            {
                if (_pCS_Inicio != value)
                {
                    OnComplexPropertyChanging();
                    _pCS_Inicio = value;
                    OnPropertyChanged("PCS_Inicio");
                }
            }
        }
        private long _pCS_Inicio;
    
        [DataMember]
        public long PCS_Fin
        {
            get { return _pCS_Fin; }
            set
            {
                if (_pCS_Fin != value)
                {
                    OnComplexPropertyChanging();
                    _pCS_Fin = value;
                    OnPropertyChanged("PCS_Fin");
                }
            }
        }
        private long _pCS_Fin;
    
        [DataMember]
        public System.DateTime PCS_FechaInicial
        {
            get { return _pCS_FechaInicial; }
            set
            {
                if (_pCS_FechaInicial != value)
                {
                    OnComplexPropertyChanging();
                    _pCS_FechaInicial = value;
                    OnPropertyChanged("PCS_FechaInicial");
                }
            }
        }
        private System.DateTime _pCS_FechaInicial;
    
        [DataMember]
        public System.DateTime PCS_FechaFinal
        {
            get { return _pCS_FechaFinal; }
            set
            {
                if (_pCS_FechaFinal != value)
                {
                    OnComplexPropertyChanging();
                    _pCS_FechaFinal = value;
                    OnPropertyChanged("PCS_FechaFinal");
                }
            }
        }
        private System.DateTime _pCS_FechaFinal;
    
        [DataMember]
        public decimal PSC_CantidadAsginada
        {
            get { return _pSC_CantidadAsginada; }
            set
            {
                if (_pSC_CantidadAsginada != value)
                {
                    OnComplexPropertyChanging();
                    _pSC_CantidadAsginada = value;
                    OnPropertyChanged("PSC_CantidadAsginada");
                }
            }
        }
        private decimal _pSC_CantidadAsginada;
    
        [DataMember]
        public long SCS_IdCentroServicios
        {
            get { return _sCS_IdCentroServicios; }
            set
            {
                if (_sCS_IdCentroServicios != value)
                {
                    OnComplexPropertyChanging();
                    _sCS_IdCentroServicios = value;
                    OnPropertyChanged("SCS_IdCentroServicios");
                }
            }
        }
        private long _sCS_IdCentroServicios;
    
        [DataMember]
        public string SUM_Descripcion
        {
            get { return _sUM_Descripcion; }
            set
            {
                if (_sUM_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_Descripcion = value;
                    OnPropertyChanged("SUM_Descripcion");
                }
            }
        }
        private string _sUM_Descripcion;
    
        [DataMember]
        public int SUM_IdSuministro
        {
            get { return _sUM_IdSuministro; }
            set
            {
                if (_sUM_IdSuministro != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_IdSuministro = value;
                    OnPropertyChanged("SUM_IdSuministro");
                }
            }
        }
        private int _sUM_IdSuministro;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, SUpaObtenerCentroSrvPropietarioSuministro complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SCS_StockMinimo", parentPropertyName), complexObject == null ? null : (object)complexObject.SCS_StockMinimo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PCS_Prefijo", parentPropertyName), complexObject == null ? null : (object)complexObject.PCS_Prefijo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PCS_Inicio", parentPropertyName), complexObject == null ? null : (object)complexObject.PCS_Inicio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PCS_Fin", parentPropertyName), complexObject == null ? null : (object)complexObject.PCS_Fin);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PCS_FechaInicial", parentPropertyName), complexObject == null ? null : (object)complexObject.PCS_FechaInicial);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PCS_FechaFinal", parentPropertyName), complexObject == null ? null : (object)complexObject.PCS_FechaFinal);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.PSC_CantidadAsginada", parentPropertyName), complexObject == null ? null : (object)complexObject.PSC_CantidadAsginada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SCS_IdCentroServicios", parentPropertyName), complexObject == null ? null : (object)complexObject.SCS_IdCentroServicios);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_IdSuministro", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_IdSuministro);
        }

        #endregion

    }
}
