//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Suministros.Datos.Modelo
{
    
    public partial class SUpaObtenerSumAsignadoYNoAsigMen : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string SUM_CodigoERP
        {
            get { return _sUM_CodigoERP; }
            set
            {
                if (_sUM_CodigoERP != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_CodigoERP = value;
                    OnPropertyChanged("SUM_CodigoERP");
                }
            }
        }
        private string _sUM_CodigoERP;
    
        [DataMember]
        public string SUM_CodigoAlterno
        {
            get { return _sUM_CodigoAlterno; }
            set
            {
                if (_sUM_CodigoAlterno != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_CodigoAlterno = value;
                    OnPropertyChanged("SUM_CodigoAlterno");
                }
            }
        }
        private string _sUM_CodigoAlterno;
    
        [DataMember]
        public string SUM_Descripcion
        {
            get { return _sUM_Descripcion; }
            set
            {
                if (_sUM_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_Descripcion = value;
                    OnPropertyChanged("SUM_Descripcion");
                }
            }
        }
        private string _sUM_Descripcion;
    
        [DataMember]
        public string UNM_Descripcion
        {
            get { return _uNM_Descripcion; }
            set
            {
                if (_uNM_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _uNM_Descripcion = value;
                    OnPropertyChanged("UNM_Descripcion");
                }
            }
        }
        private string _uNM_Descripcion;
    
        [DataMember]
        public bool SUM_SePreImprime
        {
            get { return _sUM_SePreImprime; }
            set
            {
                if (_sUM_SePreImprime != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_SePreImprime = value;
                    OnPropertyChanged("SUM_SePreImprime");
                }
            }
        }
        private bool _sUM_SePreImprime;
    
        [DataMember]
        public int SME_IdSuministro
        {
            get { return _sME_IdSuministro; }
            set
            {
                if (_sME_IdSuministro != value)
                {
                    OnComplexPropertyChanging();
                    _sME_IdSuministro = value;
                    OnPropertyChanged("SME_IdSuministro");
                }
            }
        }
        private int _sME_IdSuministro;
    
        [DataMember]
        public int asignado
        {
            get { return _asignado; }
            set
            {
                if (_asignado != value)
                {
                    OnComplexPropertyChanging();
                    _asignado = value;
                    OnPropertyChanged("asignado");
                }
            }
        }
        private int _asignado;
    
        [DataMember]
        public string SUM_IdUnidadMedida
        {
            get { return _sUM_IdUnidadMedida; }
            set
            {
                if (_sUM_IdUnidadMedida != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_IdUnidadMedida = value;
                    OnPropertyChanged("SUM_IdUnidadMedida");
                }
            }
        }
        private string _sUM_IdUnidadMedida;
    
        [DataMember]
        public string SUM_Estado
        {
            get { return _sUM_Estado; }
            set
            {
                if (_sUM_Estado != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_Estado = value;
                    OnPropertyChanged("SUM_Estado");
                }
            }
        }
        private string _sUM_Estado;
    
        [DataMember]
        public bool SUM_AplicaResolucion
        {
            get { return _sUM_AplicaResolucion; }
            set
            {
                if (_sUM_AplicaResolucion != value)
                {
                    OnComplexPropertyChanging();
                    _sUM_AplicaResolucion = value;
                    OnPropertyChanged("SUM_AplicaResolucion");
                }
            }
        }
        private bool _sUM_AplicaResolucion;
    
        [DataMember]
        public decimal SME_CantidadInicialAutorizada
        {
            get { return _sME_CantidadInicialAutorizada; }
            set
            {
                if (_sME_CantidadInicialAutorizada != value)
                {
                    OnComplexPropertyChanging();
                    _sME_CantidadInicialAutorizada = value;
                    OnPropertyChanged("SME_CantidadInicialAutorizada");
                }
            }
        }
        private decimal _sME_CantidadInicialAutorizada;
    
        [DataMember]
        public decimal SME_StockMinimo
        {
            get { return _sME_StockMinimo; }
            set
            {
                if (_sME_StockMinimo != value)
                {
                    OnComplexPropertyChanging();
                    _sME_StockMinimo = value;
                    OnPropertyChanged("SME_StockMinimo");
                }
            }
        }
        private decimal _sME_StockMinimo;
    
        [DataMember]
        public string SME_Estado
        {
            get { return _sME_Estado; }
            set
            {
                if (_sME_Estado != value)
                {
                    OnComplexPropertyChanging();
                    _sME_Estado = value;
                    OnPropertyChanged("SME_Estado");
                }
            }
        }
        private string _sME_Estado;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, SUpaObtenerSumAsignadoYNoAsigMen complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_CodigoERP", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_CodigoERP);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_CodigoAlterno", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_CodigoAlterno);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.UNM_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.UNM_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_SePreImprime", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_SePreImprime);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_IdSuministro", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_IdSuministro);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.asignado", parentPropertyName), complexObject == null ? null : (object)complexObject.asignado);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_IdUnidadMedida", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_IdUnidadMedida);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_Estado", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_Estado);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SUM_AplicaResolucion", parentPropertyName), complexObject == null ? null : (object)complexObject.SUM_AplicaResolucion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_CantidadInicialAutorizada", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_CantidadInicialAutorizada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_StockMinimo", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_StockMinimo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.SME_Estado", parentPropertyName), complexObject == null ? null : (object)complexObject.SME_Estado);
        }

        #endregion

    }
}
