//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Suministros.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(InventarioConsolidadoTula_SUM))]
    public partial class TamanoTula_SUM: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public short TAT_IdTamanoTula
        {
            get { return _tAT_IdTamanoTula; }
            set
            {
                if (_tAT_IdTamanoTula != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TAT_IdTamanoTula' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _tAT_IdTamanoTula = value;
                    OnPropertyChanged("TAT_IdTamanoTula");
                }
            }
        }
        private short _tAT_IdTamanoTula;
    
        [DataMember]
        public string TAT_Descripcion
        {
            get { return _tAT_Descripcion; }
            set
            {
                if (_tAT_Descripcion != value)
                {
                    _tAT_Descripcion = value;
                    OnPropertyChanged("TAT_Descripcion");
                }
            }
        }
        private string _tAT_Descripcion;
    
        [DataMember]
        public string TAT_CreadoPor
        {
            get { return _tAT_CreadoPor; }
            set
            {
                if (_tAT_CreadoPor != value)
                {
                    _tAT_CreadoPor = value;
                    OnPropertyChanged("TAT_CreadoPor");
                }
            }
        }
        private string _tAT_CreadoPor;
    
        [DataMember]
        public System.DateTime TAT_FechaGrabacion
        {
            get { return _tAT_FechaGrabacion; }
            set
            {
                if (_tAT_FechaGrabacion != value)
                {
                    _tAT_FechaGrabacion = value;
                    OnPropertyChanged("TAT_FechaGrabacion");
                }
            }
        }
        private System.DateTime _tAT_FechaGrabacion;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<InventarioConsolidadoTula_SUM> InventarioConsolidadoTula_SUM
        {
            get
            {
                if (_inventarioConsolidadoTula_SUM == null)
                {
                    _inventarioConsolidadoTula_SUM = new TrackableCollection<InventarioConsolidadoTula_SUM>();
                    _inventarioConsolidadoTula_SUM.CollectionChanged += FixupInventarioConsolidadoTula_SUM;
                }
                return _inventarioConsolidadoTula_SUM;
            }
            set
            {
                if (!ReferenceEquals(_inventarioConsolidadoTula_SUM, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_inventarioConsolidadoTula_SUM != null)
                    {
                        _inventarioConsolidadoTula_SUM.CollectionChanged -= FixupInventarioConsolidadoTula_SUM;
                    }
                    _inventarioConsolidadoTula_SUM = value;
                    if (_inventarioConsolidadoTula_SUM != null)
                    {
                        _inventarioConsolidadoTula_SUM.CollectionChanged += FixupInventarioConsolidadoTula_SUM;
                    }
                    OnNavigationPropertyChanged("InventarioConsolidadoTula_SUM");
                }
            }
        }
        private TrackableCollection<InventarioConsolidadoTula_SUM> _inventarioConsolidadoTula_SUM;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            InventarioConsolidadoTula_SUM.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupInventarioConsolidadoTula_SUM(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (InventarioConsolidadoTula_SUM item in e.NewItems)
                {
                    item.TamanoTula_SUM = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("InventarioConsolidadoTula_SUM", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (InventarioConsolidadoTula_SUM item in e.OldItems)
                {
                    if (ReferenceEquals(item.TamanoTula_SUM, this))
                    {
                        item.TamanoTula_SUM = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("InventarioConsolidadoTula_SUM", item);
                    }
                }
            }
        }

        #endregion

    }
}
