//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Adminisiones.Mensajeria.Datos.Modelo
{
    
    public partial class AD_paValorAdicional : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long AVA_IdAdminisionMensajeria
        {
            get { return _aVA_IdAdminisionMensajeria; }
            set
            {
                if (_aVA_IdAdminisionMensajeria != value)
                {
                    OnComplexPropertyChanging();
                    _aVA_IdAdminisionMensajeria = value;
                    OnPropertyChanged("AVA_IdAdminisionMensajeria");
                }
            }
        }
        private long _aVA_IdAdminisionMensajeria;
    
        [DataMember]
        public string AVA_IdTipoValorAdicional
        {
            get { return _aVA_IdTipoValorAdicional; }
            set
            {
                if (_aVA_IdTipoValorAdicional != value)
                {
                    OnComplexPropertyChanging();
                    _aVA_IdTipoValorAdicional = value;
                    OnPropertyChanged("AVA_IdTipoValorAdicional");
                }
            }
        }
        private string _aVA_IdTipoValorAdicional;
    
        [DataMember]
        public string AVA_Descripcion
        {
            get { return _aVA_Descripcion; }
            set
            {
                if (_aVA_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _aVA_Descripcion = value;
                    OnPropertyChanged("AVA_Descripcion");
                }
            }
        }
        private string _aVA_Descripcion;
    
        [DataMember]
        public decimal AVA_Valor
        {
            get { return _aVA_Valor; }
            set
            {
                if (_aVA_Valor != value)
                {
                    OnComplexPropertyChanging();
                    _aVA_Valor = value;
                    OnPropertyChanged("AVA_Valor");
                }
            }
        }
        private decimal _aVA_Valor;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, AD_paValorAdicional complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AVA_IdAdminisionMensajeria", parentPropertyName), complexObject == null ? null : (object)complexObject.AVA_IdAdminisionMensajeria);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AVA_IdTipoValorAdicional", parentPropertyName), complexObject == null ? null : (object)complexObject.AVA_IdTipoValorAdicional);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AVA_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.AVA_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AVA_Valor", parentPropertyName), complexObject == null ? null : (object)complexObject.AVA_Valor);
        }

        #endregion

    }
}
