//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Adminisiones.Mensajeria.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdminisionMensajeriaGuiaRelacion_MEN))]
    [KnownType(typeof(AdmisionNotificaciones_MEN))]
    [KnownType(typeof(AdmisionRotulos_MEN))]
    [KnownType(typeof(EstadoGuiaTraza_MEN))]
    [KnownType(typeof(MensajeriaConvenioConvenio_MEN))]
    [KnownType(typeof(MensajeriaConvenioPeaton_MEN))]
    [KnownType(typeof(OrdenServicioMasivoGuia_MEN))]
    [KnownType(typeof(RecibidoGuia_LOI))]
    [KnownType(typeof(AlmacenGuia_LOI))]
    [KnownType(typeof(NovedadGuia_MEN))]
    public partial class AdmisionMensajeria_MEN: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long ADM_IdAdminisionMensajeria
        {
            get { return _aDM_IdAdminisionMensajeria; }
            set
            {
                if (_aDM_IdAdminisionMensajeria != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ADM_IdAdminisionMensajeria' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _aDM_IdAdminisionMensajeria = value;
                    OnPropertyChanged("ADM_IdAdminisionMensajeria");
                }
            }
        }
        private long _aDM_IdAdminisionMensajeria;
    
        [DataMember]
        public string ADM_PrefijoNumeroGuia
        {
            get { return _aDM_PrefijoNumeroGuia; }
            set
            {
                if (_aDM_PrefijoNumeroGuia != value)
                {
                    _aDM_PrefijoNumeroGuia = value;
                    OnPropertyChanged("ADM_PrefijoNumeroGuia");
                }
            }
        }
        private string _aDM_PrefijoNumeroGuia;
    
        [DataMember]
        public long ADM_NumeroGuia
        {
            get { return _aDM_NumeroGuia; }
            set
            {
                if (_aDM_NumeroGuia != value)
                {
                    _aDM_NumeroGuia = value;
                    OnPropertyChanged("ADM_NumeroGuia");
                }
            }
        }
        private long _aDM_NumeroGuia;
    
        [DataMember]
        public string ADM_DigitoVerificacion
        {
            get { return _aDM_DigitoVerificacion; }
            set
            {
                if (_aDM_DigitoVerificacion != value)
                {
                    _aDM_DigitoVerificacion = value;
                    OnPropertyChanged("ADM_DigitoVerificacion");
                }
            }
        }
        private string _aDM_DigitoVerificacion;
    
        [DataMember]
        public string ADM_GuidDeChequeo
        {
            get { return _aDM_GuidDeChequeo; }
            set
            {
                if (_aDM_GuidDeChequeo != value)
                {
                    _aDM_GuidDeChequeo = value;
                    OnPropertyChanged("ADM_GuidDeChequeo");
                }
            }
        }
        private string _aDM_GuidDeChequeo;
    
        [DataMember]
        public bool ADM_EsAutomatico
        {
            get { return _aDM_EsAutomatico; }
            set
            {
                if (_aDM_EsAutomatico != value)
                {
                    _aDM_EsAutomatico = value;
                    OnPropertyChanged("ADM_EsAutomatico");
                }
            }
        }
        private bool _aDM_EsAutomatico;
    
        [DataMember]
        public string ADM_IdUnidadNegocio
        {
            get { return _aDM_IdUnidadNegocio; }
            set
            {
                if (_aDM_IdUnidadNegocio != value)
                {
                    _aDM_IdUnidadNegocio = value;
                    OnPropertyChanged("ADM_IdUnidadNegocio");
                }
            }
        }
        private string _aDM_IdUnidadNegocio;
    
        [DataMember]
        public int ADM_IdServicio
        {
            get { return _aDM_IdServicio; }
            set
            {
                if (_aDM_IdServicio != value)
                {
                    _aDM_IdServicio = value;
                    OnPropertyChanged("ADM_IdServicio");
                }
            }
        }
        private int _aDM_IdServicio;
    
        [DataMember]
        public string ADM_NombreServicio
        {
            get { return _aDM_NombreServicio; }
            set
            {
                if (_aDM_NombreServicio != value)
                {
                    _aDM_NombreServicio = value;
                    OnPropertyChanged("ADM_NombreServicio");
                }
            }
        }
        private string _aDM_NombreServicio;
    
        [DataMember]
        public string ADM_IdTipoEntrega
        {
            get { return _aDM_IdTipoEntrega; }
            set
            {
                if (_aDM_IdTipoEntrega != value)
                {
                    _aDM_IdTipoEntrega = value;
                    OnPropertyChanged("ADM_IdTipoEntrega");
                }
            }
        }
        private string _aDM_IdTipoEntrega;
    
        [DataMember]
        public string ADM_DescripcionTipoEntrega
        {
            get { return _aDM_DescripcionTipoEntrega; }
            set
            {
                if (_aDM_DescripcionTipoEntrega != value)
                {
                    _aDM_DescripcionTipoEntrega = value;
                    OnPropertyChanged("ADM_DescripcionTipoEntrega");
                }
            }
        }
        private string _aDM_DescripcionTipoEntrega;
    
        [DataMember]
        public long ADM_IdCentroServicioOrigen
        {
            get { return _aDM_IdCentroServicioOrigen; }
            set
            {
                if (_aDM_IdCentroServicioOrigen != value)
                {
                    _aDM_IdCentroServicioOrigen = value;
                    OnPropertyChanged("ADM_IdCentroServicioOrigen");
                }
            }
        }
        private long _aDM_IdCentroServicioOrigen;
    
        [DataMember]
        public string ADM_NombreCentroServicioOrigen
        {
            get { return _aDM_NombreCentroServicioOrigen; }
            set
            {
                if (_aDM_NombreCentroServicioOrigen != value)
                {
                    _aDM_NombreCentroServicioOrigen = value;
                    OnPropertyChanged("ADM_NombreCentroServicioOrigen");
                }
            }
        }
        private string _aDM_NombreCentroServicioOrigen;
    
        [DataMember]
        public long ADM_IdCentroServicioDestino
        {
            get { return _aDM_IdCentroServicioDestino; }
            set
            {
                if (_aDM_IdCentroServicioDestino != value)
                {
                    _aDM_IdCentroServicioDestino = value;
                    OnPropertyChanged("ADM_IdCentroServicioDestino");
                }
            }
        }
        private long _aDM_IdCentroServicioDestino;
    
        [DataMember]
        public string ADM_NombreCentroServicioDestino
        {
            get { return _aDM_NombreCentroServicioDestino; }
            set
            {
                if (_aDM_NombreCentroServicioDestino != value)
                {
                    _aDM_NombreCentroServicioDestino = value;
                    OnPropertyChanged("ADM_NombreCentroServicioDestino");
                }
            }
        }
        private string _aDM_NombreCentroServicioDestino;
    
        [DataMember]
        public string ADM_IdPaisOrigen
        {
            get { return _aDM_IdPaisOrigen; }
            set
            {
                if (_aDM_IdPaisOrigen != value)
                {
                    _aDM_IdPaisOrigen = value;
                    OnPropertyChanged("ADM_IdPaisOrigen");
                }
            }
        }
        private string _aDM_IdPaisOrigen;
    
        [DataMember]
        public string ADM_NombrePaisOrigen
        {
            get { return _aDM_NombrePaisOrigen; }
            set
            {
                if (_aDM_NombrePaisOrigen != value)
                {
                    _aDM_NombrePaisOrigen = value;
                    OnPropertyChanged("ADM_NombrePaisOrigen");
                }
            }
        }
        private string _aDM_NombrePaisOrigen;
    
        [DataMember]
        public string ADM_IdCiudadOrigen
        {
            get { return _aDM_IdCiudadOrigen; }
            set
            {
                if (_aDM_IdCiudadOrigen != value)
                {
                    _aDM_IdCiudadOrigen = value;
                    OnPropertyChanged("ADM_IdCiudadOrigen");
                }
            }
        }
        private string _aDM_IdCiudadOrigen;
    
        [DataMember]
        public string ADM_NombreCiudadOrigen
        {
            get { return _aDM_NombreCiudadOrigen; }
            set
            {
                if (_aDM_NombreCiudadOrigen != value)
                {
                    _aDM_NombreCiudadOrigen = value;
                    OnPropertyChanged("ADM_NombreCiudadOrigen");
                }
            }
        }
        private string _aDM_NombreCiudadOrigen;
    
        [DataMember]
        public string ADM_CodigoPostalOrigen
        {
            get { return _aDM_CodigoPostalOrigen; }
            set
            {
                if (_aDM_CodigoPostalOrigen != value)
                {
                    _aDM_CodigoPostalOrigen = value;
                    OnPropertyChanged("ADM_CodigoPostalOrigen");
                }
            }
        }
        private string _aDM_CodigoPostalOrigen;
    
        [DataMember]
        public string ADM_IdPaisDestino
        {
            get { return _aDM_IdPaisDestino; }
            set
            {
                if (_aDM_IdPaisDestino != value)
                {
                    _aDM_IdPaisDestino = value;
                    OnPropertyChanged("ADM_IdPaisDestino");
                }
            }
        }
        private string _aDM_IdPaisDestino;
    
        [DataMember]
        public string ADM_NombrePaisDestino
        {
            get { return _aDM_NombrePaisDestino; }
            set
            {
                if (_aDM_NombrePaisDestino != value)
                {
                    _aDM_NombrePaisDestino = value;
                    OnPropertyChanged("ADM_NombrePaisDestino");
                }
            }
        }
        private string _aDM_NombrePaisDestino;
    
        [DataMember]
        public string ADM_IdCiudadDestino
        {
            get { return _aDM_IdCiudadDestino; }
            set
            {
                if (_aDM_IdCiudadDestino != value)
                {
                    _aDM_IdCiudadDestino = value;
                    OnPropertyChanged("ADM_IdCiudadDestino");
                }
            }
        }
        private string _aDM_IdCiudadDestino;
    
        [DataMember]
        public string ADM_NombreCiudadDestino
        {
            get { return _aDM_NombreCiudadDestino; }
            set
            {
                if (_aDM_NombreCiudadDestino != value)
                {
                    _aDM_NombreCiudadDestino = value;
                    OnPropertyChanged("ADM_NombreCiudadDestino");
                }
            }
        }
        private string _aDM_NombreCiudadDestino;
    
        [DataMember]
        public string ADM_CodigoPostalDestino
        {
            get { return _aDM_CodigoPostalDestino; }
            set
            {
                if (_aDM_CodigoPostalDestino != value)
                {
                    _aDM_CodigoPostalDestino = value;
                    OnPropertyChanged("ADM_CodigoPostalDestino");
                }
            }
        }
        private string _aDM_CodigoPostalDestino;
    
        [DataMember]
        public string ADM_TelefonoDestinatario
        {
            get { return _aDM_TelefonoDestinatario; }
            set
            {
                if (_aDM_TelefonoDestinatario != value)
                {
                    _aDM_TelefonoDestinatario = value;
                    OnPropertyChanged("ADM_TelefonoDestinatario");
                }
            }
        }
        private string _aDM_TelefonoDestinatario;
    
        [DataMember]
        public string ADM_DireccionDestinatario
        {
            get { return _aDM_DireccionDestinatario; }
            set
            {
                if (_aDM_DireccionDestinatario != value)
                {
                    _aDM_DireccionDestinatario = value;
                    OnPropertyChanged("ADM_DireccionDestinatario");
                }
            }
        }
        private string _aDM_DireccionDestinatario;
    
        [DataMember]
        public string ADM_TipoCliente
        {
            get { return _aDM_TipoCliente; }
            set
            {
                if (_aDM_TipoCliente != value)
                {
                    _aDM_TipoCliente = value;
                    OnPropertyChanged("ADM_TipoCliente");
                }
            }
        }
        private string _aDM_TipoCliente;
    
        [DataMember]
        public short ADM_DiasDeEntrega
        {
            get { return _aDM_DiasDeEntrega; }
            set
            {
                if (_aDM_DiasDeEntrega != value)
                {
                    _aDM_DiasDeEntrega = value;
                    OnPropertyChanged("ADM_DiasDeEntrega");
                }
            }
        }
        private short _aDM_DiasDeEntrega;
    
        [DataMember]
        public System.DateTime ADM_FechaEstimadaEntrega
        {
            get { return _aDM_FechaEstimadaEntrega; }
            set
            {
                if (_aDM_FechaEstimadaEntrega != value)
                {
                    _aDM_FechaEstimadaEntrega = value;
                    OnPropertyChanged("ADM_FechaEstimadaEntrega");
                }
            }
        }
        private System.DateTime _aDM_FechaEstimadaEntrega;
    
        [DataMember]
        public decimal ADM_ValorAdmision
        {
            get { return _aDM_ValorAdmision; }
            set
            {
                if (_aDM_ValorAdmision != value)
                {
                    _aDM_ValorAdmision = value;
                    OnPropertyChanged("ADM_ValorAdmision");
                }
            }
        }
        private decimal _aDM_ValorAdmision;
    
        [DataMember]
        public decimal ADM_ValorTotal
        {
            get { return _aDM_ValorTotal; }
            set
            {
                if (_aDM_ValorTotal != value)
                {
                    _aDM_ValorTotal = value;
                    OnPropertyChanged("ADM_ValorTotal");
                }
            }
        }
        private decimal _aDM_ValorTotal;
    
        [DataMember]
        public decimal ADM_ValorTotalImpuestos
        {
            get { return _aDM_ValorTotalImpuestos; }
            set
            {
                if (_aDM_ValorTotalImpuestos != value)
                {
                    _aDM_ValorTotalImpuestos = value;
                    OnPropertyChanged("ADM_ValorTotalImpuestos");
                }
            }
        }
        private decimal _aDM_ValorTotalImpuestos;
    
        [DataMember]
        public decimal ADM_ValorTotalRetenciones
        {
            get { return _aDM_ValorTotalRetenciones; }
            set
            {
                if (_aDM_ValorTotalRetenciones != value)
                {
                    _aDM_ValorTotalRetenciones = value;
                    OnPropertyChanged("ADM_ValorTotalRetenciones");
                }
            }
        }
        private decimal _aDM_ValorTotalRetenciones;
    
        [DataMember]
        public decimal ADM_ValorPrimaSeguro
        {
            get { return _aDM_ValorPrimaSeguro; }
            set
            {
                if (_aDM_ValorPrimaSeguro != value)
                {
                    _aDM_ValorPrimaSeguro = value;
                    OnPropertyChanged("ADM_ValorPrimaSeguro");
                }
            }
        }
        private decimal _aDM_ValorPrimaSeguro;
    
        [DataMember]
        public decimal ADM_ValorEmpaque
        {
            get { return _aDM_ValorEmpaque; }
            set
            {
                if (_aDM_ValorEmpaque != value)
                {
                    _aDM_ValorEmpaque = value;
                    OnPropertyChanged("ADM_ValorEmpaque");
                }
            }
        }
        private decimal _aDM_ValorEmpaque;
    
        [DataMember]
        public decimal ADM_ValorAdicionales
        {
            get { return _aDM_ValorAdicionales; }
            set
            {
                if (_aDM_ValorAdicionales != value)
                {
                    _aDM_ValorAdicionales = value;
                    OnPropertyChanged("ADM_ValorAdicionales");
                }
            }
        }
        private decimal _aDM_ValorAdicionales;
    
        [DataMember]
        public decimal ADM_ValorDeclarado
        {
            get { return _aDM_ValorDeclarado; }
            set
            {
                if (_aDM_ValorDeclarado != value)
                {
                    _aDM_ValorDeclarado = value;
                    OnPropertyChanged("ADM_ValorDeclarado");
                }
            }
        }
        private decimal _aDM_ValorDeclarado;
    
        [DataMember]
        public string ADM_DiceContener
        {
            get { return _aDM_DiceContener; }
            set
            {
                if (_aDM_DiceContener != value)
                {
                    _aDM_DiceContener = value;
                    OnPropertyChanged("ADM_DiceContener");
                }
            }
        }
        private string _aDM_DiceContener;
    
        [DataMember]
        public string ADM_Observaciones
        {
            get { return _aDM_Observaciones; }
            set
            {
                if (_aDM_Observaciones != value)
                {
                    _aDM_Observaciones = value;
                    OnPropertyChanged("ADM_Observaciones");
                }
            }
        }
        private string _aDM_Observaciones;
    
        [DataMember]
        public short ADM_NumeroPieza
        {
            get { return _aDM_NumeroPieza; }
            set
            {
                if (_aDM_NumeroPieza != value)
                {
                    _aDM_NumeroPieza = value;
                    OnPropertyChanged("ADM_NumeroPieza");
                }
            }
        }
        private short _aDM_NumeroPieza;
    
        [DataMember]
        public short ADM_TotalPiezas
        {
            get { return _aDM_TotalPiezas; }
            set
            {
                if (_aDM_TotalPiezas != value)
                {
                    _aDM_TotalPiezas = value;
                    OnPropertyChanged("ADM_TotalPiezas");
                }
            }
        }
        private short _aDM_TotalPiezas;
    
        [DataMember]
        public System.DateTime ADM_FechaAdmision
        {
            get { return _aDM_FechaAdmision; }
            set
            {
                if (_aDM_FechaAdmision != value)
                {
                    _aDM_FechaAdmision = value;
                    OnPropertyChanged("ADM_FechaAdmision");
                }
            }
        }
        private System.DateTime _aDM_FechaAdmision;
    
        [DataMember]
        public decimal ADM_Peso
        {
            get { return _aDM_Peso; }
            set
            {
                if (_aDM_Peso != value)
                {
                    _aDM_Peso = value;
                    OnPropertyChanged("ADM_Peso");
                }
            }
        }
        private decimal _aDM_Peso;
    
        [DataMember]
        public decimal ADM_PesoLiqVolumetrico
        {
            get { return _aDM_PesoLiqVolumetrico; }
            set
            {
                if (_aDM_PesoLiqVolumetrico != value)
                {
                    _aDM_PesoLiqVolumetrico = value;
                    OnPropertyChanged("ADM_PesoLiqVolumetrico");
                }
            }
        }
        private decimal _aDM_PesoLiqVolumetrico;
    
        [DataMember]
        public decimal ADM_PesoLiqMasa
        {
            get { return _aDM_PesoLiqMasa; }
            set
            {
                if (_aDM_PesoLiqMasa != value)
                {
                    _aDM_PesoLiqMasa = value;
                    OnPropertyChanged("ADM_PesoLiqMasa");
                }
            }
        }
        private decimal _aDM_PesoLiqMasa;
    
        [DataMember]
        public bool ADM_EsPesoVolumetrico
        {
            get { return _aDM_EsPesoVolumetrico; }
            set
            {
                if (_aDM_EsPesoVolumetrico != value)
                {
                    _aDM_EsPesoVolumetrico = value;
                    OnPropertyChanged("ADM_EsPesoVolumetrico");
                }
            }
        }
        private bool _aDM_EsPesoVolumetrico;
    
        [DataMember]
        public string ADM_NumeroBolsaSeguridad
        {
            get { return _aDM_NumeroBolsaSeguridad; }
            set
            {
                if (_aDM_NumeroBolsaSeguridad != value)
                {
                    _aDM_NumeroBolsaSeguridad = value;
                    OnPropertyChanged("ADM_NumeroBolsaSeguridad");
                }
            }
        }
        private string _aDM_NumeroBolsaSeguridad;
    
        [DataMember]
        public Nullable<short> ADM_IdMotivoNoUsoBolsaSegurida
        {
            get { return _aDM_IdMotivoNoUsoBolsaSegurida; }
            set
            {
                if (_aDM_IdMotivoNoUsoBolsaSegurida != value)
                {
                    _aDM_IdMotivoNoUsoBolsaSegurida = value;
                    OnPropertyChanged("ADM_IdMotivoNoUsoBolsaSegurida");
                }
            }
        }
        private Nullable<short> _aDM_IdMotivoNoUsoBolsaSegurida;
    
        [DataMember]
        public string ADM_MotivoNoUsoBolsaSeguriDesc
        {
            get { return _aDM_MotivoNoUsoBolsaSeguriDesc; }
            set
            {
                if (_aDM_MotivoNoUsoBolsaSeguriDesc != value)
                {
                    _aDM_MotivoNoUsoBolsaSeguriDesc = value;
                    OnPropertyChanged("ADM_MotivoNoUsoBolsaSeguriDesc");
                }
            }
        }
        private string _aDM_MotivoNoUsoBolsaSeguriDesc;
    
        [DataMember]
        public string ADM_NoUsoaBolsaSeguridadObserv
        {
            get { return _aDM_NoUsoaBolsaSeguridadObserv; }
            set
            {
                if (_aDM_NoUsoaBolsaSeguridadObserv != value)
                {
                    _aDM_NoUsoaBolsaSeguridadObserv = value;
                    OnPropertyChanged("ADM_NoUsoaBolsaSeguridadObserv");
                }
            }
        }
        private string _aDM_NoUsoaBolsaSeguridadObserv;
    
        [DataMember]
        public string ADM_IdUnidadMedida
        {
            get { return _aDM_IdUnidadMedida; }
            set
            {
                if (_aDM_IdUnidadMedida != value)
                {
                    _aDM_IdUnidadMedida = value;
                    OnPropertyChanged("ADM_IdUnidadMedida");
                }
            }
        }
        private string _aDM_IdUnidadMedida;
    
        [DataMember]
        public decimal ADM_Largo
        {
            get { return _aDM_Largo; }
            set
            {
                if (_aDM_Largo != value)
                {
                    _aDM_Largo = value;
                    OnPropertyChanged("ADM_Largo");
                }
            }
        }
        private decimal _aDM_Largo;
    
        [DataMember]
        public decimal ADM_Ancho
        {
            get { return _aDM_Ancho; }
            set
            {
                if (_aDM_Ancho != value)
                {
                    _aDM_Ancho = value;
                    OnPropertyChanged("ADM_Ancho");
                }
            }
        }
        private decimal _aDM_Ancho;
    
        [DataMember]
        public decimal ADM_Alto
        {
            get { return _aDM_Alto; }
            set
            {
                if (_aDM_Alto != value)
                {
                    _aDM_Alto = value;
                    OnPropertyChanged("ADM_Alto");
                }
            }
        }
        private decimal _aDM_Alto;
    
        [DataMember]
        public bool ADM_EsRecomendado
        {
            get { return _aDM_EsRecomendado; }
            set
            {
                if (_aDM_EsRecomendado != value)
                {
                    _aDM_EsRecomendado = value;
                    OnPropertyChanged("ADM_EsRecomendado");
                }
            }
        }
        private bool _aDM_EsRecomendado;
    
        [DataMember]
        public short ADM_IdTipoEnvio
        {
            get { return _aDM_IdTipoEnvio; }
            set
            {
                if (_aDM_IdTipoEnvio != value)
                {
                    _aDM_IdTipoEnvio = value;
                    OnPropertyChanged("ADM_IdTipoEnvio");
                }
            }
        }
        private short _aDM_IdTipoEnvio;
    
        [DataMember]
        public string ADM_NombreTipoEnvio
        {
            get { return _aDM_NombreTipoEnvio; }
            set
            {
                if (_aDM_NombreTipoEnvio != value)
                {
                    _aDM_NombreTipoEnvio = value;
                    OnPropertyChanged("ADM_NombreTipoEnvio");
                }
            }
        }
        private string _aDM_NombreTipoEnvio;
    
        [DataMember]
        public bool ADM_AdmisionSistemaMensajero
        {
            get { return _aDM_AdmisionSistemaMensajero; }
            set
            {
                if (_aDM_AdmisionSistemaMensajero != value)
                {
                    _aDM_AdmisionSistemaMensajero = value;
                    OnPropertyChanged("ADM_AdmisionSistemaMensajero");
                }
            }
        }
        private bool _aDM_AdmisionSistemaMensajero;
    
        [DataMember]
        public bool ADM_EsAlCobro
        {
            get { return _aDM_EsAlCobro; }
            set
            {
                if (_aDM_EsAlCobro != value)
                {
                    _aDM_EsAlCobro = value;
                    OnPropertyChanged("ADM_EsAlCobro");
                }
            }
        }
        private bool _aDM_EsAlCobro;
    
        [DataMember]
        public bool ADM_EstaPagada
        {
            get { return _aDM_EstaPagada; }
            set
            {
                if (_aDM_EstaPagada != value)
                {
                    _aDM_EstaPagada = value;
                    OnPropertyChanged("ADM_EstaPagada");
                }
            }
        }
        private bool _aDM_EstaPagada;
    
        [DataMember]
        public System.DateTime ADM_FechaPago
        {
            get { return _aDM_FechaPago; }
            set
            {
                if (_aDM_FechaPago != value)
                {
                    _aDM_FechaPago = value;
                    OnPropertyChanged("ADM_FechaPago");
                }
            }
        }
        private System.DateTime _aDM_FechaPago;
    
        [DataMember]
        public string ADM_IdTipoIdentificacionRemitente
        {
            get { return _aDM_IdTipoIdentificacionRemitente; }
            set
            {
                if (_aDM_IdTipoIdentificacionRemitente != value)
                {
                    _aDM_IdTipoIdentificacionRemitente = value;
                    OnPropertyChanged("ADM_IdTipoIdentificacionRemitente");
                }
            }
        }
        private string _aDM_IdTipoIdentificacionRemitente;
    
        [DataMember]
        public string ADM_IdRemitente
        {
            get { return _aDM_IdRemitente; }
            set
            {
                if (_aDM_IdRemitente != value)
                {
                    _aDM_IdRemitente = value;
                    OnPropertyChanged("ADM_IdRemitente");
                }
            }
        }
        private string _aDM_IdRemitente;
    
        [DataMember]
        public string ADM_NombreRemitente
        {
            get { return _aDM_NombreRemitente; }
            set
            {
                if (_aDM_NombreRemitente != value)
                {
                    _aDM_NombreRemitente = value;
                    OnPropertyChanged("ADM_NombreRemitente");
                }
            }
        }
        private string _aDM_NombreRemitente;
    
        [DataMember]
        public string ADM_TelefonoRemitente
        {
            get { return _aDM_TelefonoRemitente; }
            set
            {
                if (_aDM_TelefonoRemitente != value)
                {
                    _aDM_TelefonoRemitente = value;
                    OnPropertyChanged("ADM_TelefonoRemitente");
                }
            }
        }
        private string _aDM_TelefonoRemitente;
    
        [DataMember]
        public string ADM_DireccionRemitente
        {
            get { return _aDM_DireccionRemitente; }
            set
            {
                if (_aDM_DireccionRemitente != value)
                {
                    _aDM_DireccionRemitente = value;
                    OnPropertyChanged("ADM_DireccionRemitente");
                }
            }
        }
        private string _aDM_DireccionRemitente;
    
        [DataMember]
        public string ADM_IdTipoIdentificacionDestinatario
        {
            get { return _aDM_IdTipoIdentificacionDestinatario; }
            set
            {
                if (_aDM_IdTipoIdentificacionDestinatario != value)
                {
                    _aDM_IdTipoIdentificacionDestinatario = value;
                    OnPropertyChanged("ADM_IdTipoIdentificacionDestinatario");
                }
            }
        }
        private string _aDM_IdTipoIdentificacionDestinatario;
    
        [DataMember]
        public string ADM_IdDestinatario
        {
            get { return _aDM_IdDestinatario; }
            set
            {
                if (_aDM_IdDestinatario != value)
                {
                    _aDM_IdDestinatario = value;
                    OnPropertyChanged("ADM_IdDestinatario");
                }
            }
        }
        private string _aDM_IdDestinatario;
    
        [DataMember]
        public string ADM_NombreDestinatario
        {
            get { return _aDM_NombreDestinatario; }
            set
            {
                if (_aDM_NombreDestinatario != value)
                {
                    _aDM_NombreDestinatario = value;
                    OnPropertyChanged("ADM_NombreDestinatario");
                }
            }
        }
        private string _aDM_NombreDestinatario;
    
        [DataMember]
        public long ADM_IdMensajero
        {
            get { return _aDM_IdMensajero; }
            set
            {
                if (_aDM_IdMensajero != value)
                {
                    _aDM_IdMensajero = value;
                    OnPropertyChanged("ADM_IdMensajero");
                }
            }
        }
        private long _aDM_IdMensajero;
    
        [DataMember]
        public string ADM_NombreMensajero
        {
            get { return _aDM_NombreMensajero; }
            set
            {
                if (_aDM_NombreMensajero != value)
                {
                    _aDM_NombreMensajero = value;
                    OnPropertyChanged("ADM_NombreMensajero");
                }
            }
        }
        private string _aDM_NombreMensajero;
    
        [DataMember]
        public System.DateTime ADM_FechaGrabacion
        {
            get { return _aDM_FechaGrabacion; }
            set
            {
                if (_aDM_FechaGrabacion != value)
                {
                    _aDM_FechaGrabacion = value;
                    OnPropertyChanged("ADM_FechaGrabacion");
                }
            }
        }
        private System.DateTime _aDM_FechaGrabacion;
    
        [DataMember]
        public string ADM_CreadoPor
        {
            get { return _aDM_CreadoPor; }
            set
            {
                if (_aDM_CreadoPor != value)
                {
                    _aDM_CreadoPor = value;
                    OnPropertyChanged("ADM_CreadoPor");
                }
            }
        }
        private string _aDM_CreadoPor;
    
        [DataMember]
        public bool ADM_EsSupervisada
        {
            get { return _aDM_EsSupervisada; }
            set
            {
                if (_aDM_EsSupervisada != value)
                {
                    _aDM_EsSupervisada = value;
                    OnPropertyChanged("ADM_EsSupervisada");
                }
            }
        }
        private bool _aDM_EsSupervisada;
    
        [DataMember]
        public System.DateTime ADM_FechaSupervision
        {
            get { return _aDM_FechaSupervision; }
            set
            {
                if (_aDM_FechaSupervision != value)
                {
                    _aDM_FechaSupervision = value;
                    OnPropertyChanged("ADM_FechaSupervision");
                }
            }
        }
        private System.DateTime _aDM_FechaSupervision;
    
        [DataMember]
        public string ADM_EmailRemitente
        {
            get { return _aDM_EmailRemitente; }
            set
            {
                if (_aDM_EmailRemitente != value)
                {
                    _aDM_EmailRemitente = value;
                    OnPropertyChanged("ADM_EmailRemitente");
                }
            }
        }
        private string _aDM_EmailRemitente;
    
        [DataMember]
        public string ADM_EmailDestinatario
        {
            get { return _aDM_EmailDestinatario; }
            set
            {
                if (_aDM_EmailDestinatario != value)
                {
                    _aDM_EmailDestinatario = value;
                    OnPropertyChanged("ADM_EmailDestinatario");
                }
            }
        }
        private string _aDM_EmailDestinatario;
    
        [DataMember]
        public int ADM_CantidadReintentosEntrega
        {
            get { return _aDM_CantidadReintentosEntrega; }
            set
            {
                if (_aDM_CantidadReintentosEntrega != value)
                {
                    _aDM_CantidadReintentosEntrega = value;
                    OnPropertyChanged("ADM_CantidadReintentosEntrega");
                }
            }
        }
        private int _aDM_CantidadReintentosEntrega;
    
        [DataMember]
        public Nullable<bool> ADM_NotificarEntregaPorEmail
        {
            get { return _aDM_NotificarEntregaPorEmail; }
            set
            {
                if (_aDM_NotificarEntregaPorEmail != value)
                {
                    _aDM_NotificarEntregaPorEmail = value;
                    OnPropertyChanged("ADM_NotificarEntregaPorEmail");
                }
            }
        }
        private Nullable<bool> _aDM_NotificarEntregaPorEmail;
    
        [DataMember]
        public long ADM_IdEstadoGuiaLog
        {
            get { return _aDM_IdEstadoGuiaLog; }
            set
            {
                if (_aDM_IdEstadoGuiaLog != value)
                {
                    _aDM_IdEstadoGuiaLog = value;
                    OnPropertyChanged("ADM_IdEstadoGuiaLog");
                }
            }
        }
        private long _aDM_IdEstadoGuiaLog;
    
        [DataMember]
        public bool ADM_EstaEntregada
        {
            get { return _aDM_EstaEntregada; }
            set
            {
                if (_aDM_EstaEntregada != value)
                {
                    _aDM_EstaEntregada = value;
                    OnPropertyChanged("ADM_EstaEntregada");
                }
            }
        }
        private bool _aDM_EstaEntregada;
    
        [DataMember]
        public System.DateTime ADM_FechaEntrega
        {
            get { return _aDM_FechaEntrega; }
            set
            {
                if (_aDM_FechaEntrega != value)
                {
                    _aDM_FechaEntrega = value;
                    OnPropertyChanged("ADM_FechaEntrega");
                }
            }
        }
        private System.DateTime _aDM_FechaEntrega;
    
        [DataMember]
        public long ADM_IdEstadoGuiaLogGestion
        {
            get { return _aDM_IdEstadoGuiaLogGestion; }
            set
            {
                if (_aDM_IdEstadoGuiaLogGestion != value)
                {
                    _aDM_IdEstadoGuiaLogGestion = value;
                    OnPropertyChanged("ADM_IdEstadoGuiaLogGestion");
                }
            }
        }
        private long _aDM_IdEstadoGuiaLogGestion;
    
        [DataMember]
        public string ADM_NoPedido
        {
            get { return _aDM_NoPedido; }
            set
            {
                if (_aDM_NoPedido != value)
                {
                    _aDM_NoPedido = value;
                    OnPropertyChanged("ADM_NoPedido");
                }
            }
        }
        private string _aDM_NoPedido;
    
        [DataMember]
        public Nullable<short> ADM_IdEstadoGuia
        {
            get { return _aDM_IdEstadoGuia; }
            set
            {
                if (_aDM_IdEstadoGuia != value)
                {
                    _aDM_IdEstadoGuia = value;
                    OnPropertyChanged("ADM_IdEstadoGuia");
                }
            }
        }
        private Nullable<short> _aDM_IdEstadoGuia;
    
        [DataMember]
        public string ADM_DescripcionEstado
        {
            get { return _aDM_DescripcionEstado; }
            set
            {
                if (_aDM_DescripcionEstado != value)
                {
                    _aDM_DescripcionEstado = value;
                    OnPropertyChanged("ADM_DescripcionEstado");
                }
            }
        }
        private string _aDM_DescripcionEstado;
    
        [DataMember]
        public string ADM_IdLocalidadEstado
        {
            get { return _aDM_IdLocalidadEstado; }
            set
            {
                if (_aDM_IdLocalidadEstado != value)
                {
                    _aDM_IdLocalidadEstado = value;
                    OnPropertyChanged("ADM_IdLocalidadEstado");
                }
            }
        }
        private string _aDM_IdLocalidadEstado;
    
        [DataMember]
        public string ADM_NombreLocalidadEstado
        {
            get { return _aDM_NombreLocalidadEstado; }
            set
            {
                if (_aDM_NombreLocalidadEstado != value)
                {
                    _aDM_NombreLocalidadEstado = value;
                    OnPropertyChanged("ADM_NombreLocalidadEstado");
                }
            }
        }
        private string _aDM_NombreLocalidadEstado;
    
        [DataMember]
        public Nullable<System.DateTime> ADM_FechaGrabacionEstado
        {
            get { return _aDM_FechaGrabacionEstado; }
            set
            {
                if (_aDM_FechaGrabacionEstado != value)
                {
                    _aDM_FechaGrabacionEstado = value;
                    OnPropertyChanged("ADM_FechaGrabacionEstado");
                }
            }
        }
        private Nullable<System.DateTime> _aDM_FechaGrabacionEstado;
    
        [DataMember]
        public Nullable<System.DateTime> ADM_FechaEstimadaEntregaNew
        {
            get { return _aDM_FechaEstimadaEntregaNew; }
            set
            {
                if (_aDM_FechaEstimadaEntregaNew != value)
                {
                    _aDM_FechaEstimadaEntregaNew = value;
                    OnPropertyChanged("ADM_FechaEstimadaEntregaNew");
                }
            }
        }
        private Nullable<System.DateTime> _aDM_FechaEstimadaEntregaNew;
    
        [DataMember]
        public Nullable<long> ADM_IdCentroServicioEstado
        {
            get { return _aDM_IdCentroServicioEstado; }
            set
            {
                if (_aDM_IdCentroServicioEstado != value)
                {
                    _aDM_IdCentroServicioEstado = value;
                    OnPropertyChanged("ADM_IdCentroServicioEstado");
                }
            }
        }
        private Nullable<long> _aDM_IdCentroServicioEstado;
    
        [DataMember]
        public string ADM_NombreCentroServicioEstado
        {
            get { return _aDM_NombreCentroServicioEstado; }
            set
            {
                if (_aDM_NombreCentroServicioEstado != value)
                {
                    _aDM_NombreCentroServicioEstado = value;
                    OnPropertyChanged("ADM_NombreCentroServicioEstado");
                }
            }
        }
        private string _aDM_NombreCentroServicioEstado;
    
        [DataMember]
        public Nullable<long> ADM_IdMovimientoInventario
        {
            get { return _aDM_IdMovimientoInventario; }
            set
            {
                if (_aDM_IdMovimientoInventario != value)
                {
                    _aDM_IdMovimientoInventario = value;
                    OnPropertyChanged("ADM_IdMovimientoInventario");
                }
            }
        }
        private Nullable<long> _aDM_IdMovimientoInventario;
    
        [DataMember]
        public Nullable<bool> ADM_Impresa
        {
            get { return _aDM_Impresa; }
            set
            {
                if (_aDM_Impresa != value)
                {
                    _aDM_Impresa = value;
                    OnPropertyChanged("ADM_Impresa");
                }
            }
        }
        private Nullable<bool> _aDM_Impresa;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN> AdminisionMensajeriaGuiaRelacion_MEN
        {
            get
            {
                if (_adminisionMensajeriaGuiaRelacion_MEN == null)
                {
                    _adminisionMensajeriaGuiaRelacion_MEN = new TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN>();
                    _adminisionMensajeriaGuiaRelacion_MEN.CollectionChanged += FixupAdminisionMensajeriaGuiaRelacion_MEN;
                }
                return _adminisionMensajeriaGuiaRelacion_MEN;
            }
            set
            {
                if (!ReferenceEquals(_adminisionMensajeriaGuiaRelacion_MEN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_adminisionMensajeriaGuiaRelacion_MEN != null)
                    {
                        _adminisionMensajeriaGuiaRelacion_MEN.CollectionChanged -= FixupAdminisionMensajeriaGuiaRelacion_MEN;
                    }
                    _adminisionMensajeriaGuiaRelacion_MEN = value;
                    if (_adminisionMensajeriaGuiaRelacion_MEN != null)
                    {
                        _adminisionMensajeriaGuiaRelacion_MEN.CollectionChanged += FixupAdminisionMensajeriaGuiaRelacion_MEN;
                    }
                    OnNavigationPropertyChanged("AdminisionMensajeriaGuiaRelacion_MEN");
                }
            }
        }
        private TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN> _adminisionMensajeriaGuiaRelacion_MEN;
    
        [DataMember]
        public TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN> AdminisionMensajeriaGuiaRelacion_MEN1
        {
            get
            {
                if (_adminisionMensajeriaGuiaRelacion_MEN1 == null)
                {
                    _adminisionMensajeriaGuiaRelacion_MEN1 = new TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN>();
                    _adminisionMensajeriaGuiaRelacion_MEN1.CollectionChanged += FixupAdminisionMensajeriaGuiaRelacion_MEN1;
                }
                return _adminisionMensajeriaGuiaRelacion_MEN1;
            }
            set
            {
                if (!ReferenceEquals(_adminisionMensajeriaGuiaRelacion_MEN1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_adminisionMensajeriaGuiaRelacion_MEN1 != null)
                    {
                        _adminisionMensajeriaGuiaRelacion_MEN1.CollectionChanged -= FixupAdminisionMensajeriaGuiaRelacion_MEN1;
                    }
                    _adminisionMensajeriaGuiaRelacion_MEN1 = value;
                    if (_adminisionMensajeriaGuiaRelacion_MEN1 != null)
                    {
                        _adminisionMensajeriaGuiaRelacion_MEN1.CollectionChanged += FixupAdminisionMensajeriaGuiaRelacion_MEN1;
                    }
                    OnNavigationPropertyChanged("AdminisionMensajeriaGuiaRelacion_MEN1");
                }
            }
        }
        private TrackableCollection<AdminisionMensajeriaGuiaRelacion_MEN> _adminisionMensajeriaGuiaRelacion_MEN1;
    
        [DataMember]
        public AdmisionNotificaciones_MEN AdmisionNotificaciones_MEN
        {
            get { return _admisionNotificaciones_MEN; }
            set
            {
                if (!ReferenceEquals(_admisionNotificaciones_MEN, value))
                {
                    var previousValue = _admisionNotificaciones_MEN;
                    _admisionNotificaciones_MEN = value;
                    FixupAdmisionNotificaciones_MEN(previousValue);
                    OnNavigationPropertyChanged("AdmisionNotificaciones_MEN");
                }
            }
        }
        private AdmisionNotificaciones_MEN _admisionNotificaciones_MEN;
    
        [DataMember]
        public TrackableCollection<AdmisionRotulos_MEN> AdmisionRotulos_MEN
        {
            get
            {
                if (_admisionRotulos_MEN == null)
                {
                    _admisionRotulos_MEN = new TrackableCollection<AdmisionRotulos_MEN>();
                    _admisionRotulos_MEN.CollectionChanged += FixupAdmisionRotulos_MEN;
                }
                return _admisionRotulos_MEN;
            }
            set
            {
                if (!ReferenceEquals(_admisionRotulos_MEN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_admisionRotulos_MEN != null)
                    {
                        _admisionRotulos_MEN.CollectionChanged -= FixupAdmisionRotulos_MEN;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (AdmisionRotulos_MEN item in _admisionRotulos_MEN)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _admisionRotulos_MEN = value;
                    if (_admisionRotulos_MEN != null)
                    {
                        _admisionRotulos_MEN.CollectionChanged += FixupAdmisionRotulos_MEN;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (AdmisionRotulos_MEN item in _admisionRotulos_MEN)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("AdmisionRotulos_MEN");
                }
            }
        }
        private TrackableCollection<AdmisionRotulos_MEN> _admisionRotulos_MEN;
    
        [DataMember]
        public TrackableCollection<EstadoGuiaTraza_MEN> EstadoGuiaTraza_MEN
        {
            get
            {
                if (_estadoGuiaTraza_MEN == null)
                {
                    _estadoGuiaTraza_MEN = new TrackableCollection<EstadoGuiaTraza_MEN>();
                    _estadoGuiaTraza_MEN.CollectionChanged += FixupEstadoGuiaTraza_MEN;
                }
                return _estadoGuiaTraza_MEN;
            }
            set
            {
                if (!ReferenceEquals(_estadoGuiaTraza_MEN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_estadoGuiaTraza_MEN != null)
                    {
                        _estadoGuiaTraza_MEN.CollectionChanged -= FixupEstadoGuiaTraza_MEN;
                    }
                    _estadoGuiaTraza_MEN = value;
                    if (_estadoGuiaTraza_MEN != null)
                    {
                        _estadoGuiaTraza_MEN.CollectionChanged += FixupEstadoGuiaTraza_MEN;
                    }
                    OnNavigationPropertyChanged("EstadoGuiaTraza_MEN");
                }
            }
        }
        private TrackableCollection<EstadoGuiaTraza_MEN> _estadoGuiaTraza_MEN;
    
        [DataMember]
        public MensajeriaConvenioConvenio_MEN MensajeriaConvenioConvenio_MEN
        {
            get { return _mensajeriaConvenioConvenio_MEN; }
            set
            {
                if (!ReferenceEquals(_mensajeriaConvenioConvenio_MEN, value))
                {
                    var previousValue = _mensajeriaConvenioConvenio_MEN;
                    _mensajeriaConvenioConvenio_MEN = value;
                    FixupMensajeriaConvenioConvenio_MEN(previousValue);
                    OnNavigationPropertyChanged("MensajeriaConvenioConvenio_MEN");
                }
            }
        }
        private MensajeriaConvenioConvenio_MEN _mensajeriaConvenioConvenio_MEN;
    
        [DataMember]
        public MensajeriaConvenioPeaton_MEN MensajeriaConvenioPeaton_MEN
        {
            get { return _mensajeriaConvenioPeaton_MEN; }
            set
            {
                if (!ReferenceEquals(_mensajeriaConvenioPeaton_MEN, value))
                {
                    var previousValue = _mensajeriaConvenioPeaton_MEN;
                    _mensajeriaConvenioPeaton_MEN = value;
                    FixupMensajeriaConvenioPeaton_MEN(previousValue);
                    OnNavigationPropertyChanged("MensajeriaConvenioPeaton_MEN");
                }
            }
        }
        private MensajeriaConvenioPeaton_MEN _mensajeriaConvenioPeaton_MEN;
    
        [DataMember]
        public TrackableCollection<OrdenServicioMasivoGuia_MEN> OrdenServicioMasivoGuia_MEN
        {
            get
            {
                if (_ordenServicioMasivoGuia_MEN == null)
                {
                    _ordenServicioMasivoGuia_MEN = new TrackableCollection<OrdenServicioMasivoGuia_MEN>();
                    _ordenServicioMasivoGuia_MEN.CollectionChanged += FixupOrdenServicioMasivoGuia_MEN;
                }
                return _ordenServicioMasivoGuia_MEN;
            }
            set
            {
                if (!ReferenceEquals(_ordenServicioMasivoGuia_MEN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_ordenServicioMasivoGuia_MEN != null)
                    {
                        _ordenServicioMasivoGuia_MEN.CollectionChanged -= FixupOrdenServicioMasivoGuia_MEN;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (OrdenServicioMasivoGuia_MEN item in _ordenServicioMasivoGuia_MEN)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _ordenServicioMasivoGuia_MEN = value;
                    if (_ordenServicioMasivoGuia_MEN != null)
                    {
                        _ordenServicioMasivoGuia_MEN.CollectionChanged += FixupOrdenServicioMasivoGuia_MEN;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (OrdenServicioMasivoGuia_MEN item in _ordenServicioMasivoGuia_MEN)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("OrdenServicioMasivoGuia_MEN");
                }
            }
        }
        private TrackableCollection<OrdenServicioMasivoGuia_MEN> _ordenServicioMasivoGuia_MEN;
    
        [DataMember]
        public RecibidoGuia_LOI RecibidoGuia_LOI
        {
            get { return _recibidoGuia_LOI; }
            set
            {
                if (!ReferenceEquals(_recibidoGuia_LOI, value))
                {
                    var previousValue = _recibidoGuia_LOI;
                    _recibidoGuia_LOI = value;
                    FixupRecibidoGuia_LOI(previousValue);
                    OnNavigationPropertyChanged("RecibidoGuia_LOI");
                }
            }
        }
        private RecibidoGuia_LOI _recibidoGuia_LOI;
    
        [DataMember]
        public TrackableCollection<AlmacenGuia_LOI> AlmacenGuia_LOI
        {
            get
            {
                if (_almacenGuia_LOI == null)
                {
                    _almacenGuia_LOI = new TrackableCollection<AlmacenGuia_LOI>();
                    _almacenGuia_LOI.CollectionChanged += FixupAlmacenGuia_LOI;
                }
                return _almacenGuia_LOI;
            }
            set
            {
                if (!ReferenceEquals(_almacenGuia_LOI, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_almacenGuia_LOI != null)
                    {
                        _almacenGuia_LOI.CollectionChanged -= FixupAlmacenGuia_LOI;
                    }
                    _almacenGuia_LOI = value;
                    if (_almacenGuia_LOI != null)
                    {
                        _almacenGuia_LOI.CollectionChanged += FixupAlmacenGuia_LOI;
                    }
                    OnNavigationPropertyChanged("AlmacenGuia_LOI");
                }
            }
        }
        private TrackableCollection<AlmacenGuia_LOI> _almacenGuia_LOI;
    
        [DataMember]
        public TrackableCollection<NovedadGuia_MEN> NovedadGuia_MEN
        {
            get
            {
                if (_novedadGuia_MEN == null)
                {
                    _novedadGuia_MEN = new TrackableCollection<NovedadGuia_MEN>();
                    _novedadGuia_MEN.CollectionChanged += FixupNovedadGuia_MEN;
                }
                return _novedadGuia_MEN;
            }
            set
            {
                if (!ReferenceEquals(_novedadGuia_MEN, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_novedadGuia_MEN != null)
                    {
                        _novedadGuia_MEN.CollectionChanged -= FixupNovedadGuia_MEN;
                    }
                    _novedadGuia_MEN = value;
                    if (_novedadGuia_MEN != null)
                    {
                        _novedadGuia_MEN.CollectionChanged += FixupNovedadGuia_MEN;
                    }
                    OnNavigationPropertyChanged("NovedadGuia_MEN");
                }
            }
        }
        private TrackableCollection<NovedadGuia_MEN> _novedadGuia_MEN;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            AdminisionMensajeriaGuiaRelacion_MEN.Clear();
            AdminisionMensajeriaGuiaRelacion_MEN1.Clear();
            AdmisionNotificaciones_MEN = null;
            AdmisionRotulos_MEN.Clear();
            EstadoGuiaTraza_MEN.Clear();
            MensajeriaConvenioConvenio_MEN = null;
            MensajeriaConvenioPeaton_MEN = null;
            OrdenServicioMasivoGuia_MEN.Clear();
            RecibidoGuia_LOI = null;
            AlmacenGuia_LOI.Clear();
            NovedadGuia_MEN.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupAdmisionNotificaciones_MEN(AdmisionNotificaciones_MEN previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (AdmisionNotificaciones_MEN != null)
            {
                ChangeTracker.ObjectStateChanging += AdmisionNotificaciones_MEN.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.AdmisionMensajeria_MEN, this))
            {
                previousValue.AdmisionMensajeria_MEN = null;
            }
    
            if (AdmisionNotificaciones_MEN != null)
            {
                AdmisionNotificaciones_MEN.AdmisionMensajeria_MEN = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("AdmisionNotificaciones_MEN")
                    && (ChangeTracker.OriginalValues["AdmisionNotificaciones_MEN"] == AdmisionNotificaciones_MEN))
                {
                    ChangeTracker.OriginalValues.Remove("AdmisionNotificaciones_MEN");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("AdmisionNotificaciones_MEN", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (AdmisionNotificaciones_MEN != null && !AdmisionNotificaciones_MEN.ChangeTracker.ChangeTrackingEnabled)
                {
                    AdmisionNotificaciones_MEN.StartTracking();
                }
            }
        }
    
        private void FixupMensajeriaConvenioConvenio_MEN(MensajeriaConvenioConvenio_MEN previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (MensajeriaConvenioConvenio_MEN != null)
            {
                ChangeTracker.ObjectStateChanging += MensajeriaConvenioConvenio_MEN.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.AdmisionMensajeria_MEN, this))
            {
                previousValue.AdmisionMensajeria_MEN = null;
            }
    
            if (MensajeriaConvenioConvenio_MEN != null)
            {
                MensajeriaConvenioConvenio_MEN.AdmisionMensajeria_MEN = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MensajeriaConvenioConvenio_MEN")
                    && (ChangeTracker.OriginalValues["MensajeriaConvenioConvenio_MEN"] == MensajeriaConvenioConvenio_MEN))
                {
                    ChangeTracker.OriginalValues.Remove("MensajeriaConvenioConvenio_MEN");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MensajeriaConvenioConvenio_MEN", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (MensajeriaConvenioConvenio_MEN != null && !MensajeriaConvenioConvenio_MEN.ChangeTracker.ChangeTrackingEnabled)
                {
                    MensajeriaConvenioConvenio_MEN.StartTracking();
                }
            }
        }
    
        private void FixupMensajeriaConvenioPeaton_MEN(MensajeriaConvenioPeaton_MEN previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (MensajeriaConvenioPeaton_MEN != null)
            {
                ChangeTracker.ObjectStateChanging += MensajeriaConvenioPeaton_MEN.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.AdmisionMensajeria_MEN, this))
            {
                previousValue.AdmisionMensajeria_MEN = null;
            }
    
            if (MensajeriaConvenioPeaton_MEN != null)
            {
                MensajeriaConvenioPeaton_MEN.AdmisionMensajeria_MEN = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MensajeriaConvenioPeaton_MEN")
                    && (ChangeTracker.OriginalValues["MensajeriaConvenioPeaton_MEN"] == MensajeriaConvenioPeaton_MEN))
                {
                    ChangeTracker.OriginalValues.Remove("MensajeriaConvenioPeaton_MEN");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MensajeriaConvenioPeaton_MEN", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (MensajeriaConvenioPeaton_MEN != null && !MensajeriaConvenioPeaton_MEN.ChangeTracker.ChangeTrackingEnabled)
                {
                    MensajeriaConvenioPeaton_MEN.StartTracking();
                }
            }
        }
    
        private void FixupRecibidoGuia_LOI(RecibidoGuia_LOI previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (RecibidoGuia_LOI != null)
            {
                ChangeTracker.ObjectStateChanging += RecibidoGuia_LOI.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.AdmisionMensajeria_MEN, this))
            {
                previousValue.AdmisionMensajeria_MEN = null;
            }
    
            if (RecibidoGuia_LOI != null)
            {
                RecibidoGuia_LOI.AdmisionMensajeria_MEN = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RecibidoGuia_LOI")
                    && (ChangeTracker.OriginalValues["RecibidoGuia_LOI"] == RecibidoGuia_LOI))
                {
                    ChangeTracker.OriginalValues.Remove("RecibidoGuia_LOI");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RecibidoGuia_LOI", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (RecibidoGuia_LOI != null && !RecibidoGuia_LOI.ChangeTracker.ChangeTrackingEnabled)
                {
                    RecibidoGuia_LOI.StartTracking();
                }
            }
        }
    
        private void FixupAdminisionMensajeriaGuiaRelacion_MEN(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (AdminisionMensajeriaGuiaRelacion_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("AdminisionMensajeriaGuiaRelacion_MEN", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AdminisionMensajeriaGuiaRelacion_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("AdminisionMensajeriaGuiaRelacion_MEN", item);
                    }
                }
            }
        }
    
        private void FixupAdminisionMensajeriaGuiaRelacion_MEN1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (AdminisionMensajeriaGuiaRelacion_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN1 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("AdminisionMensajeriaGuiaRelacion_MEN1", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AdminisionMensajeriaGuiaRelacion_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN1, this))
                    {
                        item.AdmisionMensajeria_MEN1 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("AdminisionMensajeriaGuiaRelacion_MEN1", item);
                    }
                }
            }
        }
    
        private void FixupAdmisionRotulos_MEN(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (AdmisionRotulos_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("AdmisionRotulos_MEN", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AdmisionRotulos_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("AdmisionRotulos_MEN", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupEstadoGuiaTraza_MEN(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (EstadoGuiaTraza_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("EstadoGuiaTraza_MEN", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EstadoGuiaTraza_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("EstadoGuiaTraza_MEN", item);
                    }
                }
            }
        }
    
        private void FixupOrdenServicioMasivoGuia_MEN(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (OrdenServicioMasivoGuia_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("OrdenServicioMasivoGuia_MEN", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (OrdenServicioMasivoGuia_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("OrdenServicioMasivoGuia_MEN", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupAlmacenGuia_LOI(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (AlmacenGuia_LOI item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("AlmacenGuia_LOI", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AlmacenGuia_LOI item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("AlmacenGuia_LOI", item);
                    }
                }
            }
        }
    
        private void FixupNovedadGuia_MEN(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (NovedadGuia_MEN item in e.NewItems)
                {
                    item.AdmisionMensajeria_MEN = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("NovedadGuia_MEN", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (NovedadGuia_MEN item in e.OldItems)
                {
                    if (ReferenceEquals(item.AdmisionMensajeria_MEN, this))
                    {
                        item.AdmisionMensajeria_MEN = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("NovedadGuia_MEN", item);
                    }
                }
            }
        }

        #endregion

    }
}
