//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Adminisiones.Mensajeria.Datos.Modelo
{
    
    public partial class paObtenerFormasPagoAdmMen : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long ADM_IdAdminisionMensajeria
        {
            get { return _aDM_IdAdminisionMensajeria; }
            set
            {
                if (_aDM_IdAdminisionMensajeria != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdAdminisionMensajeria = value;
                    OnPropertyChanged("ADM_IdAdminisionMensajeria");
                }
            }
        }
        private long _aDM_IdAdminisionMensajeria;
    
        [DataMember]
        public string ADM_NombrePaisDestino
        {
            get { return _aDM_NombrePaisDestino; }
            set
            {
                if (_aDM_NombrePaisDestino != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombrePaisDestino = value;
                    OnPropertyChanged("ADM_NombrePaisDestino");
                }
            }
        }
        private string _aDM_NombrePaisDestino;
    
        [DataMember]
        public string ADM_NombreCiudadDestino
        {
            get { return _aDM_NombreCiudadDestino; }
            set
            {
                if (_aDM_NombreCiudadDestino != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombreCiudadDestino = value;
                    OnPropertyChanged("ADM_NombreCiudadDestino");
                }
            }
        }
        private string _aDM_NombreCiudadDestino;
    
        [DataMember]
        public decimal ADM_ValorTotal
        {
            get { return _aDM_ValorTotal; }
            set
            {
                if (_aDM_ValorTotal != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorTotal = value;
                    OnPropertyChanged("ADM_ValorTotal");
                }
            }
        }
        private decimal _aDM_ValorTotal;
    
        [DataMember]
        public int ADM_IdServicio
        {
            get { return _aDM_IdServicio; }
            set
            {
                if (_aDM_IdServicio != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdServicio = value;
                    OnPropertyChanged("ADM_IdServicio");
                }
            }
        }
        private int _aDM_IdServicio;
    
        [DataMember]
        public long ADM_NumeroGuia
        {
            get { return _aDM_NumeroGuia; }
            set
            {
                if (_aDM_NumeroGuia != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NumeroGuia = value;
                    OnPropertyChanged("ADM_NumeroGuia");
                }
            }
        }
        private long _aDM_NumeroGuia;
    
        [DataMember]
        public long ADM_IdCentroServicioOrigen
        {
            get { return _aDM_IdCentroServicioOrigen; }
            set
            {
                if (_aDM_IdCentroServicioOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdCentroServicioOrigen = value;
                    OnPropertyChanged("ADM_IdCentroServicioOrigen");
                }
            }
        }
        private long _aDM_IdCentroServicioOrigen;
    
        [DataMember]
        public string ADM_NombreCentroServicioOrigen
        {
            get { return _aDM_NombreCentroServicioOrigen; }
            set
            {
                if (_aDM_NombreCentroServicioOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombreCentroServicioOrigen = value;
                    OnPropertyChanged("ADM_NombreCentroServicioOrigen");
                }
            }
        }
        private string _aDM_NombreCentroServicioOrigen;
    
        [DataMember]
        public string ADM_IdPaisOrigen
        {
            get { return _aDM_IdPaisOrigen; }
            set
            {
                if (_aDM_IdPaisOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdPaisOrigen = value;
                    OnPropertyChanged("ADM_IdPaisOrigen");
                }
            }
        }
        private string _aDM_IdPaisOrigen;
    
        [DataMember]
        public string ADM_NombrePaisOrigen
        {
            get { return _aDM_NombrePaisOrigen; }
            set
            {
                if (_aDM_NombrePaisOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombrePaisOrigen = value;
                    OnPropertyChanged("ADM_NombrePaisOrigen");
                }
            }
        }
        private string _aDM_NombrePaisOrigen;
    
        [DataMember]
        public string ADM_NombreCiudadOrigen
        {
            get { return _aDM_NombreCiudadOrigen; }
            set
            {
                if (_aDM_NombreCiudadOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombreCiudadOrigen = value;
                    OnPropertyChanged("ADM_NombreCiudadOrigen");
                }
            }
        }
        private string _aDM_NombreCiudadOrigen;
    
        [DataMember]
        public string ADM_IdCiudadOrigen
        {
            get { return _aDM_IdCiudadOrigen; }
            set
            {
                if (_aDM_IdCiudadOrigen != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdCiudadOrigen = value;
                    OnPropertyChanged("ADM_IdCiudadOrigen");
                }
            }
        }
        private string _aDM_IdCiudadOrigen;
    
        [DataMember]
        public string ADM_IdCiudadDestino
        {
            get { return _aDM_IdCiudadDestino; }
            set
            {
                if (_aDM_IdCiudadDestino != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdCiudadDestino = value;
                    OnPropertyChanged("ADM_IdCiudadDestino");
                }
            }
        }
        private string _aDM_IdCiudadDestino;
    
        [DataMember]
        public System.DateTime ADM_FechaAdmision
        {
            get { return _aDM_FechaAdmision; }
            set
            {
                if (_aDM_FechaAdmision != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_FechaAdmision = value;
                    OnPropertyChanged("ADM_FechaAdmision");
                }
            }
        }
        private System.DateTime _aDM_FechaAdmision;
    
        [DataMember]
        public decimal ADM_Peso
        {
            get { return _aDM_Peso; }
            set
            {
                if (_aDM_Peso != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_Peso = value;
                    OnPropertyChanged("ADM_Peso");
                }
            }
        }
        private decimal _aDM_Peso;
    
        [DataMember]
        public bool ADM_EsAlCobro
        {
            get { return _aDM_EsAlCobro; }
            set
            {
                if (_aDM_EsAlCobro != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_EsAlCobro = value;
                    OnPropertyChanged("ADM_EsAlCobro");
                }
            }
        }
        private bool _aDM_EsAlCobro;
    
        [DataMember]
        public bool ADM_EsPesoVolumetrico
        {
            get { return _aDM_EsPesoVolumetrico; }
            set
            {
                if (_aDM_EsPesoVolumetrico != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_EsPesoVolumetrico = value;
                    OnPropertyChanged("ADM_EsPesoVolumetrico");
                }
            }
        }
        private bool _aDM_EsPesoVolumetrico;
    
        [DataMember]
        public decimal ADM_ValorDeclarado
        {
            get { return _aDM_ValorDeclarado; }
            set
            {
                if (_aDM_ValorDeclarado != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorDeclarado = value;
                    OnPropertyChanged("ADM_ValorDeclarado");
                }
            }
        }
        private decimal _aDM_ValorDeclarado;
    
        [DataMember]
        public string ADM_TipoCliente
        {
            get { return _aDM_TipoCliente; }
            set
            {
                if (_aDM_TipoCliente != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_TipoCliente = value;
                    OnPropertyChanged("ADM_TipoCliente");
                }
            }
        }
        private string _aDM_TipoCliente;
    
        [DataMember]
        public short AGF_IdFormaPago
        {
            get { return _aGF_IdFormaPago; }
            set
            {
                if (_aGF_IdFormaPago != value)
                {
                    OnComplexPropertyChanging();
                    _aGF_IdFormaPago = value;
                    OnPropertyChanged("AGF_IdFormaPago");
                }
            }
        }
        private short _aGF_IdFormaPago;
    
        [DataMember]
        public string FOP_Descripcion
        {
            get { return _fOP_Descripcion; }
            set
            {
                if (_fOP_Descripcion != value)
                {
                    OnComplexPropertyChanging();
                    _fOP_Descripcion = value;
                    OnPropertyChanged("FOP_Descripcion");
                }
            }
        }
        private string _fOP_Descripcion;
    
        [DataMember]
        public decimal AGF_Valor
        {
            get { return _aGF_Valor; }
            set
            {
                if (_aGF_Valor != value)
                {
                    OnComplexPropertyChanging();
                    _aGF_Valor = value;
                    OnPropertyChanged("AGF_Valor");
                }
            }
        }
        private decimal _aGF_Valor;
    
        [DataMember]
        public bool ADM_EsAutomatico
        {
            get { return _aDM_EsAutomatico; }
            set
            {
                if (_aDM_EsAutomatico != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_EsAutomatico = value;
                    OnPropertyChanged("ADM_EsAutomatico");
                }
            }
        }
        private bool _aDM_EsAutomatico;
    
        [DataMember]
        public long ADM_IdCentroServicioDestino
        {
            get { return _aDM_IdCentroServicioDestino; }
            set
            {
                if (_aDM_IdCentroServicioDestino != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_IdCentroServicioDestino = value;
                    OnPropertyChanged("ADM_IdCentroServicioDestino");
                }
            }
        }
        private long _aDM_IdCentroServicioDestino;
    
        [DataMember]
        public string ADM_NombreCentroServicioDestino
        {
            get { return _aDM_NombreCentroServicioDestino; }
            set
            {
                if (_aDM_NombreCentroServicioDestino != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_NombreCentroServicioDestino = value;
                    OnPropertyChanged("ADM_NombreCentroServicioDestino");
                }
            }
        }
        private string _aDM_NombreCentroServicioDestino;
    
        [DataMember]
        public decimal ADM_ValorAdicionales
        {
            get { return _aDM_ValorAdicionales; }
            set
            {
                if (_aDM_ValorAdicionales != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorAdicionales = value;
                    OnPropertyChanged("ADM_ValorAdicionales");
                }
            }
        }
        private decimal _aDM_ValorAdicionales;
    
        [DataMember]
        public decimal ADM_ValorAdmision
        {
            get { return _aDM_ValorAdmision; }
            set
            {
                if (_aDM_ValorAdmision != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorAdmision = value;
                    OnPropertyChanged("ADM_ValorAdmision");
                }
            }
        }
        private decimal _aDM_ValorAdmision;
    
        [DataMember]
        public decimal ADM_ValorPrimaSeguro
        {
            get { return _aDM_ValorPrimaSeguro; }
            set
            {
                if (_aDM_ValorPrimaSeguro != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorPrimaSeguro = value;
                    OnPropertyChanged("ADM_ValorPrimaSeguro");
                }
            }
        }
        private decimal _aDM_ValorPrimaSeguro;
    
        [DataMember]
        public decimal ADM_ValorTotalImpuestos
        {
            get { return _aDM_ValorTotalImpuestos; }
            set
            {
                if (_aDM_ValorTotalImpuestos != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorTotalImpuestos = value;
                    OnPropertyChanged("ADM_ValorTotalImpuestos");
                }
            }
        }
        private decimal _aDM_ValorTotalImpuestos;
    
        [DataMember]
        public decimal ADM_ValorTotalRetenciones
        {
            get { return _aDM_ValorTotalRetenciones; }
            set
            {
                if (_aDM_ValorTotalRetenciones != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_ValorTotalRetenciones = value;
                    OnPropertyChanged("ADM_ValorTotalRetenciones");
                }
            }
        }
        private decimal _aDM_ValorTotalRetenciones;
    
        [DataMember]
        public bool ADM_EstaPagada
        {
            get { return _aDM_EstaPagada; }
            set
            {
                if (_aDM_EstaPagada != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_EstaPagada = value;
                    OnPropertyChanged("ADM_EstaPagada");
                }
            }
        }
        private bool _aDM_EstaPagada;
    
        [DataMember]
        public bool ADM_EstaEntregada
        {
            get { return _aDM_EstaEntregada; }
            set
            {
                if (_aDM_EstaEntregada != value)
                {
                    OnComplexPropertyChanging();
                    _aDM_EstaEntregada = value;
                    OnPropertyChanged("ADM_EstaEntregada");
                }
            }
        }
        private bool _aDM_EstaEntregada;

        #endregion

        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, paObtenerFormasPagoAdmMen complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdAdminisionMensajeria", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdAdminisionMensajeria);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombrePaisDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombrePaisDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombreCiudadDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombreCiudadDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorTotal", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorTotal);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdServicio", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdServicio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NumeroGuia", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NumeroGuia);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdCentroServicioOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdCentroServicioOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombreCentroServicioOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombreCentroServicioOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdPaisOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdPaisOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombrePaisOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombrePaisOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombreCiudadOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombreCiudadOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdCiudadOrigen", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdCiudadOrigen);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdCiudadDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdCiudadDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_FechaAdmision", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_FechaAdmision);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_Peso", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_Peso);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_EsAlCobro", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_EsAlCobro);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_EsPesoVolumetrico", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_EsPesoVolumetrico);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorDeclarado", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorDeclarado);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_TipoCliente", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_TipoCliente);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AGF_IdFormaPago", parentPropertyName), complexObject == null ? null : (object)complexObject.AGF_IdFormaPago);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.FOP_Descripcion", parentPropertyName), complexObject == null ? null : (object)complexObject.FOP_Descripcion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.AGF_Valor", parentPropertyName), complexObject == null ? null : (object)complexObject.AGF_Valor);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_EsAutomatico", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_EsAutomatico);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_IdCentroServicioDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_IdCentroServicioDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_NombreCentroServicioDestino", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_NombreCentroServicioDestino);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorAdicionales", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorAdicionales);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorAdmision", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorAdmision);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorPrimaSeguro", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorPrimaSeguro);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorTotalImpuestos", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorTotalImpuestos);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_ValorTotalRetenciones", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_ValorTotalRetenciones);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_EstaPagada", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_EstaPagada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ADM_EstaEntregada", parentPropertyName), complexObject == null ? null : (object)complexObject.ADM_EstaEntregada);
        }

        #endregion

    }
}
