//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Framework.Servidor.Mensajeria.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MensajesEnviados_MEN))]
    public partial class AdjuntosMensajes_MEN: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public int ADJ_IdAdjunto
        {
            get { return _aDJ_IdAdjunto; }
            set
            {
                if (_aDJ_IdAdjunto != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'ADJ_IdAdjunto' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _aDJ_IdAdjunto = value;
                    OnPropertyChanged("ADJ_IdAdjunto");
                }
            }
        }
        private int _aDJ_IdAdjunto;
    
        [DataMember]
        public string ADJ_RutaArchivo
        {
            get { return _aDJ_RutaArchivo; }
            set
            {
                if (_aDJ_RutaArchivo != value)
                {
                    _aDJ_RutaArchivo = value;
                    OnPropertyChanged("ADJ_RutaArchivo");
                }
            }
        }
        private string _aDJ_RutaArchivo;
    
        [DataMember]
        public int ADJ_IdMensaje
        {
            get { return _aDJ_IdMensaje; }
            set
            {
                if (_aDJ_IdMensaje != value)
                {
                    ChangeTracker.RecordOriginalValue("ADJ_IdMensaje", _aDJ_IdMensaje);
                    if (!IsDeserializing)
                    {
                        if (MensajesEnviados_MEN != null && MensajesEnviados_MEN.MEN_IdMensaje != value)
                        {
                            MensajesEnviados_MEN = null;
                        }
                    }
                    _aDJ_IdMensaje = value;
                    OnPropertyChanged("ADJ_IdMensaje");
                }
            }
        }
        private int _aDJ_IdMensaje;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public MensajesEnviados_MEN MensajesEnviados_MEN
        {
            get { return _mensajesEnviados_MEN; }
            set
            {
                if (!ReferenceEquals(_mensajesEnviados_MEN, value))
                {
                    var previousValue = _mensajesEnviados_MEN;
                    _mensajesEnviados_MEN = value;
                    FixupMensajesEnviados_MEN(previousValue);
                    OnNavigationPropertyChanged("MensajesEnviados_MEN");
                }
            }
        }
        private MensajesEnviados_MEN _mensajesEnviados_MEN;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            MensajesEnviados_MEN = null;
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupMensajesEnviados_MEN(MensajesEnviados_MEN previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.AdjuntosMensajes_MEN.Contains(this))
            {
                previousValue.AdjuntosMensajes_MEN.Remove(this);
            }
    
            if (MensajesEnviados_MEN != null)
            {
                if (!MensajesEnviados_MEN.AdjuntosMensajes_MEN.Contains(this))
                {
                    MensajesEnviados_MEN.AdjuntosMensajes_MEN.Add(this);
                }
    
                ADJ_IdMensaje = MensajesEnviados_MEN.MEN_IdMensaje;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MensajesEnviados_MEN")
                    && (ChangeTracker.OriginalValues["MensajesEnviados_MEN"] == MensajesEnviados_MEN))
                {
                    ChangeTracker.OriginalValues.Remove("MensajesEnviados_MEN");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MensajesEnviados_MEN", previousValue);
                }
                if (MensajesEnviados_MEN != null && !MensajesEnviados_MEN.ChangeTracker.ChangeTrackingEnabled)
                {
                    MensajesEnviados_MEN.StartTracking();
                }
            }
        }

        #endregion

    }
}
