//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.ParametrosOperacion.Datos.Modelo
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PersonaInterna_PAR))]
    [KnownType(typeof(TipoContrato_CPO))]
    [KnownType(typeof(TipoMensajero_CPO))]
    [KnownType(typeof(MensajeroVehiculo_OPU))]
    public partial class Mensajero_CPO: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public long MEN_IdMensajero
        {
            get { return _mEN_IdMensajero; }
            set
            {
                if (_mEN_IdMensajero != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'MEN_IdMensajero' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _mEN_IdMensajero = value;
                    OnPropertyChanged("MEN_IdMensajero");
                }
            }
        }
        private long _mEN_IdMensajero;
    
        [DataMember]
        public short MEN_IdTipoMensajero
        {
            get { return _mEN_IdTipoMensajero; }
            set
            {
                if (_mEN_IdTipoMensajero != value)
                {
                    ChangeTracker.RecordOriginalValue("MEN_IdTipoMensajero", _mEN_IdTipoMensajero);
                    if (!IsDeserializing)
                    {
                        if (TipoMensajero_CPO != null && TipoMensajero_CPO.TIM_IdTipoMensajero != value)
                        {
                            TipoMensajero_CPO = null;
                        }
                    }
                    _mEN_IdTipoMensajero = value;
                    OnPropertyChanged("MEN_IdTipoMensajero");
                }
            }
        }
        private short _mEN_IdTipoMensajero;
    
        [DataMember]
        public long MEN_IdAgencia
        {
            get { return _mEN_IdAgencia; }
            set
            {
                if (_mEN_IdAgencia != value)
                {
                    _mEN_IdAgencia = value;
                    OnPropertyChanged("MEN_IdAgencia");
                }
            }
        }
        private long _mEN_IdAgencia;
    
        [DataMember]
        public string MEN_Telefono2
        {
            get { return _mEN_Telefono2; }
            set
            {
                if (_mEN_Telefono2 != value)
                {
                    _mEN_Telefono2 = value;
                    OnPropertyChanged("MEN_Telefono2");
                }
            }
        }
        private string _mEN_Telefono2;
    
        [DataMember]
        public System.DateTime MEN_FechaIngreso
        {
            get { return _mEN_FechaIngreso; }
            set
            {
                if (_mEN_FechaIngreso != value)
                {
                    _mEN_FechaIngreso = value;
                    OnPropertyChanged("MEN_FechaIngreso");
                }
            }
        }
        private System.DateTime _mEN_FechaIngreso;
    
        [DataMember]
        public System.DateTime MEN_FechaTerminacionContrato
        {
            get { return _mEN_FechaTerminacionContrato; }
            set
            {
                if (_mEN_FechaTerminacionContrato != value)
                {
                    _mEN_FechaTerminacionContrato = value;
                    OnPropertyChanged("MEN_FechaTerminacionContrato");
                }
            }
        }
        private System.DateTime _mEN_FechaTerminacionContrato;
    
        [DataMember]
        public string MEN_NumeroPase
        {
            get { return _mEN_NumeroPase; }
            set
            {
                if (_mEN_NumeroPase != value)
                {
                    _mEN_NumeroPase = value;
                    OnPropertyChanged("MEN_NumeroPase");
                }
            }
        }
        private string _mEN_NumeroPase;
    
        [DataMember]
        public System.DateTime MEN_FechaVencimientoPase
        {
            get { return _mEN_FechaVencimientoPase; }
            set
            {
                if (_mEN_FechaVencimientoPase != value)
                {
                    _mEN_FechaVencimientoPase = value;
                    OnPropertyChanged("MEN_FechaVencimientoPase");
                }
            }
        }
        private System.DateTime _mEN_FechaVencimientoPase;
    
        [DataMember]
        public string MEN_Estado
        {
            get { return _mEN_Estado; }
            set
            {
                if (_mEN_Estado != value)
                {
                    _mEN_Estado = value;
                    OnPropertyChanged("MEN_Estado");
                }
            }
        }
        private string _mEN_Estado;
    
        [DataMember]
        public bool MEN_EsContratista
        {
            get { return _mEN_EsContratista; }
            set
            {
                if (_mEN_EsContratista != value)
                {
                    _mEN_EsContratista = value;
                    OnPropertyChanged("MEN_EsContratista");
                }
            }
        }
        private bool _mEN_EsContratista;
    
        [DataMember]
        public short MEN_TipoContrato
        {
            get { return _mEN_TipoContrato; }
            set
            {
                if (_mEN_TipoContrato != value)
                {
                    ChangeTracker.RecordOriginalValue("MEN_TipoContrato", _mEN_TipoContrato);
                    if (!IsDeserializing)
                    {
                        if (TipoContrato_CPO != null && TipoContrato_CPO.TIC_IdTipoContrato != value)
                        {
                            TipoContrato_CPO = null;
                        }
                    }
                    _mEN_TipoContrato = value;
                    OnPropertyChanged("MEN_TipoContrato");
                }
            }
        }
        private short _mEN_TipoContrato;
    
        [DataMember]
        public System.DateTime MEN_FechaGrabacion
        {
            get { return _mEN_FechaGrabacion; }
            set
            {
                if (_mEN_FechaGrabacion != value)
                {
                    _mEN_FechaGrabacion = value;
                    OnPropertyChanged("MEN_FechaGrabacion");
                }
            }
        }
        private System.DateTime _mEN_FechaGrabacion;
    
        [DataMember]
        public string MEN_CreadoPor
        {
            get { return _mEN_CreadoPor; }
            set
            {
                if (_mEN_CreadoPor != value)
                {
                    _mEN_CreadoPor = value;
                    OnPropertyChanged("MEN_CreadoPor");
                }
            }
        }
        private string _mEN_CreadoPor;
    
        [DataMember]
        public long MEN_IdPersonaInterna
        {
            get { return _mEN_IdPersonaInterna; }
            set
            {
                if (_mEN_IdPersonaInterna != value)
                {
                    ChangeTracker.RecordOriginalValue("MEN_IdPersonaInterna", _mEN_IdPersonaInterna);
                    if (!IsDeserializing)
                    {
                        if (PersonaInterna_PAR != null && PersonaInterna_PAR.PEI_IdPersonaInterna != value)
                        {
                            PersonaInterna_PAR = null;
                        }
                    }
                    _mEN_IdPersonaInterna = value;
                    OnPropertyChanged("MEN_IdPersonaInterna");
                }
            }
        }
        private long _mEN_IdPersonaInterna;
    
        [DataMember]
        public bool MEN_EsMensajeroUrbano
        {
            get { return _mEN_EsMensajeroUrbano; }
            set
            {
                if (_mEN_EsMensajeroUrbano != value)
                {
                    _mEN_EsMensajeroUrbano = value;
                    OnPropertyChanged("MEN_EsMensajeroUrbano");
                }
            }
        }
        private bool _mEN_EsMensajeroUrbano;
    
        [DataMember]
        public bool MEN_AplicaPAM
        {
            get { return _mEN_AplicaPAM; }
            set
            {
                if (_mEN_AplicaPAM != value)
                {
                    _mEN_AplicaPAM = value;
                    OnPropertyChanged("MEN_AplicaPAM");
                }
            }
        }
        private bool _mEN_AplicaPAM;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public PersonaInterna_PAR PersonaInterna_PAR
        {
            get { return _personaInterna_PAR; }
            set
            {
                if (!ReferenceEquals(_personaInterna_PAR, value))
                {
                    var previousValue = _personaInterna_PAR;
                    _personaInterna_PAR = value;
                    FixupPersonaInterna_PAR(previousValue);
                    OnNavigationPropertyChanged("PersonaInterna_PAR");
                }
            }
        }
        private PersonaInterna_PAR _personaInterna_PAR;
    
        [DataMember]
        public TipoContrato_CPO TipoContrato_CPO
        {
            get { return _tipoContrato_CPO; }
            set
            {
                if (!ReferenceEquals(_tipoContrato_CPO, value))
                {
                    var previousValue = _tipoContrato_CPO;
                    _tipoContrato_CPO = value;
                    FixupTipoContrato_CPO(previousValue);
                    OnNavigationPropertyChanged("TipoContrato_CPO");
                }
            }
        }
        private TipoContrato_CPO _tipoContrato_CPO;
    
        [DataMember]
        public TipoMensajero_CPO TipoMensajero_CPO
        {
            get { return _tipoMensajero_CPO; }
            set
            {
                if (!ReferenceEquals(_tipoMensajero_CPO, value))
                {
                    var previousValue = _tipoMensajero_CPO;
                    _tipoMensajero_CPO = value;
                    FixupTipoMensajero_CPO(previousValue);
                    OnNavigationPropertyChanged("TipoMensajero_CPO");
                }
            }
        }
        private TipoMensajero_CPO _tipoMensajero_CPO;
    
        [DataMember]
        public TrackableCollection<MensajeroVehiculo_OPU> MensajeroVehiculo_OPU
        {
            get
            {
                if (_mensajeroVehiculo_OPU == null)
                {
                    _mensajeroVehiculo_OPU = new TrackableCollection<MensajeroVehiculo_OPU>();
                    _mensajeroVehiculo_OPU.CollectionChanged += FixupMensajeroVehiculo_OPU;
                }
                return _mensajeroVehiculo_OPU;
            }
            set
            {
                if (!ReferenceEquals(_mensajeroVehiculo_OPU, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("No se puede establecer el elemento FixupChangeTrackingCollection cuando se ha habilitado ChangeTracking");
                    }
                    if (_mensajeroVehiculo_OPU != null)
                    {
                        _mensajeroVehiculo_OPU.CollectionChanged -= FixupMensajeroVehiculo_OPU;
                        // Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                        // Quitar el controlador de eventos de eliminación en cascada para aquellas entidades de la colección actual.
                        foreach (MensajeroVehiculo_OPU item in _mensajeroVehiculo_OPU)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _mensajeroVehiculo_OPU = value;
                    if (_mensajeroVehiculo_OPU != null)
                    {
                        _mensajeroVehiculo_OPU.CollectionChanged += FixupMensajeroVehiculo_OPU;
                        // Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                        // Agrega el controlador de eventos de eliminación en cascada para aquellas entidades que ya se encuentran en la nueva colección.
                        foreach (MensajeroVehiculo_OPU item in _mensajeroVehiculo_OPU)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("MensajeroVehiculo_OPU");
                }
            }
        }
        private TrackableCollection<MensajeroVehiculo_OPU> _mensajeroVehiculo_OPU;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PersonaInterna_PAR = null;
            TipoContrato_CPO = null;
            TipoMensajero_CPO = null;
            MensajeroVehiculo_OPU.Clear();
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupPersonaInterna_PAR(PersonaInterna_PAR previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Mensajero_CPO.Contains(this))
            {
                previousValue.Mensajero_CPO.Remove(this);
            }
    
            if (PersonaInterna_PAR != null)
            {
                if (!PersonaInterna_PAR.Mensajero_CPO.Contains(this))
                {
                    PersonaInterna_PAR.Mensajero_CPO.Add(this);
                }
    
                MEN_IdPersonaInterna = PersonaInterna_PAR.PEI_IdPersonaInterna;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PersonaInterna_PAR")
                    && (ChangeTracker.OriginalValues["PersonaInterna_PAR"] == PersonaInterna_PAR))
                {
                    ChangeTracker.OriginalValues.Remove("PersonaInterna_PAR");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PersonaInterna_PAR", previousValue);
                }
                if (PersonaInterna_PAR != null && !PersonaInterna_PAR.ChangeTracker.ChangeTrackingEnabled)
                {
                    PersonaInterna_PAR.StartTracking();
                }
            }
        }
    
        private void FixupTipoContrato_CPO(TipoContrato_CPO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Mensajero_CPO.Contains(this))
            {
                previousValue.Mensajero_CPO.Remove(this);
            }
    
            if (TipoContrato_CPO != null)
            {
                if (!TipoContrato_CPO.Mensajero_CPO.Contains(this))
                {
                    TipoContrato_CPO.Mensajero_CPO.Add(this);
                }
    
                MEN_TipoContrato = TipoContrato_CPO.TIC_IdTipoContrato;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TipoContrato_CPO")
                    && (ChangeTracker.OriginalValues["TipoContrato_CPO"] == TipoContrato_CPO))
                {
                    ChangeTracker.OriginalValues.Remove("TipoContrato_CPO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TipoContrato_CPO", previousValue);
                }
                if (TipoContrato_CPO != null && !TipoContrato_CPO.ChangeTracker.ChangeTrackingEnabled)
                {
                    TipoContrato_CPO.StartTracking();
                }
            }
        }
    
        private void FixupTipoMensajero_CPO(TipoMensajero_CPO previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Mensajero_CPO.Contains(this))
            {
                previousValue.Mensajero_CPO.Remove(this);
            }
    
            if (TipoMensajero_CPO != null)
            {
                if (!TipoMensajero_CPO.Mensajero_CPO.Contains(this))
                {
                    TipoMensajero_CPO.Mensajero_CPO.Add(this);
                }
    
                MEN_IdTipoMensajero = TipoMensajero_CPO.TIM_IdTipoMensajero;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TipoMensajero_CPO")
                    && (ChangeTracker.OriginalValues["TipoMensajero_CPO"] == TipoMensajero_CPO))
                {
                    ChangeTracker.OriginalValues.Remove("TipoMensajero_CPO");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TipoMensajero_CPO", previousValue);
                }
                if (TipoMensajero_CPO != null && !TipoMensajero_CPO.ChangeTracker.ChangeTrackingEnabled)
                {
                    TipoMensajero_CPO.StartTracking();
                }
            }
        }
    
        private void FixupMensajeroVehiculo_OPU(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (MensajeroVehiculo_OPU item in e.NewItems)
                {
                    item.Mensajero_CPO = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("MensajeroVehiculo_OPU", item);
                    }
                    // Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                    // Actualizar la escucha de eventos para que se refiera al nuevo extremo dependiente.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MensajeroVehiculo_OPU item in e.OldItems)
                {
                    if (ReferenceEquals(item.Mensajero_CPO, this))
                    {
                        item.Mensajero_CPO = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("MensajeroVehiculo_OPU", item);
                        // Eliminar el extremo dependiente de esta asociación de identificación. Si el estado actual es agregado,
                        // permite que la relación se modifique sin eliminar el elemento dependiente.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // Este es el extremo principal en una asociación que realiza eliminaciones en cascada.
                    // Quitar el extremo dependiente anterior de la escucha de eventos.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
