//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.ParametrosOperacion.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class TipoCombustible_CPO: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public int TCO_IdTipoCombustible
        {
            get { return _tCO_IdTipoCombustible; }
            set
            {
                if (_tCO_IdTipoCombustible != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'TCO_IdTipoCombustible' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _tCO_IdTipoCombustible = value;
                    OnPropertyChanged("TCO_IdTipoCombustible");
                }
            }
        }
        private int _tCO_IdTipoCombustible;
    
        [DataMember]
        public string TCO_Descripcion
        {
            get { return _tCO_Descripcion; }
            set
            {
                if (_tCO_Descripcion != value)
                {
                    _tCO_Descripcion = value;
                    OnPropertyChanged("TCO_Descripcion");
                }
            }
        }
        private string _tCO_Descripcion;
    
        [DataMember]
        public System.DateTime TCO_FechaGrbacion
        {
            get { return _tCO_FechaGrbacion; }
            set
            {
                if (_tCO_FechaGrbacion != value)
                {
                    _tCO_FechaGrbacion = value;
                    OnPropertyChanged("TCO_FechaGrbacion");
                }
            }
        }
        private System.DateTime _tCO_FechaGrbacion;
    
        [DataMember]
        public string TCO_CreadoPor
        {
            get { return _tCO_CreadoPor; }
            set
            {
                if (_tCO_CreadoPor != value)
                {
                    _tCO_CreadoPor = value;
                    OnPropertyChanged("TCO_CreadoPor");
                }
            }
        }
        private string _tCO_CreadoPor;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
