//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CO.Servidor.Dominio.Comun.AdmEstadosGuia.Datos.Modelo
{
    [DataContract(IsReference = true)]
    public partial class EstadoGuiaTraza_MEN: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long EGT_IdEstadoGuiaLog
        {
            get { return _eGT_IdEstadoGuiaLog; }
            set
            {
                if (_eGT_IdEstadoGuiaLog != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'EGT_IdEstadoGuiaLog' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _eGT_IdEstadoGuiaLog = value;
                    OnPropertyChanged("EGT_IdEstadoGuiaLog");
                }
            }
        }
        private long _eGT_IdEstadoGuiaLog;
    
        [DataMember]
        public long EGT_IdAdminisionMensajeria
        {
            get { return _eGT_IdAdminisionMensajeria; }
            set
            {
                if (_eGT_IdAdminisionMensajeria != value)
                {
                    _eGT_IdAdminisionMensajeria = value;
                    OnPropertyChanged("EGT_IdAdminisionMensajeria");
                }
            }
        }
        private long _eGT_IdAdminisionMensajeria;
    
        [DataMember]
        public long EGT_NumeroGuia
        {
            get { return _eGT_NumeroGuia; }
            set
            {
                if (_eGT_NumeroGuia != value)
                {
                    _eGT_NumeroGuia = value;
                    OnPropertyChanged("EGT_NumeroGuia");
                }
            }
        }
        private long _eGT_NumeroGuia;
    
        [DataMember]
        public short EGT_IdEstadoGuia
        {
            get { return _eGT_IdEstadoGuia; }
            set
            {
                if (_eGT_IdEstadoGuia != value)
                {
                    _eGT_IdEstadoGuia = value;
                    OnPropertyChanged("EGT_IdEstadoGuia");
                }
            }
        }
        private short _eGT_IdEstadoGuia;
    
        [DataMember]
        public string EGT_DescripcionEstado
        {
            get { return _eGT_DescripcionEstado; }
            set
            {
                if (_eGT_DescripcionEstado != value)
                {
                    _eGT_DescripcionEstado = value;
                    OnPropertyChanged("EGT_DescripcionEstado");
                }
            }
        }
        private string _eGT_DescripcionEstado;
    
        [DataMember]
        public bool EGT_EsVisible
        {
            get { return _eGT_EsVisible; }
            set
            {
                if (_eGT_EsVisible != value)
                {
                    _eGT_EsVisible = value;
                    OnPropertyChanged("EGT_EsVisible");
                }
            }
        }
        private bool _eGT_EsVisible;
    
        [DataMember]
        public string EGT_Observacion
        {
            get { return _eGT_Observacion; }
            set
            {
                if (_eGT_Observacion != value)
                {
                    _eGT_Observacion = value;
                    OnPropertyChanged("EGT_Observacion");
                }
            }
        }
        private string _eGT_Observacion;
    
        [DataMember]
        public string EGT_IdLocalidad
        {
            get { return _eGT_IdLocalidad; }
            set
            {
                if (_eGT_IdLocalidad != value)
                {
                    _eGT_IdLocalidad = value;
                    OnPropertyChanged("EGT_IdLocalidad");
                }
            }
        }
        private string _eGT_IdLocalidad;
    
        [DataMember]
        public string EGT_NombreLocalidad
        {
            get { return _eGT_NombreLocalidad; }
            set
            {
                if (_eGT_NombreLocalidad != value)
                {
                    _eGT_NombreLocalidad = value;
                    OnPropertyChanged("EGT_NombreLocalidad");
                }
            }
        }
        private string _eGT_NombreLocalidad;
    
        [DataMember]
        public string EGT_IdModulo
        {
            get { return _eGT_IdModulo; }
            set
            {
                if (_eGT_IdModulo != value)
                {
                    _eGT_IdModulo = value;
                    OnPropertyChanged("EGT_IdModulo");
                }
            }
        }
        private string _eGT_IdModulo;
    
        [DataMember]
        public System.DateTime EGT_FechaGrabacion
        {
            get { return _eGT_FechaGrabacion; }
            set
            {
                if (_eGT_FechaGrabacion != value)
                {
                    _eGT_FechaGrabacion = value;
                    OnPropertyChanged("EGT_FechaGrabacion");
                }
            }
        }
        private System.DateTime _eGT_FechaGrabacion;
    
        [DataMember]
        public string EGT_CreadoPor
        {
            get { return _eGT_CreadoPor; }
            set
            {
                if (_eGT_CreadoPor != value)
                {
                    _eGT_CreadoPor = value;
                    OnPropertyChanged("EGT_CreadoPor");
                }
            }
        }
        private string _eGT_CreadoPor;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
